/* ═══════════════════════════════════════════════════════════
   SPEAKER NOTES — English
   Voice-over narration style — spoken directly to the listener.
   Key = slide id  or  "slide-{index}" for slides without an id.
   ═══════════════════════════════════════════════════════════ */
window.NOTES_EN = {

  /* ── PREFACE ─────────────────────────────────────────────── */

  "slide-0": "Welcome to Understanding Artificial Intelligence — a hands-on journey from foundations to autonomous agents. This course is designed for developers, architects, product managers, and anyone curious about how modern AI really works under the hood. We cover six chapters, each building on the previous one, so you leave with a coherent picture instead of disconnected buzzwords. You can switch language at any time using the menu in the top corner. Let's begin.",

  "slide-1": "Before we dive in, a quick orientation. Use the arrow keys or swipe to move between slides. The menu button opens a chapter navigator so you can jump to any section. Each chapter ends with a references slide for further reading. Interactive slides — those with animations or sliders — are self-contained: just follow the on-screen cues. This material is available in English, Italian, French, and Spanish — switch languages any time from the top menu.",

  "agenda": "Here is what we will cover together. Six chapters, each building on the last. Chapter one establishes the foundation: what AI really is, how transformers work, and what all those parameters mean. Chapter two is about prompt engineering — the craft of communicating precisely with AI models. Chapter three covers AI-assisted coding, from autocomplete to fully agentic tools. Chapter four explains Retrieval-Augmented Generation — how to connect AI to your own private data. Chapter five explores autonomous AI agents and the Model Context Protocol. Chapter six addresses ethics, bias, and governance. The annex contains reference material you can return to at any time.",

  /* ── CHAPTER 1 ───────────────────────────────────────────── */

  "chapter-1": "Chapter one lays the conceptual foundation for everything that follows. The single most important idea here is this: artificial intelligence is not magic — it is mathematics applied to enormous amounts of data. We will move from deterministic systems, like a traditional if-then program that always gives the same answer, to probabilistic ones, where the model makes its best prediction based on patterns learned from billions of examples. By the end of this chapter, you will understand how a transformer neural network works, what temperature and tokens really mean, and why specialized hardware matters.",

  "slide-4": "The most fundamental distinction in modern AI is the shift from deterministic to probabilistic computation. Traditional software is deterministic: give it the same input and it always returns the exact same output. Language models are probabilistic: given the same question, they can produce different answers each time. This is not a flaw — it is by design. The model does not look up a fixed answer. Instead, it samples from a probability distribution over possible next words. The temperature parameter controls how narrow or wide that distribution is. This shift — from guaranteed correctness to optimized likelihood — is the mental model that everything else in this course builds on.",

  "slide-5": "There are effectively two eras in the history of modern AI: everything before 2017, and everything after. Before 2017, the dominant approach was recurrent neural networks, which processed text one word at a time and tended to forget context from more than a few sentences back. Then in 2017, a team at Google published a paper titled Attention Is All You Need, introducing the transformer architecture. Its key innovation: every word in a sentence can attend directly to every other word simultaneously, regardless of distance. That single insight unlocked a step-change in capability. By 2020, GPT-3 demonstrated that scaling this architecture with enough data and compute produced a model that could learn new tasks from just a few examples — with no additional training.",

  "slide-6": "Three forces converged between 2017 and 2023 to accelerate AI beyond all previous expectations. First, data: the internet produced text at unprecedented scale — CommonCrawl, Wikipedia, GitHub, and billions of digitized books provided the raw training material. Second, compute: GPUs evolved from gaming hardware into massively parallel computing engines capable of training models with hundreds of billions of parameters. Third, the transformer architecture itself: it could be trained far more efficiently than previous approaches, and its capability scaled predictably with more data and compute. When these three forces combined, progress that once took a decade began happening in months.",

  "slide-7": "This animation shows what actually happens when a language model generates text. Each step you advance produces exactly one token. Notice the probability bars: the model is never certain which word comes next. It maintains a full distribution of possibilities and samples from it. When temperature is above zero, lower-probability tokens still have a chance of being selected — which is why generating the same prompt twice can produce different results. It also explains why language models stream output token by token rather than returning a complete answer instantly: they literally compute the text one token at a time.",

  "slide-8": "Let us trace the path a piece of text takes through a transformer. First, raw text is split into tokens — small chunks of characters. Each token is converted into an embedding: a vector of numbers encoding its meaning in high-dimensional space. These embeddings then pass through the self-attention mechanism — the heart of the transformer. Here, every token examines every other token and decides how much weight to place on each one. This is how the model resolves that 'it' refers to 'cat' several words back, without any explicit rules. After attention, the result passes through feedforward layers, and finally the model outputs a probability distribution over the next possible token. This entire process repeats for every single token generated.",

  "slide-03a": "This slide walks through the complete sampling pipeline — the path from input text to a single generated token. Embeddings convert each token into a high-dimensional vector. Self-attention lets every token reference all others. Feed-forward layers apply a learned non-linear transformation. Softmax converts raw output scores into a proper probability distribution over the entire vocabulary. Finally, the sampling step draws the next token from that distribution, shaped by temperature and Top-P. Understanding this pipeline helps you reason about why parameter choices have the effects they do on model output.",

  "slide-10": "Understanding the key generation parameters is essential for working with any AI model. Temperature is the most important: at zero, the model always picks the highest-probability token, producing deterministic and reproducible output. Above zero, lower-probability tokens get a chance — increasing creativity but also unpredictability. For code generation and data extraction, keep temperature low. For brainstorming, raise it. A token is roughly three-quarters of an English word — and the unit your API bill is calculated in. Max tokens caps the response length and your cost per call. Top-P controls the size of the candidate pool. Change these parameters one at a time, because they interact.",

  "slide-11": "Three practical limitations matter most when building real-world AI applications. First, language models have no persistent memory: each conversation starts fresh, with no recollection of anything said before. If continuity matters, you must inject the relevant history into the prompt yourself. Second, context windows are finite: every model has a maximum input length, and content beyond that limit is simply cut off. Third, hallucination is inherent: models may produce confident, fluent, factually incorrect output whenever they encounter topics outside their training distribution. Understanding these constraints upfront prevents a category of surprises in production.",

  "slide-12": "Why do AI models require such specialized hardware? At their core, neural network layers are enormous matrix multiplications — multiplying arrays with billions of numbers simultaneously. GPUs were originally built for graphics rendering, which involves exactly this kind of highly parallel computation. A modern H100 GPU has eighty gigabytes of high-bandwidth memory and processes thousands of operations in parallel. Cloud providers like Azure, AWS, and Google Cloud expose these capabilities as APIs, so you pay per token rather than buying hardware. The cost curve is dramatic: inference cost drops roughly ten times per year — which is why running capable models locally is already practical today.",

  "slide-13": "One of the most striking properties of modern large language models is their generality. Every task in this word cloud — sentiment analysis, translation, summarization, code generation, named entity recognition, classification, question answering, and dozens more — can be handled by a single foundation model. Before 2020, each of these tasks required a dedicated, purpose-trained model. Today, one model handles all of them. The implication is profound: the marginal cost of trying a new AI use case is now essentially zero, because you are reusing the same model.",

  "slide-14": "The landscape of AI models changes roughly every three to six months, so treat this table as a snapshot. Key dimensions when choosing a model: capability for your specific task, context window size, cost per token, whether it is open-weight or proprietary, and where inference runs for compliance. Gemini 2.0 leads on context window at over one million tokens. Llama 3 and Mistral are open-weight and can be self-hosted — important for data sovereignty. GPT-4o mini delivers most of full GPT-4o quality at a fraction of the cost. Your choice depends on task, budget, latency, and compliance requirements.",

  "slide-15": "Every language model has predictable failure modes you should know before deploying one. Hallucination is the most dangerous: the model generates text that sounds fluent and confident but is factually wrong — with no visible signal of uncertainty. Knowledge cutoff means the model knows nothing about events after its training data ends. Mathematical reasoning is unreliable — models often get arithmetic wrong in ways that feel surprising given their other capabilities. And bias: because models learn patterns from human-generated text, they reflect the biases in that text. None of these are bugs that will be fixed — they are fundamental properties of the current architecture. Design your system accordingly.",

  "ai-system-architecture": "This diagram shows the complete layered architecture of a modern AI system. At the top are the actors: the end user sending queries, the developer who builds and monitors the system, and any external services or APIs. Requests flow down through an application layer that handles authentication, rate limiting, and conversation context. Below that sits the AI integration layer: prompt construction, optional retrieval from a vector database for RAG, and the call to the language model. The response flows back up through the same layers. Each layer is an opportunity to add safety checks, logging, and control — which is why well-designed AI systems are built in layers rather than as a direct user-to-model connection.",

  "slide-17": "Let us consolidate the key ideas from chapter one. LLMs are probabilistic, not deterministic: the same question can produce different answers, and that is by design. Transformers made this possible by processing entire sequences simultaneously through self-attention. Temperature and token limits are the primary controls you will use in every integration. Context windows define the maximum information a model can reason over in one call. And all the capabilities — translation, code, summarization, reasoning — emerge from a single pre-training objective: predict the next token. That is the foundation everything else in this course builds on.",

  "slide-18": "Let us close chapter one with the foundational references. The paper that started it all is Attention Is All You Need by Vaswani and colleagues, published by Google in 2017 — it introduced the transformer architecture that underpins every modern language model. The GPT-3 paper from OpenAI in 2020 showed that scaling transformers unlocks few-shot learning — the ability to perform new tasks from just a few examples in the prompt. For an excellent visual explanation of how attention works, Jay Alammar's Illustrated Transformer is highly recommended and freely available online.",

  /* ── CHAPTER 2 ───────────────────────────────────────────── */

  "chapter-2": "Chapter two is where theory becomes practice. Prompt engineering is the discipline of communicating precisely with AI models. How you phrase a request has an enormous effect on the quality of the response — and there are repeatable patterns that reliably improve results. We will dissect the anatomy of a good prompt, learn six proven patterns from zero-shot to chain-of-thought, and look at real before-and-after rewrites. These skills apply to every AI model, not just the ones available today.",

  "slide-20": "A well-structured prompt has four layers, and understanding each one unlocks significantly better results. At the top is the system prompt: where you define the model's role, constraints, and persona. A simple instruction like you are a senior data engineer specializing in Python measurably shifts the style and depth of the response. Next is context: the relevant background information the model needs. Then comes the user message — the actual task or question. Finally, output format instructions: tell the model explicitly whether you want JSON, a numbered list, a paragraph, or a table. The model does not know your downstream requirements unless you specify them.",

  "slide-21": "Three foundational prompt patterns cover the vast majority of use cases. Zero-shot: describe the task directly, with no examples — modern models handle most tasks well this way. Few-shot: provide two to five input-output examples demonstrating the format and style you want — especially effective for consistent, structured output. Chain-of-thought: ask the model to reason step by step before giving its final answer — this dramatically improves accuracy on mathematical, logical, and multi-step reasoning tasks. These patterns combine naturally: a system prompt plus few-shot examples plus chain-of-thought is one of the most reliable prompt architectures in production.",

  "slide-22": "Beyond the basics, several advanced patterns extend what prompting can achieve. System prompts define the model's persona, rules, and guardrails — users never see them, but they shape every response. Role playing assigns a specific expert persona to improve output depth. Retrieval-Augmented Generation injects relevant documents retrieved from a knowledge base into the prompt before generation — covered in full in chapter four. Tool use allows the model to request execution of external functions — the foundation of agents in chapter five. These techniques are especially valuable when building production AI systems.",

  "slide-23": "The most common mistake when working with AI is writing vague prompts. Compare summarize this document with summarize this document in exactly three bullet points for a non-technical executive, using plain English, no jargon, maximum fifteen words per bullet. The second consistently produces better, more usable output. Key guidelines: always assign a role in the system prompt; express constraints positively — say what you want, not what you do not want; be explicit about length and format; and include an example when the desired output style is not obvious. Test any prompt across at least ten diverse inputs before shipping it to production.",

  "slide-24": "The prompt makeover is one of the most effective ways to build intuition. Take a mediocre prompt and apply a structured rewrite: add a clear role, specify the output format, add constraints, include an example. The pattern is remarkably consistent: the naive before-prompt produces generic, often unusable output; the engineered after-prompt produces something specific, structured, and ready to use. The gap between them is not the model — it is the quality of the instruction. A useful mental model: think of a prompt as a program you are writing for a very capable but extremely literal-minded interpreter.",

  "slide-25": "Let us see how the same prompting principles apply across different professional roles. A manager might ask the AI to summarize a twenty-page report in five bullet points tailored for a non-technical audience — adding explicit format constraints and a target reader. A developer might ask it to write a unit test for a specific function with exact coverage requirements. A data analyst might request a Python script that ingests a CSV, computes summary statistics, and flags outliers. The pattern is the same in every case: state the role, provide context, specify the format. The value is not in the AI doing your thinking — it is in handling the mechanical production work so you can focus on judgment.",

  "slide-26": "This interactive playground lets you explore how generation parameters affect output in real time. Set temperature to zero and generate the same prompt twice — you will get identical results every time. Increase temperature gradually and watch how the output diversifies. Top-P controls the candidate pool: a low value restricts the model to the most probable tokens; a high value opens up more creative territory. These are not abstract settings — they directly control the consistency-versus-creativity trade-off in your application. Customer-facing applications that need reliable answers benefit from low temperature. Creative tools benefit from high temperature.",

  "slide-27": "Now it is your turn to practice. Take a real task — writing a job description, analyzing a dataset, drafting a technical proposal — and write an initial prompt. Run it, see what you get, then improve it systematically: add a role, add format instructions, add an example. Compare each iteration's output to the previous one. You will find that each refinement makes a meaningful difference. The goal is not perfection on the first attempt — it is to build the iterative muscle of generate, evaluate critically, refine, and repeat. That loop is the core skill of effective prompt engineering.",

  "slide-28": "The key takeaways from chapter two. Every effective prompt has four parts: role, context, task, and format. Miss any one and quality suffers. Prompting patterns — zero-shot, few-shot, chain-of-thought — are composable: use them together for complex requirements. Advanced techniques like system prompts and structured output extend prompting into architecture territory. And remember: a prompt is a program. Treat it like code — version it, test it across diverse inputs, and refine it iteratively. The best prompt engineers think of themselves as interface designers for a very powerful but very literal system.",

  "slide-29": "The key references for chapter two. Anthropic and OpenAI both publish detailed prompt engineering guides that reflect the latest best practices for their models — make these your first stop. The Chain-of-Thought Prompting paper by Wei and colleagues established why reasoning step by step dramatically improves performance on complex tasks. The promptingguide.ai website and the Learn Prompting course are excellent structured resources for building these skills from the ground up.",

  /* ── CHAPTER 3 ───────────────────────────────────────────── */

  "chapter-3": "Chapter three is about what happens when AI becomes your coding partner. We will cover the full spectrum: from simple autocomplete, to conversational coding assistants, to fully agentic tools that understand your entire codebase and make autonomous multi-file changes. There is real, measurable productivity upside — backed by controlled studies. There are also real risks when these tools are used without understanding what they produce. We will look at both sides honestly.",

  "slide-31": "In February 2025, AI researcher Andrej Karpathy coined the phrase vibe coding to describe a new way of writing software. You describe what you want in natural language, the AI generates the code, you run it, observe what breaks, and describe the fix. You do not necessarily read every line before shipping it. Developers who embrace this rapid iteration loop report working three to five times faster on well-defined tasks. But there is a critical caveat: vibe coding amplifies your existing skills — it does not replace understanding. If you cannot evaluate whether the code is correct and secure, you will not catch the mistakes the AI confidently makes.",

  "slide-32": "The AI-assisted development workflow follows a clear loop: describe the task precisely, generate code, review it critically, run it, identify what is wrong, and refine. The word to emphasize is critically. AI tools are excellent at generating boilerplate, scaffolding, unit tests, and well-specified transformations. They struggle with implicit business logic, security-sensitive code, and anything requiring deep contextual knowledge of your codebase. Tools like Cursor and Windsurf reduce friction with inline diff views and multi-file editing. The best practitioners have brought this iteration cycle down to under two minutes per change.",

  "slide-33": "The AI coding tool landscape has three tiers. IDE-integrated assistants: GitHub Copilot with the widest enterprise adoption; Cursor, popular with startups for its multi-file composer mode; and Windsurf, which excels at large-codebase awareness. Fully autonomous agents like Devin can receive a task, browse documentation, write code, run tests, and commit changes with minimal human interaction. The key differentiator when evaluating tools is codebase context: how much of your existing code can the tool hold in context at once. More context means more accurate, contextually appropriate suggestions.",

  "slide-34": "AI coding tools work best on well-defined, self-contained problems: CRUD APIs, unit tests, data transformation scripts, configuration files, regular expressions, CSS layouts, and documentation. Where they consistently struggle: complex business logic with unstated constraints, security-critical code where a subtle mistake is exploitable, and legacy codebases where years of decisions live in undocumented conventions. The golden rule: the clearer your specification, the better the output. AI amplifies the quality of your thinking — it does not substitute for it.",

  "slide-35": "The productivity gains from AI coding tools are real and measurable. A randomized controlled trial by GitHub and Microsoft in 2022 found that developers using Copilot completed an HTTP server task fifty-five percent faster. The GitHub Octoverse 2024 report found Copilot generates an average of forty-six percent of code in files where it is enabled. The Stack Overflow Developer Survey showed seventy-six percent of developers are already using or planning to adopt AI coding tools. For senior developers, the role is shifting: from writing individual functions toward architecture decisions, rigorous AI-output review, and engineering the precise specifications that direct AI effectively.",

  "slide-36": "This exercise is about the process, not just the result. Take any CSV file and use an AI coding tool to write an analysis script: summary statistics, outlier detection, and a simple visualization. Pay attention to where the AI makes assumptions without asking — column types, missing value handling, output format. Notice what it gets wrong the first time. Practice the loop: generate, review critically, test, and refine. By the end you will have a working script and a concrete intuition for exactly where AI assistance adds value and where your judgment remains indispensable.",

  "slide-37": "The key takeaways from chapter three. AI coding tools deliver real productivity gains — thirty-five to fifty-five percent on well-defined tasks, backed by controlled studies. But amplification works in both directions: good practices scale up, and poor ones do too. Always review AI-generated code critically — not just for correctness but for security, edge cases, and maintainability. The emerging role is not prompter but AI-enabled engineer: someone who specifies intent precisely, evaluates AI output rigorously, and integrates it safely into a larger system. Vibe first, review always.",

  "slide-38": "The references for chapter three. Karpathy's original vibe-coding post defines the philosophy of this new development mode. The Kalliamvakou study is the most rigorous academic measurement of Copilot's productivity impact. The GitHub Octoverse 2024 report provides industry-wide adoption statistics. Cursor's documentation is worth exploring as a concrete example of what an AI-native IDE looks like beyond a traditional plugin.",

  /* ── CHAPTER 4 ───────────────────────────────────────────── */

  "chapter-4": "Chapter four addresses one of the most important limitations of language models in production: they do not know your private data, and their training has a hard knowledge cutoff. Retrieval-Augmented Generation — RAG — is the solution, and it is the most widely deployed AI architecture in enterprise software today. Understanding RAG is what separates someone who uses AI from someone who builds with it. We will cover the full pipeline: document indexing, embedding, vector search, retrieval, and grounded generation.",

  "slide-40": "Why not simply fine-tune the model on your internal documents? Three reasons: fine-tuning is expensive, it takes days or weeks, and — most critically — facts change. When a document is updated, you would need to retrain the entire model. RAG takes a fundamentally different approach: rather than baking knowledge into the model weights, you retrieve the relevant information at query time and inject it directly into the prompt. Think of it as giving the model a search engine and copy-paste rights before it answers — it reads the retrieved documents, then responds. This makes RAG cheaper, faster to update, more auditable, and more controllable than fine-tuning for any information that changes over time.",

  "slide-41": "The RAG pipeline has two distinct phases. First is indexing, which happens once or periodically: documents are split into chunks, each chunk is converted into an embedding vector, and those vectors are stored in a vector database. Second is querying, which happens on every user request: the question is embedded using the same model, the vector database finds the closest matching chunks, those chunks are injected into the prompt as context, and the language model generates a grounded answer. The quality of every step — chunking strategy, embedding model, retrieval depth — determines the quality of the final response.",

  "slide-42": "Here is the intuition behind embeddings. Imagine placing every piece of text into a high-dimensional space where semantically similar texts land close together. Revenue declined last quarter and sales dropped in Q3 would be very close, even though they share no words. Revenue and puppy would be far apart. A vector database is an index optimized for finding nearest neighbors in this space at high speed, using algorithms like HNSW that avoid comparing every pair of vectors. For most organizations, pgvector — a PostgreSQL extension — is the pragmatic starting point. Pinecone and Weaviate are purpose-built vector databases suited to larger-scale deployments.",

  "slide-43": "How you split documents into chunks has a larger impact on RAG quality than almost any other decision — including which language model you use. Recursive character text splitting tries to split on paragraph, sentence, then word boundaries — a solid default. Semantic chunking uses embedding similarity between adjacent sentences to find natural topic boundaries — more expensive but it preserves meaning better. Hierarchical indexing stores both parent and child chunks: retrieval uses child chunks for precision, but provides the parent chunk to the model for fuller context. For most content, a chunk size of five hundred to one thousand tokens with ten to twenty percent overlap is a reliable starting point.",

  "slide-44": "This before-and-after example makes the stakes of chunking concrete. The query is: what is the parental leave policy for adoptive parents? If the HR handbook is chunked mechanically every five hundred characters, the relevant policy text may be split across two chunks — neither of which ranks high in a vector search because each chunk alone is incomplete. With semantic chunking — splitting at natural topic boundaries — the entire parental leave section stays together, retrieves cleanly, and produces a correct, complete answer. Chunk size and overlap are not configuration details. They are architectural decisions that directly determine whether your RAG system works.",

  "slide-45": "RAG is the number one production AI architecture in 2025, solving three critical problems at once. It grounds model responses in verifiable source documents, turning a black-box model into a transparent assistant that can cite its sources. It eliminates knowledge cutoff issues — update your document index and the model's effective knowledge updates immediately, no retraining needed. And it makes AI auditable: in regulated industries, tracing every claim to a source document is often a compliance requirement. Common applications include internal knowledge bases, technical documentation Q&A, legal and compliance research, and customer support with access to live product information.",

  "slide-46": "For this architecture exercise, design a RAG system for a real use case you care about. Work through each decision: what are your source documents, and how frequently do they change? What chunk size and overlap makes sense for this content type? What metadata should accompany each chunk to enable filtering by date, author, or access level? How do you handle sensitive documents that should not be broadly retrievable? And how do you instruct the model to say I do not know when retrieved context does not answer the question — rather than hallucinating? Getting these decisions right upfront saves enormous debugging time later.",

  "slide-47": "The key takeaways from chapter four. RAG solves the frozen knowledge problem by retrieving relevant documents at query time — no retraining needed, always current. Chunking strategy and embedding model choice have more impact on quality than the choice of language model. Always include a metadata filter and an explicit instruction for the model to acknowledge when it lacks relevant information. And RAG makes AI auditable: every response can be traced to a source document, which is often a compliance requirement in regulated industries.",

  "slide-48": "The key references for chapter four. The original RAG paper by Lewis and colleagues, published in 2020, showed state-of-the-art results on open-domain question answering. LlamaIndex and LangChain are the two leading open-source frameworks for building production RAG pipelines — both have excellent documentation. The 2023 survey by Gao and colleagues provides a comprehensive map of naive, advanced, and modular RAG variants, with a clear assessment of when each approach is most effective.",

  /* ── CHAPTER 5 ───────────────────────────────────────────── */

  "chapter-5": "Chapter five moves from model to agent. Until now we have been talking about models that respond: you ask, they answer. An AI agent is different — it acts. It can browse the web, call APIs, write and execute code, query databases, and send emails — autonomously, chaining multiple decisions without a human in the loop for every step. This shift from response to action is one of the most consequential developments in AI in 2025. We will cover the ReAct reasoning loop, the four agentic design patterns, the Model Context Protocol, and multi-agent orchestration.",

  "slide-50": "An AI agent differs from a chatbot in one fundamental way: it acts. Where a chatbot returns text, an agent issues instructions that cause things to happen in the real world. The basic structure is a loop called ReAct — short for Reason and Act. The model observes the current state, reasons about what to do next, takes an action — calling a function, querying a database, running code — observes the result, and reasons again. This loop continues until the task is complete. Agents can run for minutes or hours, making dozens of autonomous decisions. That power is matched by risk: clear scope boundaries and human oversight checkpoints are essential.",

  "slide-51": "Andrew Ng identified four agentic design patterns that make AI workflows dramatically more capable. Reflection: the model generates output, then critiques and revises its own work — this alone can push code generation accuracy from around fifty percent to over ninety. Tool use: the model calls external functions to interact with real systems. Planning: the model decomposes a complex task into subtasks before executing. Multi-agent collaboration: multiple specialized models work as a team. The key insight: iterative agentic workflows consistently outperform a single one-shot prompt, sometimes even when using a less capable base model.",

  "slide-52": "The ReAct pattern, introduced by Yao and colleagues in 2022, works by making the model's chain of thought explicit in the prompt. Before every action, the model writes a thought — its reasoning about the current situation. Then it specifies the action. Then it observes the result. Then it writes another thought. This interleaving of reasoning and action is what makes agents reliable on complex tasks, because the model verbalizes its plan before executing it. It also makes agent behavior inspectable: you can read the thought trace and understand exactly why each decision was made. Well-engineered agents include retry logic and fallback strategies for when a tool call fails.",

  "slide-53": "Function calling and tool use are how agents interact with the world. Rather than returning plain text, the model emits a structured JSON payload specifying the function it wants to call and the arguments to pass. Your application code receives this JSON, executes the actual function — calling a REST API, querying a database, running a calculation — and returns the result back to the model. This architecture is crucial for security: the model requests an action, but your code decides whether to execute it. You can add validation, rate limiting, and human approval gates for irreversible actions. The agent asks; you control what actually happens.",

  "slide-54": "The Model Context Protocol, or MCP, was released by Anthropic in November 2024 and quickly became the standard interface for connecting AI applications to external tools. Before MCP, every AI product had to build custom integrations for every tool it needed — multiplying maintenance burden across the ecosystem. MCP defines a universal protocol: write an MCP server for your tool once, and any MCP-compatible client — Cursor, VS Code Copilot, Claude, Windsurf — can use it immediately without additional work. This is analogous to the Language Server Protocol, which solved the same problem in the IDE world: write a language server once and every compatible editor gets support for free.",

  "slide-55": "When a single agent is not enough, multi-agent frameworks let you orchestrate several specialized agents working together. LangGraph from the LangChain team is the most production-ready option: it forces you to model your agent as an explicit state machine with defined states and transitions, making the system inspectable, resumable, and safe to interrupt for human review. AutoGen from Microsoft uses a group-chat model where agents communicate via a shared message thread — well-suited for debate and refinement workflows. The practical advice: start with the simplest possible single agent and add agents only when a single agent demonstrably fails. Complexity in multi-agent systems grows fast, and so do failure modes.",

  "slide-56": "The key takeaways from chapter five. The difference between an LLM and an agent is action: an agent can call tools, execute code, and make decisions across multiple steps. The ReAct loop — reason, act, observe, repeat — is the pattern that makes agents reliable and inspectable. Tool use is architecturally critical: the model requests an action, but your application decides what to actually execute. MCP is rapidly becoming the universal interface for AI tool integrations. And multi-agent systems add complexity fast — start with the simplest design and add agents only when a single agent demonstrably fails.",

  "slide-57": "The key references for chapter five. The ReAct paper by Yao and colleagues is the foundational work on combining reasoning and acting in AI agents. The Anthropic Model Context Protocol documentation describes the open standard now widely adopted across AI development tools. DeepLearning.AI's short courses on agents and tool use are the best hands-on introduction — several are free. LangGraph's documentation and examples are excellent for anyone building production-grade agent systems.",

  /* ── CHAPTER 6 ───────────────────────────────────────────── */

  "chapter-6": "Chapter six asks the harder question: just because AI can do something, should it — and under what conditions? After five chapters about capability, this chapter is about responsibility. We will look at documented cases where AI systems caused real harm: biased hiring tools, flawed criminal risk scores, fabricated legal citations, and deepfake fraud. We will cover the EU AI Act, the world's first binding AI law. And we will discuss governance frameworks you can apply to your own deployments. Responsible AI is not a brake on innovation — it is what makes innovation trustworthy.",

  "slide-59": "The two most important limitations of current AI models are bias and hallucination. Bias: models learn patterns from human-generated data — including human prejudices. A hiring model trained on historical data may learn to prefer certain demographics not because it was programmed to, but because that pattern existed in the training set. Hallucination: models generate text that sounds confident and fluent but is factually wrong. This happens because the model is predicting statistically plausible tokens, not retrieving verified facts. Both are predictable, systematic failures. Design your AI systems with these failure modes in mind from day one.",

  "slide-60": "The European Union AI Act is the world's first comprehensive, binding AI law, entering into force in August 2024. It uses a risk-based tiered approach. Most applications fall into minimal or limited risk categories with lightweight transparency requirements. High-risk applications — those affecting hiring, credit, law enforcement, access to education, or essential services — face strict requirements: technical documentation, human oversight, accuracy testing, and EU database registration. Non-compliance risks fines of up to thirty-five million euros or seven percent of global annual turnover. If your organization deploys AI in any high-risk category within the EU, compliance is a legal obligation.",

  "slide-61": "Real-world AI failures teach us more about risk than any hypothetical scenario. Amazon's internal hiring tool, trained on a decade of male-dominated tech resumes, systematically downgraded applications from women — they discontinued it in 2018. COMPAS, a recidivism prediction tool used in US courts, was found to flag Black defendants as high risk at twice the rate of comparable white defendants. A New York lawyer submitted a legal brief full of AI-generated case citations — every case was fabricated. These failures share one pattern: the technology performed exactly as designed. The governance around it did not.",

  "slide-62": "Two more documented cases from 2023 and 2024 illustrate the stakes. UnitedHealth's AI-powered prior authorization tool denied nursing home coverage for elderly Medicare patients at a ninety percent error rate — overriding physician recommendations for thousands of people. Air Canada's customer service chatbot created a fabricated bereavement fare policy and promised it to a grieving customer; the company was held legally liable for the AI's invention. Both illustrate the same systemic failure: an AI system deployed in a consequential domain without adequate human oversight or escalation path. The technology did what it was asked to do. The governance did not.",

  "slide-63": "Three complementary frameworks give structure to AI governance today. The NIST AI Risk Management Framework organizes governance around four functions: Govern, Map, Measure, and Manage — familiar to organizations that already use the NIST Cybersecurity Framework. ISO 42001, published in December 2023, is the first certifiable AI management system standard; it aligns with ISO 27001, making it straightforward to extend existing security certifications to cover AI. The EU AI Act is the binding legal layer for EU operations. Together, these three frameworks give organizations a structured, auditable path to responsible AI deployment.",

  "slide-64": "Responsible AI is not a one-time checklist — it is an ongoing discipline. Before deploying any AI system, document what it does, what data it relies on, and what harms it could cause to specific user groups. Test it with diverse profiles — do not assume that because the system works for one demographic it works equally for all. Red-team it deliberately: try to deceive it, push it into failure modes, and test for prompt injection vulnerabilities. Build explainability in from the start — retrofitting it later is expensive and often inadequate. And define clear escalation paths for when the system produces harmful or incorrect output in production. AI you can explain and control is AI you can trust.",

  "slide-65": "Where is AI heading? Some trends are already clear. Context windows keep growing, enabling models to reason over entire codebases and document collections simultaneously. Multimodal models process text, images, audio, and video natively. Agent autonomy expands, with AI systems managing longer, more complex workflows with less human intervention. Inference costs keep falling. The roles most at risk are those that can be fully described as a repeatable, well-specified pattern. The roles that grow are those requiring judgment, empathy, ethical reasoning, and contextual creativity. The best preparation: stay curious, build things, and develop a critical, informed relationship with these tools.",

  "slide-66": "The key takeaways from chapter six. Bias and hallucination are not random failures — they are predictable consequences of how these systems are trained. Every real-world AI failure we examined was preventable with appropriate governance. The EU AI Act creates legal obligations for high-risk applications within Europe, and regulators globally are following its lead. Responsible AI practice — transparency, fairness, human oversight, and clear escalation paths — is not compliance theater. It is what makes AI systems trustworthy enough to deploy at scale.",

  "slide-67": "The key references for chapter six. The EU AI Act official text and implementation timeline are essential reading for anyone deploying AI in Europe. Stochastic Parrots by Bender, Gebru, and colleagues is a landmark critical analysis of large language models and the risks they carry. The ProPublica COMPAS investigation is required reading on algorithmic bias in criminal justice. The NIST AI RMF and ISO 42001 documentation provide the governance frameworks discussed in this chapter.",

  "slide-68": "This table gives you a practical map of where AI delivers measurable value across industries today. Finance uses AI for fraud detection, credit scoring, and document processing — all in production at major institutions. Healthcare applies it to clinical note summarization, radiology image analysis, and drug interaction analysis — with human oversight on all clinical decisions. Legal firms use AI for contract review and case research. Manufacturing applies it to predictive maintenance and quality control. Retail uses it for personalization, demand forecasting, and supply chain optimization. The pattern across all sectors: AI handles the high-volume, pattern-matching work so that humans can focus on judgment and exception handling.",

  /* ── CONCLUSION ──────────────────────────────────────────── */

  "conclusion": "We have reached the conclusion. Six chapters — from the mathematics of transformer attention to the ethics of autonomous agents. Let us take a moment to consolidate the most important ideas before we close.",

  "slide-70": "Here is the summary of all six chapters. Chapter one: LLMs are probabilistic token predictors — they encode statistical patterns, not facts, and scale is what unlocked capabilities. Chapter two: prompt engineering is the craft of communicating precisely — role, context, format, and examples dramatically improve output quality. Chapter three: AI-assisted coding delivers real productivity gains but amplifies whatever skills and habits you bring to it. Chapter four: RAG connects AI to your private data by retrieving documents at query time — no retraining, always current. Chapter five: agents act — they loop through reason-act-observe cycles using tools to complete multi-step tasks autonomously. Chapter six: responsible AI is an engineering discipline, not an afterthought.",

  "slide-71": "Four insights worth holding onto beyond this course. First: LLMs are pattern machines, not fact databases. They predict next tokens, not truth. Verify every output that matters. Second: prompts are programs. Structured prompts consistently outperform vague requests — treat prompt engineering with the same rigor you bring to code. Third: context is everything. What you put in the context window — the role, background, examples, constraints — determines the quality of what comes out. Fourth: AI systems need governance. Every high-stakes deployment should have a clear audit trail, a human override path, and regular evaluation for bias and accuracy.",

  "slide-72": "Here are the resources I recommend for continuing this journey. For foundations: DeepLearning.AI's short courses by Andrew Ng cover transformers, RAG, and agents in a few hours each. Andrej Karpathy's Zero to Hero series builds neural network understanding from scratch in code. The HuggingFace NLP course is the best structured introduction to the transformers library. For staying current: the Latent Space podcast covers frontier AI research in depth, and the HuggingFace Daily Papers page tracks new publications as they land. The most valuable habit is consistent, curated reading — even thirty minutes a week keeps you oriented in this fast-moving field.",

  "slide-73": "We have reached the end of this course. Artificial intelligence is a remarkable tool — and like any powerful tool, its value depends entirely on the intent, judgment, and care of the people who wield it. The models will keep improving. The principles we have covered — grounding outputs, designing for oversight, testing for bias, building in accountability — will remain relevant regardless of what specific systems exist in a year or five years from now. Stay curious. Build things. And if you have questions as you apply these ideas, I am always reachable on LinkedIn. Thank you.",

  /* ── ANNEX ───────────────────────────────────────────────── */

  "annex": "The annex is your reference section. It contains diagrams, cheat sheets, and supporting material for the six chapters. Return to these slides any time you need a quick visual reference or a deeper look at a specific concept.",

  "slide-75": "This visualization shows the self-attention mechanism in action. Each row represents one token querying all the others in the sentence. The brighter a cell, the stronger the attention weight — meaning those two tokens are closely related in the model's view. Notice how the word it attends strongly to cat — the model has learned to resolve pronoun references without any explicit grammar rules. This behavior emerges entirely from training on billions of sentences. Modern transformers run multiple attention heads in parallel, each tracking different linguistic relationships: subject-verb agreement, adjective-noun pairs, and long-range coreference.",

  "slide-76": "The prompt engineering patterns cheat sheet is your practical reference card. The Role pattern assigns an expert persona to improve depth and style. Chain-of-Thought forces step-by-step reasoning before the final answer — essential for math, logic, and multi-step tasks. Few-Shot provides worked examples to demonstrate the exact format you need. Tree of Thought explores multiple reasoning paths simultaneously. Meta-Prompting instructs the model to generate or refine a prompt for a given task. Use this card as a checklist whenever you are designing a new prompt for production use.",

  "slide-77": "This diagram shows the full lifecycle of a single AI request. A user or application sends a prompt. The text is tokenized — converted into integer IDs at roughly three-quarters of a word per token. Those tokens flow through the LLM's attention and feedforward layers, optionally augmented by tool calls or a RAG retrieval step. The model generates token probabilities, samples the next token, and appends it — repeating until done. The output flows back to the application, where it may be parsed, validated, and displayed. The critical step most developers underestimate is human validation: treat AI output as a confident draft, not a final answer, in any high-stakes context.",

  "slide-78": "The modern AI stack has four layers. At the top, the application layer: the chat interface, web app, or API gateway that users interact with. Below that, the orchestration layer: agents, planners, and multi-step reasoning logic implemented with LangGraph, AutoGen, or MCP. Then the inference layer: the language model itself, accessed via a managed API or self-hosted for data sovereignty. At the base, the data layer: vector databases, document stores, and structured data sources that RAG pipelines pull from. Understanding which layer a problem lives in helps you choose the right solution and the right team to build it.",

  "slide-79": "Zooming out to the full ecosystem: at the top, users and interfaces — chat UIs, IDE plugins, mobile apps, and API consumers. Below that, the application layer handles routing, caching, and rate limiting. A reasoning layer where agents decompose tasks and orchestrate tool calls. An inference layer where the language model processes context and generates text. A retrieval layer for RAG — vector search and document stores. And at the base, infrastructure: GPU clusters, cloud providers, monitoring, and compliance tooling. Every layer is a potential integration point, an optimization opportunity, and a governance checkpoint.",

  "slide-80": "AI cost is driven by three variables. Model size: larger models cost ten to one hundred times more per call than smaller ones — GPT-4o mini or Claude Haiku deliver most capability at a fraction of GPT-4o cost. Token count: pricing is per token, and output tokens typically cost three to five times more than input tokens. Call frequency: even modest per-call costs become significant at scale. The practical advice: always benchmark smaller models first on your specific task. You will often find that a model costing ten times less delivers ninety percent of the quality you need.",

  "slide-81": "This slide documents the PlantUML diagram source files included in this repository. Each diagram in the course has a corresponding dot-puml source file in the diagrams folder, along with a dot-link file that points to the rendered version. The diagrams cover the transformer architecture, the full LLM lifecycle, the AI agent ecosystem, RAG pipeline flow, AI-assisted development workflow, and more. If you want to adapt any diagram for your own presentations: fork the repository, edit the dot-puml source, and regenerate. PlantUML gives you version-controlled, text-based diagrams that update cleanly when the content changes.",

  "slide-82": "HuggingFace is to AI models what GitHub is to source code — the central repository where researchers publish weights and developers download them. The Transformers library provides a consistent Python API that works across all major architectures, so switching models is a one-line change. GGUF is a file format that packages model weights and architecture metadata into a single self-contained file, introduced in 2023 as a portable local deployment standard. Quantization reduces numeric precision of model weights — from 32-bit floats down to 4-bit integers — making models roughly four times smaller with minimal quality loss. The Q4-K-M variant is widely considered the best size-quality trade-off for local use.",

  "slide-83": "Running language models locally — on your own hardware, with no cloud dependency — is increasingly practical. Ollama is the easiest starting point: it wraps local models in an OpenAI-compatible REST API on port 11434, so you switch from cloud to local by changing a single URL. LM Studio provides a polished desktop interface with a built-in model browser. LLaMA dot cpp is the underlying inference engine written in C++, supporting CPU and GPU acceleration across platforms. The main constraint is RAM: a seven-billion-parameter model at four-bit quantization needs about four gigabytes — most modern laptops can handle it. Apple silicon Macs are especially well-suited because their unified memory serves both CPU and GPU workloads simultaneously."

};
