/* ═══════════════════════════════════════════════════════════
   SPEAKER NOTES — Español
   Estilo voice-over — hablado directamente al oyente.
   Key = id de la diapositiva  o  "slide-{index}" para slides sin id.
   ═══════════════════════════════════════════════════════════ */
window.NOTES_ES = {

  /* ── PREFACIO ────────────────────────────────────────────── */

  "slide-0": "Bienvenidos a Entendiendo la Inteligencia Artificial — un viaje práctico desde los fundamentos hasta los agentes autónomos. Este curso está diseñado para desarrolladores, arquitectos, gestores de producto y cualquiera que quiera entender de verdad cómo funciona la IA moderna. Cubrimos seis capítulos, cada uno construyendo sobre el anterior, para que salgan con una visión coherente en lugar de buzzwords desconectados. Pueden cambiar el idioma en cualquier momento desde el menú superior. Empecemos.",

  "slide-1": "Antes de comenzar, una breve orientación. Usen las flechas o desplacen para navegar. El botón de menú abre el navegador de capítulos para saltar a cualquier sección. Cada capítulo termina con una diapositiva de referencias para profundizar. Las diapositivas interactivas — las que tienen animaciones o controles deslizantes — son autoexplicativas: simplemente sigan las instrucciones en pantalla. El material está disponible en inglés, italiano, francés y español — cambien el idioma en cualquier momento desde el menú superior.",

  "agenda": "Esto es lo que cubriremos juntos. Seis capítulos, cada uno construyendo sobre el anterior. El capítulo uno establece las bases: qué es realmente la IA, cómo funcionan los transformers y qué significan todos esos parámetros. El capítulo dos trata sobre prompt engineering — el arte de comunicarse con precisión con los modelos de IA. El capítulo tres cubre el coding asistido por IA, desde el autocompletado hasta las herramientas agénticas. El capítulo cuatro explica el Retrieval-Augmented Generation — cómo conectar la IA a sus datos privados. El capítulo cinco explora los agentes de IA autónomos y el Model Context Protocol. El capítulo seis aborda la ética, los sesgos y la gobernanza. El anexo contiene material de referencia al que pueden volver en cualquier momento.",

  /* ── CAPÍTULO 1 ───────────────────────────────────────────── */

  "chapter-1": "El capítulo uno sienta los fundamentos conceptuales para todo lo que sigue. La idea más importante es esta: la inteligencia artificial no es magia — es matemáticas aplicadas a enormes cantidades de datos. Pasaremos de los sistemas deterministas, como un programa if-then clásico que siempre da la misma respuesta, a los probabilísticos, donde el modelo hace su mejor predicción basada en patrones aprendidos de miles de millones de ejemplos. Al final de este capítulo, entenderán cómo funciona una red neuronal transformer, qué significan realmente temperatura y token, y por qué el hardware especializado importa.",

  "slide-4": "La distinción más fundamental en la IA moderna es el cambio del cómputo determinista al probabilístico. El software tradicional es determinista: dar el mismo input siempre produce el mismo output. Los modelos de lenguaje son probabilísticos: a la misma pregunta pueden responder de manera diferente cada vez. No es un defecto — es by design. El modelo no busca una respuesta fija. En cambio, muestrea desde una distribución de probabilidad sobre las posibles palabras siguientes. El parámetro temperatura controla cuán estrecha o amplia es esa distribución. Este cambio — de la corrección garantizada a la verosimilitud optimizada — es el modelo mental sobre el que descansa todo lo demás en el curso.",

  "slide-5": "En realidad hay dos eras en la historia de la IA moderna: todo antes de 2017, y todo después. Antes de 2017, el enfoque dominante eran las redes neuronales recurrentes, que procesaban el texto palabra por palabra y tendían a olvidar el contexto más allá de unas pocas frases. En 2017, un equipo de Google publicó un paper titulado Attention Is All You Need, introduciendo la arquitectura transformer. La innovación clave: cada palabra en una oración puede referirse directamente a cualquier otra palabra simultáneamente, sin importar la distancia. Esa sola intuición desbloqueó un salto de capacidad. En 2020, GPT-3 demostró que escalar esta arquitectura con suficientes datos y cómputo produce un modelo capaz de aprender nuevas tareas de pocos ejemplos — sin entrenamiento adicional.",

  "slide-6": "Tres fuerzas convergieron entre 2017 y 2023 para acelerar la IA más allá de cualquier expectativa previa. Primero, los datos: internet produjo texto a una escala sin precedentes — CommonCrawl, Wikipedia, GitHub y miles de millones de libros digitalizados proporcionaron la materia prima de entrenamiento. Segundo, el cómputo: las GPU evolucionaron de hardware de juegos a motores de cómputo masivamente paralelos capaces de entrenar modelos con cientos de miles de millones de parámetros. Tercero, la propia arquitectura transformer: podía entrenarse mucho más eficientemente que los enfoques anteriores, y su capacidad escalaba de manera predecible con más datos y cómputo. Cuando estas tres fuerzas se combinaron, el progreso que antes requería una década comenzó a ocurrir en meses.",

  "slide-7": "Esta animación muestra lo que realmente sucede cuando un modelo de lenguaje genera texto. Cada paso hacia adelante produce exactamente un token. Noten las barras de probabilidad: el modelo nunca está seguro de qué palabra viene después. Mantiene una distribución completa de posibilidades y muestrea de ella. Cuando la temperatura está por encima de cero, los tokens de baja probabilidad aún tienen posibilidad de ser seleccionados — por eso generar el mismo prompt dos veces puede producir resultados diferentes. Esto también explica por qué los modelos de lenguaje transmiten el output token por token en lugar de devolver una respuesta completa al instante: literalmente calculan el texto un token a la vez.",

  "slide-8": "Sigamos el camino que un texto recorre a través de un transformer. Primero, el texto crudo se divide en tokens — pequeños fragmentos de caracteres. Cada token se convierte en un embedding: un vector de números que codifica su significado en un espacio de alta dimensión. Estos embeddings luego pasan por el mecanismo de auto-atención — el corazón del transformer. Aquí, cada token examina cada otro token y decide cuánto peso darle. Así es como el modelo resuelve que 'él' se refiere a 'gato' varias palabras atrás, sin reglas explícitas. Después de la atención, el resultado pasa por capas feed-forward, y finalmente el modelo produce una distribución de probabilidad sobre el siguiente token posible. Todo este proceso se repite para cada único token generado.",

  "slide-03a": "Esta diapositiva ilustra el pipeline de muestreo completo — el camino de la entrada textual a un único token generado. Los embeddings convierten cada token en un vector de alta dimensión. La auto-atención permite que cada token se refiera a todos los demás. Las capas feed-forward aplican una transformación no lineal aprendida. El softmax convierte los puntajes crudos en una distribución de probabilidad sobre el vocabulario completo. Finalmente, el paso de muestreo extrae el siguiente token de esa distribución, modulado por temperatura y Top-P. Entender este pipeline ayuda a razonar sobre por qué las elecciones de parámetros tienen los efectos que tienen en el output del modelo.",

  "slide-10": "Entender los parámetros clave de generación es esencial para trabajar con cualquier modelo de IA. La temperatura es la más importante: a cero, el modelo siempre elige el token de mayor probabilidad, produciendo output determinista y reproducible. Por encima de cero, los tokens de baja probabilidad tienen oportunidad — aumentando la creatividad pero también la imprevisibilidad. Para generación de código y extracción de datos, mantengan la temperatura baja. Para lluvia de ideas, súbanla. Un token es aproximadamente tres cuartos de una palabra en español — y la unidad en la que se calcula su factura de API. Max token limita la longitud de la respuesta y el costo por llamada. Top-P controla el tamaño del conjunto de candidatos. Cambien estos parámetros de uno en uno, porque interactúan.",

  "slide-11": "Tres limitaciones prácticas son más importantes al construir aplicaciones de IA en el mundo real. Primero, los modelos de lenguaje no tienen memoria persistente: cada conversación comienza desde cero, sin recuerdo de nada dicho antes. Si la continuidad importa, deben inyectar el historial relevante en el prompt ustedes mismos. Segundo, las ventanas de contexto son finitas: cada modelo tiene una longitud máxima de entrada, y el contenido más allá de ese límite simplemente se corta. Tercero, las alucinaciones son inherentes: los modelos pueden producir outputs factualmente incorrectos pero fluidos y confiados sobre temas fuera de su distribución de entrenamiento. Entender estas restricciones de antemano previene una categoría de sorpresas en producción.",

  "slide-12": "¿Por qué los modelos de IA requieren hardware tan especializado? En su núcleo, las capas de redes neuronales son enormes multiplicaciones matriciales — multiplicar arreglos con miles de millones de números simultáneamente. Las GPU se construyeron originalmente para renderizado gráfico, que implica exactamente este tipo de cómputo altamente paralelo. Una moderna GPU H100 tiene ochenta gigabytes de memoria de alto ancho de banda y procesa miles de operaciones en paralelo. Los proveedores de nube como Azure, AWS y Google Cloud exponen estas capacidades mediante APIs, así que pagan por token en lugar de comprar hardware. La curva de costos es dramática: el costo de inferencia baja aproximadamente diez veces al año — por eso ejecutar modelos capaces localmente ya es práctico hoy.",

  "slide-13": "Una de las propiedades más sorprendentes de los modelos de lenguaje grandes modernos es su generalidad. Cada tarea en esta nube de palabras — análisis de sentimiento, traducción, resumen, generación de código, reconocimiento de entidades nombradas, clasificación, respuesta a preguntas y docenas más — puede ser manejada por un único modelo de fundación. Antes de 2020, cada una de estas tareas requería un modelo dedicado, especialmente entrenado. Hoy, un solo modelo las maneja todas. La implicación es profunda: el costo marginal de probar un nuevo caso de uso de IA es ahora esencialmente cero, porque reutilizan el mismo modelo.",

  "slide-14": "El panorama de modelos de IA cambia aproximadamente cada tres a seis meses, así que traten esta tabla como una instantánea. Dimensiones clave al elegir un modelo: capacidad para su tarea específica, tamaño de ventana de contexto, costo por token, si es open-weight o propietario, y dónde corre la inferencia para cumplimiento. Gemini 2.0 lidera en ventana de contexto con más de un millón de tokens. Llama 3 y Mistral son open-weight y pueden ser auto-hospedados — importante para la soberanía de datos. GPT-4o mini ofrece la mayor parte de la calidad de GPT-4o completo a una fracción del costo. Su elección depende de tarea, presupuesto, latencia y requisitos de cumplimiento.",

  "slide-15": "Cada modelo de lenguaje tiene modos de fallo predecibles que deben conocer antes de desplegarlo. La alucinación es la más peligrosa: el modelo genera texto que suena fluido y confiado pero es factualmente incorrecto — sin señal visible de incertidumbre. El knowledge cutoff significa que el modelo no sabe nada de eventos después del final de sus datos de entrenamiento. El razonamiento matemático no es confiable — los modelos frecuentemente fallan aritmética de maneras que parecen sorprendentes dado sus otras capacidades. Y el sesgo: dado que los modelos aprenden patrones de texto generado por humanos, reflejan los prejuicios en ese texto. Ninguno de estos es un bug que se corregirá — son propiedades fundamentales de la arquitectura actual. Diseñen su sistema en consecuencia.",

  "ai-system-architecture": "Este diagrama muestra la arquitectura completa por capas de un sistema de IA moderno. En la cima están los actores: el usuario final que envía consultas, el desarrollador que construye y monitorea el sistema, y cualquier servicio o API externo. Las solicitudes descienden a través de una capa de aplicación que maneja autenticación, limitación de tasa y contexto de la conversación. Debajo está la capa de integración de IA: construcción del prompt, recuperación opcional desde una base de datos vectorial para RAG, y la llamada al modelo de lenguaje. La respuesta sube de vuelta por las mismas capas. Cada capa es una oportunidad para agregar controles de seguridad, registro y control — por eso los sistemas de IA bien diseñados se construyen en capas en lugar de como conexión directa usuario-modelo.",

  "slide-17": "Consolidemos las ideas clave del capítulo uno. Los LLM son probabilísticos, no deterministas: la misma pregunta puede producir respuestas diferentes, y eso es by design. Los transformers hicieron esto posible procesando secuencias enteras simultáneamente mediante auto-atención. La temperatura y los límites de tokens son los controles principales que usarán en cada integración. Las ventanas de contexto definen la información máxima sobre la que un modelo puede razonar en una única llamada. Y todas las capacidades — traducción, código, resumen, razonamiento — emergen de un único objetivo de pre-entrenamiento: predecir el siguiente token. Esta es la fundación sobre la que descansa todo lo demás en el curso.",

  "slide-18": "Cerremos el capítulo uno con las referencias fundamentales. El paper que lo inició todo es Attention Is All You Need de Vaswani y colegas, publicado por Google en 2017 — introdujo la arquitectura transformer que subyace a cada modelo de lenguaje moderno. El paper GPT-3 de OpenAI en 2020 mostró que escalar los transformers desbloquea el few-shot learning — la capacidad de realizar nuevas tareas desde pocos ejemplos en el prompt. Para una excelente explicación visual de cómo funciona la atención, The Illustrated Transformer de Jay Alammar es altamente recomendado y disponible gratuitamente en línea.",

  /* ── CAPÍTULO 2 ───────────────────────────────────────────── */

  "chapter-2": "El capítulo dos es donde la teoría se vuelve práctica. El prompt engineering es la disciplina de comunicarse con precisión con los modelos de IA. Cómo formulan una solicitud tiene un efecto enorme en la calidad de la respuesta — y hay patrones repetibles que mejoran los resultados de manera confiable. Diseccionaremos la anatomía de un buen prompt, aprenderemos seis patrones probados desde zero-shot hasta chain-of-thought, y veremos reescrituras reales antes-después. Estas habilidades aplican a cualquier modelo de IA, no sólo los disponibles hoy.",

  "slide-20": "Un prompt bien estructurado tiene cuatro capas, y entender cada una desbloquea resultados significativamente mejores. En la cima está el system prompt: es donde definen el rol, las restricciones y la persona del modelo. Una simple instrucción como eres un senior data engineer especializado en Python cambia de manera medible el estilo y la profundidad de la respuesta. Luego el contexto: la información de fondo relevante que el modelo necesita. Luego viene el mensaje del usuario — la tarea o pregunta real. Finalmente, las instrucciones sobre el formato de salida: díganle explícitamente al modelo si quieren JSON, una lista numerada, un párrafo o una tabla. El modelo no conoce sus requisitos downstream a menos que los especifiquen.",

  "slide-21": "Tres patrones fundamentales de prompting cubren la gran mayoría de los casos de uso. Zero-shot: describan la tarea directamente, sin ejemplos — los modelos modernos manejan la mayoría de las tareas de esta manera. Few-shot: proporcionen de dos a cinco ejemplos entrada-salida que demuestren el formato y estilo que quieren — particularmente efectivo para output estructurado consistente. Chain-of-thought: pidan al modelo que razone paso a paso antes de dar la respuesta final — esto mejora drásticamente la precisión en tareas matemáticas, lógicas y multi-paso. Estos patrones se combinan naturalmente: un system prompt más ejemplos few-shot más chain-of-thought es una de las arquitecturas de prompt más confiables en producción.",

  "slide-22": "Más allá de los básicos, varios patrones avanzados extienden lo que el prompting puede lograr. Los system prompts definen la persona, las reglas y las barreras del modelo — los usuarios nunca los ven, pero moldean cada respuesta. El role playing asigna una persona experta específica para mejorar la profundidad del output. El Retrieval-Augmented Generation inyecta documentos relevantes recuperados de una base de conocimientos en el prompt antes de la generación — cubierto en detalle en el capítulo cuatro. El uso de herramientas permite al modelo solicitar la ejecución de funciones externas — la base de los agentes en el capítulo cinco. Estas técnicas son particularmente valiosas al construir sistemas de IA en producción.",

  "slide-23": "El error más común al trabajar con IA es escribir prompts vagos. Comparen resume este documento con resume este documento en exactamente tres puntos para un ejecutivo no técnico, usando español sencillo, sin jerga, máximo quince palabras por punto. El segundo produce de manera consistente output mejor y más utilizable. Pautas clave: siempre asignen un rol en el system prompt; expresen las restricciones positivamente — digan qué quieren, no qué no quieren; sean explícitos sobre longitud y formato; e incluyan un ejemplo cuando el estilo de salida deseado no es obvio. Prueben cualquier prompt en al menos diez inputs distintos antes de lanzarlo a producción.",

  "slide-24": "El prompt makeover es uno de los medios más efectivos para construir intuición. Tomen un prompt mediocre y aplíquenle una reescritura estructurada: agreguen un rol claro, especifiquen el formato de salida, agreguen restricciones, incluyan un ejemplo. El patrón es notablemente consistente: el prompt ingenuo de antes produce output genérico, a menudo inutilizable; el prompt ingenierizado de después produce algo específico, estructurado y listo para usar. La brecha entre ellos no es el modelo — es la calidad de la instrucción. Un modelo mental útil: piensen en un prompt como un programa que están escribiendo para un intérprete muy capaz pero extremadamente literal.",

  "slide-25": "Veamos cómo los mismos principios de prompting aplican en diferentes roles profesionales. Un gerente podría pedirle a la IA que resuma un informe de veinte páginas en cinco puntos para una audiencia no técnica. Un desarrollador podría pedirle que escriba un test unitario para una función específica con requisitos de cobertura precisos. Un analista de datos podría solicitar un script Python que ingiere un CSV, calcula estadísticas de resumen y señala los valores atípicos. El patrón es el mismo en cada caso: indicar el rol, proporcionar contexto, especificar el formato. El valor no está en la IA haciendo su pensamiento — sino en encargarse del trabajo mecánico de producción para que puedan enfocarse en el juicio.",

  "slide-26": "Este playground interactivo les permite explorar cómo los parámetros de generación afectan el output en tiempo real. Pongan la temperatura a cero y generen el mismo prompt dos veces — obtendrán resultados idénticos cada vez. Aumenten gradualmente la temperatura y observen cómo el output se diversifica. Top-P controla el conjunto de candidatos: un valor bajo confina al modelo a los tokens más probables; un valor alto abre territorios más creativos. Estos no son ajustes abstractos — controlan directamente el balance coherencia-creatividad en su aplicación. Las aplicaciones orientadas al cliente que necesitan respuestas confiables se benefician de temperatura baja. Las herramientas creativas se benefician de temperatura alta.",

  "slide-27": "Ahora es su turno de practicar. Tomen una tarea real — escribir una descripción de trabajo, analizar un dataset, redactar una propuesta técnica — y escriban un prompt inicial. Ejecútenlo, vean qué obtienen, luego mejórenlo sistemáticamente: agreguen un rol, agreguen instrucciones de formato, agreguen un ejemplo. Comparen el output de cada iteración con el anterior. Descubrirán que cada refinamiento hace una diferencia significativa. El objetivo no es la perfección en el primer intento — es construir el músculo iterativo de generar, evaluar críticamente, refinar y repetir. Este ciclo es la habilidad fundamental del prompt engineering efectivo.",

  "slide-28": "Los puntos clave del capítulo dos. Cada prompt efectivo tiene cuatro partes: rol, contexto, tarea y formato. Omitir una y la calidad sufre. Los patrones de prompting — zero-shot, few-shot, chain-of-thought — son combinables: úsenlos juntos para requisitos complejos. Las técnicas avanzadas como system prompts y output estructurado extienden el prompting a territorio arquitectónico. Y recuerden: un prompt es un programa. Tratenlo como código — versionenlo, pruébenlo en inputs diversos y refinenlo iterativamente.",

  "slide-29": "Las referencias clave del capítulo dos. Anthropic y OpenAI publican ambas guías detalladas de prompt engineering que reflejan las mejores prácticas más recientes para sus modelos. El paper Chain-of-Thought Prompting de Wei y colegas estableció por qué razonar paso a paso mejora drásticamente el rendimiento en tareas complejas. El sitio promptingguide.ai y el curso Learn Prompting son excelentes recursos estructurados para construir estas habilidades desde cero.",

  /* ── CAPÍTULO 3 ───────────────────────────────────────────── */

  "chapter-3": "El capítulo tres trata sobre qué sucede cuando la IA se convierte en su compañero de coding. Cubriremos todo el espectro: desde el simple autocompletado, a los asistentes de escritura de código conversacionales, a las herramientas completamente agénticas que entienden todo el codebase y realizan cambios autónomos en múltiples archivos. Hay un real y medible aumento de productividad — respaldado por estudios controlados. También hay riesgos reales cuando estas herramientas se usan sin entender lo que producen. Examinaremos ambos lados honestamente.",

  "slide-31": "En febrero de 2025, el investigador de IA Andrej Karpathy acuñó la frase vibe coding para describir una nueva forma de escribir software. Describen lo que quieren en lenguaje natural, la IA genera el código, lo ejecutan, observan qué se rompe y describen la corrección. No necesariamente leen cada línea antes de lanzarlo a producción. Los desarrolladores que adoptan este ciclo de iteración rápida reportan trabajar de tres a cinco veces más rápido en tareas bien definidas. Pero hay una advertencia crítica: el vibe coding amplifica sus habilidades existentes — no reemplaza la comprensión. Si no pueden evaluar si el código es correcto y seguro, no detectarán los errores que la IA comete con confianza.",

  "slide-32": "El flujo de trabajo de desarrollo asistido por IA sigue un ciclo claro: describan la tarea con precisión, generen código, revisen críticamente, ejecútenlo, identifiquen qué está mal y refinen. La palabra a enfatizar es críticamente. Las herramientas de IA sobresalen en generación de boilerplate, scaffolding, tests unitarios y transformaciones bien especificadas. Tienen dificultades con lógica de negocio implícita, código crítico para la seguridad y cualquier cosa que requiera conocimiento contextual profundo de su codebase. Herramientas como Cursor y Windsurf reducen la fricción con vistas diff inline y edición multi-archivo. Los mejores practicantes han reducido este ciclo de iteración a menos de dos minutos por modificación.",

  "slide-33": "El panorama de herramientas de coding de IA tiene tres niveles. Asistentes integrados en el IDE: GitHub Copilot con la adopción enterprise más amplia; Cursor, popular entre las startups por su modo compositor multi-archivo; y Windsurf, que sobresale en la consciencia de codebases grandes. Los agentes completamente autónomos como Devin pueden recibir una tarea, navegar documentación, escribir código, ejecutar tests y hacer commits con mínima interacción humana. El factor diferenciador al evaluar herramientas es el contexto del codebase: qué parte de su código existente puede mantener la herramienta en contexto simultáneamente. Más contexto significa sugerencias más precisas y contextualmente apropiadas.",

  "slide-34": "Las herramientas de coding de IA funcionan mejor en problemas bien definidos y autónomos: APIs CRUD, tests unitarios, scripts de transformación de datos, archivos de configuración, expresiones regulares, layouts CSS y documentación. Donde consistentemente tienen dificultades: lógica de negocio compleja con restricciones no declaradas, código crítico para la seguridad donde un error sutil es explotable, y codebases legacy donde años de decisiones viven en convenciones no documentadas. La regla de oro: más clara sea su especificación, mejor es el output. La IA amplifica la calidad de su pensamiento — no lo reemplaza.",

  "slide-35": "Las ganancias de productividad de las herramientas de coding de IA son reales y medibles. Un estudio controlado aleatorio de GitHub y Microsoft en 2022 encontró que los desarrolladores usando Copilot completaban una tarea de servidor HTTP el cincuenta y cinco por ciento más rápido. El informe GitHub Octoverse 2024 encontró que Copilot genera en promedio el cuarenta y seis por ciento del código en los archivos donde está habilitado. La encuesta Developer Survey de Stack Overflow mostró que el setenta y seis por ciento de los desarrolladores ya usa o planea adoptar herramientas de coding de IA. Para los desarrolladores senior, el rol está cambiando: de escribir funciones individuales hacia decisiones arquitectónicas, revisión rigurosa del output de IA, e ingeniería de las especificaciones precisas que dirigen a la IA efectivamente.",

  "slide-36": "Este ejercicio trata sobre el proceso, no solo el resultado. Tomen cualquier archivo CSV y usen una herramienta de coding de IA para escribir un script de análisis: estadísticas de resumen, detección de valores atípicos y una visualización simple. Presten atención a donde la IA hace suposiciones sin preguntar — tipos de columnas, manejo de valores faltantes, formato de salida. Noten qué falla la primera vez. Practiquen el ciclo: generen, revisen críticamente, prueben y refinen. Al final tendrán un script funcional y una intuición concreta de exactamente dónde la asistencia de IA agrega valor y dónde su juicio sigue siendo indispensable.",

  "slide-37": "Los puntos clave del capítulo tres. Las herramientas de coding de IA ofrecen ganancias de productividad reales — del treinta y cinco al cincuenta y cinco por ciento en tareas bien definidas, respaldadas por estudios controlados. Pero la amplificación funciona en ambas direcciones: las buenas prácticas se escalan hacia arriba, y las malas también. Siempre revisen críticamente el código generado por IA — no solo por corrección sino por seguridad, casos límite y mantenibilidad. El rol emergente no es prompter sino ingeniero habilitado por IA: alguien que especifica la intención con precisión, evalúa el output de IA rigurosamente y lo integra de manera segura en un sistema más grande.",

  "slide-38": "Las referencias del capítulo tres. El post original de Karpathy sobre vibe-coding define la filosofía de esta nueva forma de desarrollo. El estudio Kalliamvakou es la medida académica más rigurosa del impacto de Copilot en la productividad. El informe GitHub Octoverse 2024 proporciona estadísticas de adopción a escala de la industria. La documentación de Cursor vale la pena explorar como ejemplo concreto de cómo se ve un IDE nativo de IA más allá de un plugin tradicional.",

  /* ── CAPÍTULO 4 ───────────────────────────────────────────── */

  "chapter-4": "El capítulo cuatro aborda una de las limitaciones más importantes de los modelos de lenguaje en producción: no conocen sus datos privados, y su entrenamiento tiene un corte de conocimiento fijo. El Retrieval-Augmented Generation — RAG — es la solución, y es la arquitectura de IA más ampliamente desplegada en software empresarial hoy. Entender el RAG es lo que separa a quienes usan IA de quienes construyen sobre ella. Cubriremos el pipeline completo: indexación de documentos, embeddings, búsqueda vectorial, recuperación y generación basada en fuentes.",

  "slide-40": "¿Por qué no simplemente hacer fine-tuning del modelo en sus documentos internos? Tres razones: el fine-tuning es costoso, tarda días o semanas, y — lo más importante — los hechos cambian. Cuando un documento se actualiza, tendrían que re-entrenar el modelo completo. El RAG adopta un enfoque fundamentalmente diferente: en lugar de incorporar el conocimiento en los pesos del modelo, recupera información relevante en el momento de la consulta y la inyecta directamente en el prompt. Piénsenlo como darle al modelo un motor de búsqueda y derechos de copiar-pegar antes de que responda — lee los documentos recuperados, luego responde. Esto hace al RAG más barato, más rápido de actualizar, más verificable y más controlable que el fine-tuning para cualquier información que cambie con el tiempo.",

  "slide-41": "El pipeline RAG tiene dos fases distintas. La primera es la indexación, que ocurre una vez o periódicamente: los documentos se dividen en chunks, cada chunk se convierte en un vector embedding, y esos vectores se almacenan en una base de datos vectorial. La segunda es la consulta, que ocurre en cada solicitud del usuario: la pregunta se embede usando el mismo modelo, la base de datos vectorial encuentra los chunks más cercanos, esos chunks se inyectan en el prompt como contexto, y el modelo de lenguaje genera una respuesta basada en fuentes. La calidad de cada paso — estrategia de chunking, modelo de embedding, profundidad de recuperación — determina la calidad de la respuesta final.",

  "slide-42": "Aquí está la intuición detrás de los embeddings. Imaginen colocar cada pieza de texto en un espacio de alta dimensión donde los textos semánticamente similares aterrizan cerca. 'Los ingresos cayeron el último trimestre' y 'las ventas disminuyeron en el Q3' estarían muy cerca, aunque no comparten palabras. 'Ingresos' y 'cachorro' estarían lejos. Una base de datos vectorial es un índice optimizado para encontrar los vecinos más cercanos en ese espacio a alta velocidad, usando algoritmos como HNSW que evitan comparar cada par de vectores. Para la mayoría de las organizaciones, pgvector — una extensión de PostgreSQL — es el punto de partida pragmático. Pinecone y Weaviate son bases de datos vectoriales dedicadas adecuadas para despliegues a gran escala.",

  "slide-43": "Cómo dividen los documentos en chunks tiene mayor impacto en la calidad del RAG que casi cualquier otra decisión — incluido qué modelo de lenguaje usan. La división recursiva por caracteres intenta dividir en límites de párrafo, oración, luego palabra — un buen default. El chunking semántico usa la similitud de embedding entre oraciones adyacentes para encontrar límites naturales de tema — más costoso pero preserva mejor el significado. La indexación jerárquica almacena tanto chunks padre como hijo: la recuperación usa chunks hijo para precisión, pero proporciona el chunk padre al modelo para contexto más completo. Para la mayoría del contenido, un tamaño de chunk de quinientos a mil tokens con un solapamiento del diez al veinte por ciento es un punto de partida confiable.",

  "slide-44": "Este ejemplo antes-después hace concreto lo que está en juego con el chunking. La consulta es: ¿cuál es la política de licencia parental para padres adoptivos? Si el manual de RR.HH. se corta mecánicamente cada quinientos caracteres, el texto de política relevante podría dividirse entre dos chunks — ninguno se clasifica alto en una búsqueda vectorial porque cada chunk solo está incompleto. Con el chunking semántico — dividiendo en límites naturales de tema — toda la sección sobre licencia parental permanece junta, se recupera claramente y produce una respuesta correcta y completa. El tamaño de chunk y el solapamiento no son detalles de configuración. Son decisiones arquitectónicas que determinan directamente si su sistema RAG funciona.",

  "slide-45": "El RAG es la arquitectura de IA número uno en producción en 2025, resolviendo tres problemas críticos simultáneamente. Ancla las respuestas del modelo en documentos fuente verificables, transformando un modelo caja negra en un asistente transparente que puede citar sus fuentes. Elimina los problemas de knowledge cutoff — actualicen su índice documental y el conocimiento efectivo del modelo se actualiza inmediatamente, sin re-entrenamiento. Y hace la IA auditable: en sectores regulados, rastrear cada afirmación a un documento fuente es frecuentemente un requisito de cumplimiento. Las aplicaciones comunes incluyen bases de conocimiento internas, Q&A sobre documentación técnica, investigación legal y de cumplimiento, y soporte al cliente con acceso a información live de productos.",

  "slide-46": "Para este ejercicio arquitectónico, diseñen un sistema RAG para un caso de uso real que les interese. Trabajen en cada decisión: ¿cuáles son sus documentos fuente, y con qué frecuencia cambian? ¿Qué tamaño de chunk y solapamiento tiene sentido para este tipo de contenido? ¿Qué metadatos deben acompañar cada chunk para habilitar filtrado por fecha, autor o nivel de acceso? ¿Cómo manejan los documentos sensibles que no deben ser ampliamente recuperables? ¿Y cómo instruyen al modelo para decir no lo sé cuando el contexto recuperado no responde la pregunta — en lugar de alucinar? Tomar estas decisiones por adelantado ahorra un tiempo de depuración enorme después.",

  "slide-47": "Los puntos clave del capítulo cuatro. El RAG resuelve el problema del conocimiento congelado recuperando documentos relevantes en el momento de la consulta — no se necesita re-entrenamiento, siempre actualizado. La estrategia de chunking y la elección del modelo de embedding tienen más impacto en la calidad que la elección del modelo de lenguaje. Siempre incluyan un filtro en los metadatos y una instrucción explícita para que el modelo reconozca cuando falta información relevante. Y el RAG hace la IA auditable: cada respuesta puede rastrearse a un documento fuente, lo que frecuentemente es un requisito de cumplimiento en sectores regulados.",

  "slide-48": "Las referencias clave del capítulo cuatro. El paper RAG original de Lewis y colegas, publicado en 2020, mostró resultados de vanguardia en question answering de dominio abierto. LlamaIndex y LangChain son los dos principales frameworks open-source para construir pipelines RAG en producción — ambos tienen excelente documentación. El survey de 2023 de Gao y colegas proporciona un mapa completo de las variantes RAG ingenuas, avanzadas y modulares, con evaluación clara de cuándo cada enfoque es más efectivo.",

  /* ── CAPÍTULO 5 ───────────────────────────────────────────── */

  "chapter-5": "El capítulo cinco pasa del modelo al agente. Hasta ahora hemos hablado de modelos que responden: ustedes preguntan, ellos responden. Un agente de IA es diferente — actúa. Puede navegar la web, llamar APIs, escribir y ejecutar código, consultar bases de datos y enviar correos — de manera autónoma, encadenando múltiples decisiones sin un humano en el loop para cada paso. Este paso de la respuesta a la acción es uno de los desarrollos más consecuentes en IA en 2025. Cubriremos el ciclo de razonamiento ReAct, los cuatro patrones agénticos, el Model Context Protocol y la orquestación multi-agente.",

  "slide-50": "Un agente de IA difiere de un chatbot en una manera fundamental: actúa. Donde un chatbot devuelve texto, un agente emite instrucciones que hacen que cosas sucedan en el mundo real. La estructura básica es un ciclo llamado ReAct — abreviatura de Reason and Act. El modelo observa el estado actual, razona sobre qué hacer a continuación, toma una acción — llamando una función, consultando una base de datos, ejecutando código — observa el resultado, y razona de nuevo. Este ciclo continúa hasta que la tarea está completa. Los agentes pueden correr por minutos u horas, tomando docenas de decisiones autónomas. Ese poder viene con riesgo: límites de alcance claros y puntos de control de supervisión humana son esenciales.",

  "slide-51": "Andrew Ng identificó cuatro patrones agénticos que hacen los flujos de trabajo de IA dramáticamente más capaces. Reflection: el modelo genera output, luego critica y revisa su propio trabajo — esto solo puede llevar la precisión de generación de código de alrededor del cincuenta por ciento a más del noventa. Tool use: el modelo llama funciones externas para interactuar con sistemas reales. Planning: el modelo descompone una tarea compleja en subtareas antes de ejecutar. Colaboración multi-agente: múltiples modelos especializados trabajan como un equipo. El insight clave: los flujos de trabajo agénticos iterativos superan consistentemente un único prompt one-shot, a veces incluso usando un modelo base menos capaz.",

  "slide-52": "El patrón ReAct, introducido por Yao y colegas en 2022, funciona haciendo explícita la cadena de pensamiento del modelo en el prompt. Antes de cada acción, el modelo escribe un pensamiento — su razonamiento sobre la situación actual. Luego especifica la acción. Luego observa el resultado. Luego escribe otro pensamiento. Este entrelazado de razonamiento y acción es lo que hace a los agentes confiables en tareas complejas, porque el modelo verbaliza su plan antes de ejecutarlo. También hace el comportamiento del agente inspeccionable: pueden leer el rastro de pensamientos y entender exactamente por qué se tomó cada decisión. Los agentes bien ingenieriados incluyen lógica de reintento y estrategias de respaldo para cuando una llamada de herramienta falla.",

  "slide-53": "La llamada de funciones y el uso de herramientas son cómo los agentes interactúan con el mundo. En lugar de devolver texto simple, el modelo emite un payload JSON estructurado especificando la función que quiere llamar y los argumentos a pasar. Su código de aplicación recibe este JSON, ejecuta la función real — llamando una API REST, consultando una base de datos, ejecutando un cálculo — y devuelve el resultado al modelo. Esta arquitectura es crucial para la seguridad: el modelo solicita una acción, pero su código decide si ejecutarla. Pueden agregar validación, limitación de tasa y puertas de aprobación humana para acciones irreversibles. El agente pide; ustedes controlan qué sucede realmente.",

  "slide-54": "El Model Context Protocol, o MCP, fue lanzado por Anthropic en noviembre de 2024 y rápidamente se convirtió en la interfaz estándar para conectar aplicaciones de IA a herramientas externas. Antes de MCP, cada producto de IA tenía que construir integraciones personalizadas para cada herramienta que necesitaba — multiplicando la carga de mantenimiento en todo el ecosistema. MCP define un protocolo universal: escriban un servidor MCP para su herramienta una vez, y cualquier cliente compatible con MCP — Cursor, VS Code Copilot, Claude, Windsurf — puede usarlo inmediatamente sin trabajo adicional. Es análogo al Language Server Protocol, que resolvió el mismo problema en el mundo de los IDE: escriban un servidor de lenguaje una vez y cada editor compatible obtiene soporte gratuitamente.",

  "slide-55": "Cuando un solo agente no es suficiente, los frameworks multi-agente les permiten orquestar varios agentes especializados trabajando juntos. LangGraph del equipo LangChain es la opción más lista para producción: los obliga a modelar su agente como una máquina de estados explícita con estados y transiciones definidos, haciendo el sistema inspeccionable, reanudable y seguro de pausar para revisión humana. AutoGen de Microsoft usa un modelo de chat grupal donde los agentes se comunican a través de un hilo de mensajes compartido — ideal para flujos de trabajo de debate y refinamiento. El consejo práctico: comiencen con el agente único más simple posible y agreguen agentes solo cuando un solo agente falla de manera demostrable. La complejidad en los sistemas multi-agente crece rápido, y los modos de fallo también.",

  "slide-56": "Los puntos clave del capítulo cinco. La diferencia entre un LLM y un agente es la acción: un agente puede llamar herramientas, ejecutar código y tomar decisiones en múltiples pasos. El ciclo ReAct — razona, actúa, observa, repite — es el patrón que hace a los agentes confiables e inspeccionables. El uso de herramientas es arquitectónicamente crítico: el modelo solicita una acción, pero su aplicación decide qué se ejecuta realmente. MCP está rápidamente convirtiéndose en la interfaz universal para integraciones de herramientas de IA. Y los sistemas multi-agente agregan complejidad rápidamente — comiencen con el diseño más simple y agreguen agentes solo cuando un solo agente falla de manera demostrable.",

  "slide-57": "Las referencias clave del capítulo cinco. El paper ReAct de Yao y colegas es el trabajo fundacional sobre la combinación de razonamiento y acción en agentes de IA. La documentación del Model Context Protocol de Anthropic describe el estándar abierto ahora ampliamente adoptado en herramientas de desarrollo de IA. Los cursos cortos de DeepLearning.AI sobre agentes y uso de herramientas son la mejor introducción práctica — varios son gratuitos. La documentación y ejemplos de LangGraph son excelentes para quienes construyen sistemas agénticos listos para producción.",

  /* ── CAPÍTULO 6 ───────────────────────────────────────────── */

  "chapter-6": "El capítulo seis plantea la pregunta más difícil: solo porque la IA puede hacer algo, ¿debería hacerlo — y bajo qué condiciones? Después de cinco capítulos sobre capacidades, este capítulo trata sobre responsabilidad. Examinaremos casos documentados donde los sistemas de IA causaron daños reales: herramientas de contratación sesgadas, puntuaciones de riesgo de reincidencia defectuosas, citas legales fabricadas y fraudes deepfake. Cubriremos el EU AI Act, la primera ley vinculante del mundo sobre IA. Y discutiremos frameworks de gobernanza que pueden aplicar a sus despliegues. La IA responsable no es un obstáculo a la innovación — es lo que hace la innovación digna de confianza.",

  "slide-59": "Las dos limitaciones más importantes de los modelos de IA actuales son el sesgo y la alucinación. Sesgo: los modelos aprenden patrones de datos generados por humanos — incluidos los prejuicios humanos. Una herramienta de contratación entrenada en datos históricos puede aprender a preferir ciertos grupos demográficos no porque haya sido programada para hacerlo, sino porque ese patrón existía en el conjunto de entrenamiento. Alucinación: los modelos generan texto que suena confiado y fluido pero es factualmente incorrecto. Esto ocurre porque el modelo predice tokens estadísticamente plausibles, no recupera hechos verificados. Ambos son fallos predecibles y sistemáticos. Diseñen sus sistemas de IA con estos modos de fallo en mente desde el primer día.",

  "slide-60": "El EU AI Act de la Unión Europea es la primera ley de IA completa y vinculante del mundo, en vigor desde agosto de 2024. Usa un enfoque por niveles basado en riesgo. La mayoría de las aplicaciones caen en categorías de riesgo mínimo o limitado con requisitos ligeros de transparencia. Las aplicaciones de alto riesgo — las que afectan contratación, crédito, aplicación de la ley, acceso a educación o servicios esenciales — enfrentan requisitos estrictos: documentación técnica, supervisión humana, pruebas de precisión y registro en la base de datos de la UE. El incumplimiento arriesga multas de hasta treinta y cinco millones de euros o el siete por ciento de la facturación anual global. Si su organización despliega IA en cualquier categoría de alto riesgo en la UE, el cumplimiento es una obligación legal.",

  "slide-61": "Los fallos reales de IA nos enseñan más sobre el riesgo que cualquier escenario hipotético. La herramienta interna de contratación de Amazon, entrenada en una década de currículums tecnológicos dominados por hombres, sistemáticamente calificó más bajo las solicitudes de mujeres — fue discontinuada en 2018. COMPAS, una herramienta de predicción de reincidencia usada en tribunales estadounidenses, fue encontrada marcando a acusados negros como de alto riesgo al doble de la tasa que a acusados blancos comparables. Un abogado de Nueva York presentó un escrito legal lleno de citas de casos generadas por IA — cada caso era fabricado. Estos fallos comparten un patrón: la tecnología funcionó exactamente como fue diseñada. La gobernanza alrededor de ella no lo hizo.",

  "slide-62": "Dos casos más documentados de 2023 y 2024 ilustran lo que está en juego. La herramienta de pre-autorización de IA de UnitedHealth negó cobertura de enfermería para pacientes Medicare ancianos con una tasa de error del noventa por ciento — anulando las recomendaciones de médicos para miles de personas. El chatbot de servicio al cliente de Air Canada creó una política de tarifa de duelo fabricada y se la prometió a un cliente de duelo; la compañía fue considerada legalmente responsable de la invención de la IA. Ambos ilustran el mismo fallo sistémico: un sistema de IA desplegado en un dominio consecuente sin supervisión humana adecuada ni ruta de escalación.",

  "slide-63": "Tres frameworks complementarios dan estructura a la gobernanza de IA hoy. El NIST AI Risk Management Framework organiza la gobernanza alrededor de cuatro funciones: Gobernar, Mapear, Medir y Gestionar — familiar para organizaciones que ya usan el NIST Cybersecurity Framework. ISO 42001, publicado en diciembre de 2023, es el primer estándar certificable de sistema de gestión de IA; se alinea con ISO 27001, haciendo simple extender las certificaciones de seguridad existentes para cubrir la IA. El EU AI Act es la capa legal vinculante para operaciones en la UE. Juntos, estos tres frameworks dan a las organizaciones un camino estructurado y auditable hacia el despliegue responsable de IA.",

  "slide-64": "La IA responsable no es una lista de verificación única — es una disciplina continua. Antes de desplegar cualquier sistema de IA, documenten qué hace, en qué datos se basa, y qué daños podría causar a grupos específicos de usuarios. Pruébenlo con perfiles diversos — no asuman que porque el sistema funciona para un grupo demográfico funciona igual para todos. Hagan red-teaming deliberadamente: intenten engañarlo, empújenlo hacia modos de fallo, y prueben vulnerabilidades de inyección de prompt. Construyan la explicabilidad desde el principio — retrofitarla es costoso y frecuentemente inadecuado. Y definan rutas de escalación claras para cuando el sistema produzca outputs dañinos o incorrectos en producción. La IA que pueden explicar y controlar es la IA en la que pueden confiar.",

  "slide-65": "¿A dónde va la IA? Algunas tendencias ya son claras. Las ventanas de contexto continúan creciendo, habilitando a los modelos para razonar sobre codebases completos y colecciones de documentos simultáneamente. Los modelos multimodales procesan texto, imágenes, audio y video nativamente. La autonomía de los agentes se expande, con sistemas de IA gestionando flujos de trabajo más largos y complejos con menos intervención humana. Los costos de inferencia continúan bajando. Los roles más en riesgo son los que pueden describirse completamente como un patrón repetible y bien especificado. Los roles que crecen son los que requieren juicio, empatía, razonamiento ético y creatividad contextual. La mejor preparación: permanezcan curiosos, construyan cosas, y desarrollen una relación crítica e informada con estas herramientas.",

  "slide-66": "Los puntos clave del capítulo seis. El sesgo y la alucinación no son fallos aleatorios — son consecuencias predecibles de cómo se entrenan estos sistemas. Cada fallo de IA del mundo real que examinamos era evitable con gobernanza apropiada. El EU AI Act crea obligaciones legales para aplicaciones de alto riesgo en Europa, y los reguladores en todo el mundo siguen su ejemplo. La práctica de IA responsable — transparencia, equidad, supervisión humana y rutas de escalación claras — no es teatro de cumplimiento. Es lo que hace a los sistemas de IA suficientemente dignos de confianza para desplegar a escala.",

  "slide-67": "Las referencias clave del capítulo seis. El texto oficial del EU AI Act y la línea de tiempo de implementación son lecturas esenciales para quienes despliegan IA en Europa. Stochastic Parrots de Bender, Gebru y colegas es un análisis crítico fundamental de los modelos de lenguaje grandes y los riesgos que conllevan. La investigación COMPAS de ProPublica es lectura obligatoria sobre sesgo algorítmico en la justicia penal. La documentación NIST AI RMF e ISO 42001 proporciona los frameworks de gobernanza discutidos en este capítulo.",

  "slide-68": "Esta tabla les da un mapa práctico de dónde la IA ofrece valor medible en varios sectores hoy. Las finanzas usan IA para detección de fraude, scoring de crédito y procesamiento de documentos — todo en producción en las principales instituciones. La salud la aplica a síntesis de notas clínicas, análisis de imágenes radiológicas y análisis de interacciones medicamentosas — con supervisión humana en todas las decisiones clínicas. Los despachos de abogados usan IA para revisión de contratos e investigación de casos. La manufactura la aplica a mantenimiento predictivo y control de calidad. El retail la usa para personalización, pronósticos de demanda y optimización de la cadena de suministro. El patrón en todos los sectores: la IA maneja el trabajo de reconocimiento de patrones de alto volumen para que los humanos puedan enfocarse en el juicio y la gestión de excepciones.",

  /* ── CONCLUSIÓN ──────────────────────────────────────────── */

  "conclusion": "Hemos llegado a la conclusión. Seis capítulos — desde las matemáticas de la atención de los transformers hasta la ética de los agentes autónomos. Tomemos un momento para consolidar las ideas más importantes antes de cerrar.",

  "slide-70": "Aquí está el resumen de los seis capítulos. Capítulo uno: los LLM son predictores probabilísticos de tokens — codifican patrones estadísticos, no hechos, y la escala es lo que desbloqueó las capacidades. Capítulo dos: el prompt engineering es el arte de comunicarse con precisión — rol, contexto, formato y ejemplos mejoran drásticamente la calidad del output. Capítulo tres: el coding asistido por IA ofrece ganancias de productividad reales pero amplifica cualquier habilidad y hábito que aporten. Capítulo cuatro: el RAG conecta la IA a sus datos privados recuperando documentos en el momento de la consulta — sin re-entrenamiento, siempre actualizado. Capítulo cinco: los agentes actúan — se mueven en ciclos reason-act-observe usando herramientas para completar tareas multi-paso de manera autónoma. Capítulo seis: la IA responsable es una disciplina de ingeniería, no una reflexión tardía.",

  "slide-71": "Cuatro intuiciones para llevar más allá de este curso. Primera: los LLM son máquinas de patrones, no bases de datos de hechos. Predicen el siguiente token, no la verdad. Verifiquen cada output que importa. Segunda: los prompts son programas. Los prompts estructurados superan consistentemente las solicitudes vagas — traten el prompt engineering con el mismo rigor que aplican al código. Tercera: el contexto lo es todo. Lo que ponen en la ventana de contexto — rol, antecedentes, ejemplos, restricciones — determina la calidad de lo que sale. Cuarta: los sistemas de IA necesitan gobernanza. Cada despliegue de alto riesgo debe tener una pista de auditoría clara, una ruta de anulación humana y evaluación regular para sesgo y precisión.",

  "slide-72": "Aquí están los recursos que recomiendo para continuar este viaje. Para los fundamentos: los cursos cortos de DeepLearning.AI de Andrew Ng cubren transformers, RAG y agentes en pocas horas cada uno. La serie Zero to Hero de Andrej Karpathy construye comprensión de redes neuronales desde cero en código. El curso NLP de HuggingFace es la mejor introducción estructurada a la biblioteca transformer. Para mantenerse actualizados: el podcast Latent Space cubre investigación de IA de vanguardia en profundidad, y la página HuggingFace Daily Papers rastrea nuevas publicaciones tan pronto como se publican. El hábito más valioso es la lectura curada y consistente — incluso treinta minutos a la semana los mantiene orientados en este campo que evoluciona rápidamente.",

  "slide-73": "Hemos llegado al final de este curso. La inteligencia artificial es una herramienta extraordinaria — y como cualquier herramienta poderosa, su valor depende completamente de la intención, el juicio y el cuidado de las personas que la usan. Los modelos seguirán mejorando. Los principios que hemos cubierto — anclar los outputs, diseñar para la supervisión, probar el sesgo, construir la responsabilidad de manera nativa — seguirán siendo relevantes sin importar qué sistemas específicos existan en un año o cinco. Permanezcan curiosos. Construyan cosas. Y si tienen preguntas al aplicar estas ideas, siempre estoy disponible en LinkedIn. Gracias.",

  /* ── ANEXO ───────────────────────────────────────────────── */

  "annex": "El anexo es su sección de referencia. Contiene diagramas, hojas de referencia y material de apoyo para los seis capítulos. Vuelvan a estas diapositivas cuando necesiten una referencia visual rápida o una mirada más profunda a un concepto específico.",

  "slide-75": "Esta visualización muestra el mecanismo de auto-atención en acción. Cada fila representa un token que consulta a todos los demás en la oración. Cuanto más brillante es una celda, más fuerte es el peso de atención — lo que significa que esos dos tokens están estrechamente relacionados en la visión del modelo. Noten cómo la palabra él presta fuerte atención a gato — el modelo aprendió a resolver las referencias pronominales sin reglas gramaticales explícitas. Este comportamiento emerge completamente del entrenamiento en miles de millones de oraciones. Los transformers modernos ejecutan múltiples cabezas de atención en paralelo, cada una rastreando diferentes relaciones lingüísticas: concordancia sujeto-verbo, pares adjetivo-nombre y correferencia de largo alcance.",

  "slide-76": "La hoja de referencia de patrones de prompt engineering es su tarjeta de referencia práctica. El patrón Role asigna una persona experta para mejorar profundidad y estilo. Chain-of-Thought fuerza el razonamiento paso a paso antes de la respuesta final — esencial para matemáticas, lógica y tareas multi-paso. Few-Shot proporciona ejemplos ya resueltos para demostrar el formato exacto que necesitan. Tree of Thought explora múltiples caminos de razonamiento simultáneamente. Meta-Prompting le pide al modelo que genere o refine un prompt para una tarea dada. Usen esta hoja como lista de verificación cada vez que diseñen un nuevo prompt para uso en producción.",

  "slide-77": "Este diagrama muestra el ciclo de vida completo de una única solicitud de IA. Un usuario o una aplicación envía un prompt. El texto se tokeniza — convertido en IDs enteros a aproximadamente tres cuartos de palabra por token. Esos tokens fluyen por las capas de atención y feed-forward del LLM, opcionalmente aumentadas por llamadas de herramientas o un paso de recuperación RAG. El modelo genera probabilidades de tokens, muestrea el siguiente token y lo agrega — repitiendo hasta completar. El output vuelve a la aplicación, donde puede analizarse, validarse y mostrarse. El paso crítico que la mayoría de los desarrolladores subestima es la validación humana: traten el output de IA como un borrador seguro, no una respuesta definitiva, en cualquier contexto de alto riesgo.",

  "slide-78": "El stack de IA moderno tiene cuatro capas. En la cima, la capa de aplicación: la interfaz de chat, la aplicación web o la pasarela de API con la que los usuarios interactúan. Debajo, la capa de orquestación: agentes, planificadores y lógica de razonamiento multi-paso implementados con LangGraph, AutoGen o MCP. Luego la capa de inferencia: el propio modelo de lenguaje, accesible mediante API gestionada o auto-hospedado para la soberanía de datos. En la base, la capa de datos: bases de datos vectoriales, almacenes de documentos y fuentes de datos estructurados de los que los pipelines RAG extraen. Entender en qué capa vive un problema ayuda a elegir la solución correcta y el equipo correcto para construirla.",

  "slide-79": "Ampliando la vista al ecosistema completo: en la cima, usuarios e interfaces — UI de chat, plugins de IDE, aplicaciones móviles y consumidores de API. Debajo, la capa de aplicación gestiona enrutamiento, caché y limitación de tasa. Una capa de razonamiento donde los agentes descomponen tareas y orquestan llamadas de herramientas. Una capa de inferencia donde el modelo de lenguaje procesa el contexto y genera texto. Una capa de recuperación para el RAG — búsqueda vectorial y almacenes de documentos. Y en la base, la infraestructura: clústeres de GPU, proveedores de nube, monitoreo y herramientas de cumplimiento. Cada capa es un punto de integración potencial, una oportunidad de optimización y un punto de control de gobernanza.",

  "slide-80": "El costo de la IA está impulsado por tres variables. Tamaño del modelo: los modelos más grandes cuestan de diez a cien veces más por llamada que los más pequeños — GPT-4o mini o Claude Haiku ofrecen la mayoría de las capacidades a una fracción del costo de GPT-4o. Conteo de tokens: el precio es por token, y los tokens de salida típicamente cuestan de tres a cinco veces más que los tokens de entrada. Frecuencia de llamadas: incluso costos modestos por llamada se vuelven significativos a escala. El consejo práctico: siempre prueben primero los modelos más pequeños en su tarea específica. A menudo encontrarán que un modelo diez veces más barato ofrece el noventa por ciento de la calidad que necesitan.",

  "slide-81": "Esta diapositiva documenta los archivos fuente de diagramas PlantUML incluidos en este repositorio. Cada diagrama en el curso tiene un archivo dot-puml correspondiente en la carpeta diagrams, junto con un archivo dot-link que apunta a la versión renderizada. Los diagramas cubren la arquitectura del transformer, el ciclo de vida completo de los LLM, el ecosistema de agentes de IA, el flujo del pipeline RAG, el flujo de trabajo de desarrollo asistido por IA y más. Si quieren adaptar algún diagrama para sus presentaciones: hagan fork del repositorio, modifiquen el fuente dot-puml y regeneren. PlantUML les da diagramas textuales con control de versiones que se actualizan limpiamente cuando el contenido cambia.",

  "slide-82": "HuggingFace es para los modelos de IA lo que GitHub es para el código fuente — el repositorio central donde los investigadores publican los pesos y los desarrolladores los descargan. La biblioteca Transformers proporciona una API Python consistente que funciona para todas las principales arquitecturas, así que cambiar de modelo es una modificación de una línea. GGUF es un formato de archivo que empaqueta los pesos del modelo y los metadatos de arquitectura en un único archivo autónomo, introducido en 2023 como estándar de distribución local portátil. La cuantización reduce la precisión numérica de los pesos del modelo — de floats de 32 bits a enteros de 4 bits — haciendo los modelos aproximadamente cuatro veces más pequeños con mínima pérdida de calidad. La variante Q4-K-M es ampliamente considerada el mejor equilibrio tamaño-calidad para uso local.",

  "slide-83": "Ejecutar modelos de lenguaje localmente — en su propio hardware, sin dependencia de la nube — es cada vez más práctico. Ollama es el punto de partida más simple: envuelve modelos locales en una API REST compatible con OpenAI en el puerto 11434, así que pasan de la nube al local cambiando una única URL. LM Studio proporciona una interfaz de escritorio cuidada con un navegador de modelos integrado. LLaMA dot cpp es el motor de inferencia subyacente escrito en C++, que soporta aceleración CPU y GPU en todas las plataformas. La restricción principal es la RAM: un modelo de siete mil millones de parámetros en cuantización de 4 bits necesita alrededor de cuatro gigabytes — la mayoría de los laptops modernos pueden manejarlo. Las Mac con Apple silicon son particularmente adecuadas porque su memoria unificada sirve tanto cargas de trabajo CPU como GPU."

};
