/* ═══════════════════════════════════════════════════════════
   SPEAKER NOTES — Français
   Style voice-over — parlé directement à l'auditeur.
   Key = id de la diapositive  ou  "slide-{index}" pour les slides sans id.
   ═══════════════════════════════════════════════════════════ */
window.NOTES_FR = {

  /* ── PRÉFACE ─────────────────────────────────────────────── */

  "slide-0": "Bienvenue dans Comprendre l'Intelligence Artificielle — un parcours pratique des fondamentaux aux agents autonomes. Ce cours est conçu pour les développeurs, architectes, chefs de produit et tous ceux qui veulent vraiment comprendre comment fonctionne l'IA moderne. Nous couvrons six chapitres, chacun s'appuyant sur le précédent, pour que vous repartiez avec une vision cohérente plutôt que des buzzwords déconnectés. Vous pouvez changer de langue à tout moment depuis le menu en haut. Commençons.",

  "slide-1": "Avant de commencer, un bref repérage. Utilisez les flèches ou faites défiler pour naviguer. Le bouton menu ouvre le navigateur de chapitres pour sauter à n'importe quelle section. Chaque chapitre se termine par une diapositive de références pour approfondir. Les diapositives interactives — celles avec des animations ou des curseurs — sont autonomes : suivez simplement les instructions à l'écran. Le matériel est disponible en anglais, italien, français et espagnol — changez de langue à tout moment depuis le menu en haut.",

  "agenda": "Voici ce que nous allons couvrir ensemble. Six chapitres, chacun s'appuyant sur le précédent. Le chapitre un pose les bases : qu'est-ce que l'IA vraiment, comment fonctionnent les transformers, et que signifient tous ces paramètres. Le chapitre deux porte sur le prompt engineering — l'art de communiquer avec précision avec les modèles IA. Le chapitre trois couvre le codage assisté par IA, de l'autocomplétion aux outils agentiques. Le chapitre quatre explique le Retrieval-Augmented Generation — comment connecter l'IA à vos données privées. Le chapitre cinq explore les agents IA autonomes et le Model Context Protocol. Le chapitre six aborde l'éthique, les biais et la gouvernance. L'annexe contient du matériel de référence auquel vous pouvez revenir à tout moment.",

  /* ── CHAPITRE 1 ───────────────────────────────────────────── */

  "chapter-1": "Le chapitre un pose les fondements conceptuels pour tout ce qui suit. L'idée la plus importante est celle-ci : l'intelligence artificielle n'est pas de la magie — c'est des mathématiques appliquées à d'énormes quantités de données. Nous passerons des systèmes déterministes, comme un programme if-then classique qui donne toujours la même réponse, aux systèmes probabilistes, où le modèle fait sa meilleure prédiction basée sur des patterns appris à partir de milliards d'exemples. À la fin de ce chapitre, vous comprendrez comment fonctionne un réseau de neurones transformer, ce que signifient vraiment température et token, et pourquoi le matériel spécialisé est important.",

  "slide-4": "La distinction la plus fondamentale dans l'IA moderne est le passage du calcul déterministe au calcul probabiliste. Le logiciel traditionnel est déterministe : donnez le même input et vous obtenez toujours le même output. Les modèles de langage sont probabilistes : à la même question, ils peuvent répondre différemment à chaque fois. Ce n'est pas un défaut — c'est by design. Le modèle ne cherche pas une réponse fixe. Il échantillonne plutôt depuis une distribution de probabilité sur les mots possibles suivants. Le paramètre température contrôle à quel point cette distribution est étroite ou large. Ce changement — de la correction garantie à la vraisemblance optimisée — est le modèle mental sur lequel repose tout le reste du cours.",

  "slide-5": "Il y a en fait deux ères dans l'histoire de l'IA moderne : tout avant 2017, et tout après. Avant 2017, l'approche dominante étaient les réseaux de neurones récurrents, qui traitaient le texte mot par mot et tendaient à oublier le contexte au-delà de quelques phrases. En 2017, une équipe de Google a publié un article intitulé Attention Is All You Need, introduisant l'architecture transformer. L'innovation clé : chaque mot dans une phrase peut se référer directement à tout autre mot simultanément, quelle que soit la distance. Cette seule intuition a débloqué un saut de capacité. En 2020, GPT-3 a démontré que mettre à l'échelle cette architecture avec suffisamment de données et de calcul produit un modèle capable d'apprendre de nouvelles tâches à partir de quelques exemples — sans entraînement supplémentaire.",

  "slide-6": "Trois forces ont convergé entre 2017 et 2023 pour accélérer l'IA au-delà de toute attente précédente. D'abord, les données : internet a produit du texte à une échelle sans précédent — CommonCrawl, Wikipedia, GitHub et des milliards de livres numérisés ont fourni la matière première d'entraînement. Ensuite, le calcul : les GPU ont évolué du matériel de jeu en moteurs de calcul massivement parallèles capables d'entraîner des modèles avec des centaines de milliards de paramètres. Troisièmement, l'architecture transformer elle-même : elle pouvait être entraînée beaucoup plus efficacement que les approches précédentes, et sa capacité scalait de manière prévisible avec plus de données et de calcul. Quand ces trois forces se sont combinées, les progrès qui auraient autrefois pris une décennie ont commencé à se produire en quelques mois.",

  "slide-7": "Cette animation montre ce qui se passe vraiment quand un modèle de langage génère du texte. Chaque pas en avant produit exactement un token. Remarquez les barres de probabilité : le modèle n'est jamais certain du mot suivant. Il maintient une distribution complète de possibilités et en échantillonne. Quand la température est supérieure à zéro, les tokens à faible probabilité ont encore une chance d'être sélectionnés — c'est pourquoi générer le même prompt deux fois peut produire des résultats différents. Cela explique aussi pourquoi les modèles de langage diffusent l'output token par token plutôt que de retourner une réponse complète instantanément : ils calculent littéralement le texte un token à la fois.",

  "slide-8": "Traçons le chemin qu'un texte emprunte à travers un transformer. D'abord, le texte brut est divisé en tokens — de petits fragments de caractères. Chaque token est converti en un embedding : un vecteur de nombres qui encode sa signification dans un espace de haute dimension. Ces embeddings passent ensuite par le mécanisme d'auto-attention — le cœur du transformer. Ici, chaque token examine chaque autre token et décide quel poids lui accorder. C'est ainsi que le modèle résout que 'il' fait référence à 'chat' plusieurs mots en arrière, sans règles explicites. Après l'attention, le résultat passe par des couches feed-forward, et enfin le modèle produit une distribution de probabilité sur le prochain token possible. Tout ce processus se répète pour chaque token généré.",

  "slide-03a": "Cette diapositive illustre le pipeline d'échantillonnage complet — le chemin de l'entrée textuelle à un seul token généré. Les embeddings convertissent chaque token en un vecteur à haute dimension. L'auto-attention permet à chaque token de se référer à tous les autres. Les couches feed-forward appliquent une transformation non linéaire apprise. Le softmax convertit les scores bruts en une distribution de probabilité sur le vocabulaire entier. Enfin, l'étape d'échantillonnage extrait le prochain token de cette distribution, modulée par température et Top-P. Comprendre ce pipeline aide à raisonner sur pourquoi les choix de paramètres ont les effets qu'ils ont sur l'output du modèle.",

  "slide-10": "Comprendre les paramètres clés de génération est essentiel pour travailler avec n'importe quel modèle IA. La température est la plus importante : à zéro, le modèle choisit toujours le token à probabilité la plus haute, produisant un output déterministe et reproductible. Au-dessus de zéro, les tokens à faible probabilité ont une chance — augmentant la créativité mais aussi l'imprévisibilité. Pour la génération de code et l'extraction de données, gardez la température basse. Pour le brainstorming, augmentez-la. Un token fait environ trois quarts d'un mot français — et c'est l'unité sur laquelle votre facture API est calculée. Max token limite la longueur de la réponse et le coût par appel. Top-P contrôle la taille du pool de candidats. Changez ces paramètres un à la fois, car ils interagissent.",

  "slide-11": "Trois limitations pratiques sont les plus importantes lors de la construction d'applications IA dans le monde réel. D'abord, les modèles de langage n'ont pas de mémoire persistante : chaque conversation repart de zéro, sans souvenir de rien de ce qui a été dit auparavant. Si la continuité est importante, vous devez injecter l'historique pertinent dans le prompt vous-même. Deuxièmement, les fenêtres de contexte sont finies : chaque modèle a une longueur d'entrée maximale, et le contenu au-delà de cette limite est simplement coupé. Troisièmement, les hallucinations sont inhérentes : les modèles peuvent produire des outputs factuellement incorrects mais fluides et confiants sur des sujets hors de leur distribution d'entraînement. Comprendre ces contraintes à l'avance prévient une catégorie de surprises en production.",

  "slide-12": "Pourquoi les modèles IA nécessitent-ils du matériel si spécialisé ? Au cœur, les couches de réseaux de neurones sont d'énormes multiplications matricielles — multiplier des tableaux de milliards de nombres simultanément. Les GPU ont été construits à l'origine pour le rendu graphique, qui implique exactement ce type de calcul hautement parallèle. Un GPU H100 moderne dispose de quatre-vingts gigaoctets de mémoire à haute bande passante et traite des milliers d'opérations en parallèle. Les fournisseurs cloud comme Azure, AWS et Google Cloud exposent ces capacités via des API, vous payez donc par token plutôt que d'acheter du matériel. La courbe des coûts est dramatique : le coût d'inférence baisse d'environ dix fois par an — c'est pourquoi exécuter des modèles capables localement est déjà pratique aujourd'hui.",

  "slide-13": "Une des propriétés les plus surprenantes des modèles de langage modernes de grande taille est leur généralité. Chaque tâche dans ce nuage de mots — analyse de sentiment, traduction, résumé, génération de code, reconnaissance d'entités nommées, classification, réponse aux questions et des dizaines d'autres — peut être gérée par un seul modèle de fondation. Avant 2020, chacune de ces tâches nécessitait un modèle dédié, spécialement entraîné. Aujourd'hui, un seul modèle les gère toutes. L'implication est profonde : le coût marginal d'essayer un nouveau cas d'usage IA est maintenant essentiellement nul, car vous réutilisez le même modèle.",

  "slide-14": "Le paysage des modèles IA change environ tous les trois à six mois, donc traitez ce tableau comme un instantané. Dimensions clés pour choisir un modèle : capacité pour votre tâche spécifique, taille de la fenêtre de contexte, coût par token, s'il est open-weight ou propriétaire, et où l'inférence s'exécute pour la conformité. Gemini 2.0 mène sur la fenêtre de contexte avec plus d'un million de tokens. Llama 3 et Mistral sont open-weight et peuvent être auto-hébergés — important pour la souveraineté des données. GPT-4o mini offre la plupart de la qualité de GPT-4o complet à une fraction du coût. Votre choix dépend de la tâche, du budget, de la latence et des exigences de conformité.",

  "slide-15": "Chaque modèle de langage a des modes d'échec prévisibles que vous devez connaître avant de le déployer. L'hallucination est la plus dangereuse : le modèle génère du texte qui semble fluide et confiant mais est factuellement incorrect — sans signal visible d'incertitude. Le knowledge cutoff signifie que le modèle ne sait rien des événements après la fin de ses données d'entraînement. Le raisonnement mathématique n'est pas fiable — les modèles ratent souvent l'arithmétique d'une manière qui semble surprenante étant donné leurs autres capacités. Et le biais : puisque les modèles apprennent des patterns à partir de texte généré par des humains, ils reflètent les préjugés dans ce texte. Aucun de ces défauts n'est un bug qui sera corrigé — ce sont des propriétés fondamentales de l'architecture actuelle. Concevez votre système en conséquence.",

  "ai-system-architecture": "Ce diagramme montre l'architecture en couches complète d'un système IA moderne. En haut se trouvent les acteurs : l'utilisateur final qui envoie des requêtes, le développeur qui construit et surveille le système, et tout service ou API externe. Les requêtes descendent à travers une couche applicative qui gère l'authentification, la limitation de débit et le contexte de la conversation. En dessous se trouve la couche d'intégration IA : construction du prompt, récupération optionnelle depuis une base de données vectorielle pour le RAG, et l'appel au modèle de langage. La réponse remonte à travers les mêmes couches. Chaque couche est une opportunité d'ajouter des contrôles de sécurité, de la journalisation et du contrôle — c'est pourquoi les systèmes IA bien conçus sont construits en couches plutôt qu'en connexion directe utilisateur-modèle.",

  "slide-17": "Consolidons les idées clés du chapitre un. Les LLM sont probabilistes, pas déterministes : la même question peut produire des réponses différentes, et c'est by design. Les transformers ont rendu cela possible en traitant des séquences entières simultanément via l'auto-attention. La température et les limites de tokens sont les principaux contrôles que vous utiliserez dans chaque intégration. Les fenêtres de contexte définissent l'information maximale sur laquelle un modèle peut raisonner en un seul appel. Et toutes les capacités — traduction, code, résumé, raisonnement — émergent d'un seul objectif de pré-entraînement : prédire le prochain token. C'est la fondation sur laquelle repose tout le reste du cours.",

  "slide-18": "Clôturons le chapitre un avec les références fondamentales. Le papier qui a tout lancé est Attention Is All You Need de Vaswani et collègues, publié par Google en 2017 — il a introduit l'architecture transformer qui est à la base de chaque modèle de langage moderne. Le papier GPT-3 d'OpenAI en 2020 a montré que mettre à l'échelle les transformers débloque le few-shot learning — la capacité d'effectuer de nouvelles tâches à partir de quelques exemples dans le prompt. Pour une excellente explication visuelle de comment fonctionne l'attention, The Illustrated Transformer de Jay Alammar est fortement recommandé et disponible gratuitement en ligne.",

  /* ── CHAPITRE 2 ───────────────────────────────────────────── */

  "chapter-2": "Le chapitre deux est là où la théorie devient pratique. Le prompt engineering est la discipline de communiquer avec précision avec les modèles IA. La façon dont vous formulez une demande a un effet énorme sur la qualité de la réponse — et il existe des patterns répétables qui améliorent de manière fiable les résultats. Nous allons disséquer l'anatomie d'un bon prompt, apprendre six patterns éprouvés du zero-shot au chain-of-thought, et voir des rééecritures réelles avant-après. Ces compétences s'appliquent à n'importe quel modèle IA, pas seulement à ceux disponibles aujourd'hui.",

  "slide-20": "Un prompt bien structuré a quatre couches, et comprendre chacune débloque des résultats significativement meilleurs. En haut se trouve le system prompt : c'est là que vous définissez le rôle, les contraintes et la persona du modèle. Une simple instruction comme tu es un senior data engineer spécialisé en Python déplace de manière mesurable le style et la profondeur de réponse. Ensuite le contexte : les informations de fond pertinentes dont le modèle a besoin. Puis vient le message utilisateur — la tâche ou la question réelle. Enfin, les instructions sur le format de sortie : dites explicitement au modèle si vous voulez du JSON, une liste numérotée, un paragraphe ou un tableau. Le modèle ne connaît pas vos exigences downstream sauf si vous les spécifiez.",

  "slide-21": "Trois patterns fondamentaux de prompting couvrent la grande majorité des cas d'usage. Zero-shot : décrivez la tâche directement, sans exemples — les modèles modernes gèrent la plupart des tâches de cette façon. Few-shot : fournissez de deux à cinq exemples entrée-sortie qui démontrent le format et le style que vous voulez — particulièrement efficace pour un output structuré cohérent. Chain-of-thought : demandez au modèle de raisonner étape par étape avant de donner la réponse finale — cela améliore drastiquement la précision sur les tâches mathématiques, logiques et multi-étapes. Ces patterns se combinent naturellement : un system prompt plus des exemples few-shot plus chain-of-thought est l'une des architectures de prompt les plus fiables en production.",

  "slide-22": "Au-delà des bases, plusieurs patterns avancés étendent ce que le prompting peut accomplir. Les system prompts définissent la persona, les règles et les garde-fous du modèle — les utilisateurs ne les voient jamais, mais ils façonnent chaque réponse. Le role playing assigne une persona d'expert spécifique pour améliorer la profondeur de l'output. Le Retrieval-Augmented Generation injecte des documents pertinents récupérés d'une base de connaissances dans le prompt avant la génération — couvert en détail au chapitre quatre. L'utilisation d'outils permet au modèle de demander l'exécution de fonctions externes — la base des agents au chapitre cinq. Ces techniques sont particulièrement précieuses lors de la construction de systèmes IA en production.",

  "slide-23": "L'erreur la plus courante lorsque l'on travaille avec l'IA est d'écrire des prompts vagues. Comparez résume ce document avec résume ce document en exactement trois points pour un cadre non technique, en français simple, sans jargon, maximum quinze mots par point. Le second produit de manière cohérente un output meilleur et plus utilisable. Lignes directrices clés : donnez toujours un rôle dans le system prompt ; exprimez les contraintes positivement — dites ce que vous voulez, pas ce que vous ne voulez pas ; soyez explicite sur la longueur et le format ; et incluez un exemple lorsque le style de sortie souhaité n'est pas évident. Testez n'importe quel prompt sur au moins dix inputs différents avant de le mettre en production.",

  "slide-24": "Le prompt makeover est l'un des moyens les plus efficaces de construire de l'intuition. Prenez un prompt médiocre et appliquez une réécriture structurée : ajoutez un rôle clair, spécifiez le format de sortie, ajoutez des contraintes, incluez un exemple. Le pattern est remarquablement cohérent : le prompt naïf d'avant produit un output générique, souvent inutilisable ; le prompt ingénié d'après produit quelque chose de spécifique, structuré et prêt à l'emploi. L'écart entre les deux n'est pas le modèle — c'est la qualité de l'instruction. Un modèle mental utile : pensez à un prompt comme à un programme que vous écrivez pour un interprète très capable mais extrêmement littéral.",

  "slide-25": "Voyons comment les mêmes principes de prompting s'appliquent dans différents rôles professionnels. Un manager pourrait demander à l'IA de résumer un rapport de vingt pages en cinq points pour un public non technique. Un développeur pourrait lui demander d'écrire un test unitaire pour une fonction spécifique avec des exigences de couverture précises. Un analyste de données pourrait demander un script Python qui ingère un CSV, calcule des statistiques récapitulatives et signale les valeurs aberrantes. Le pattern est le même dans chaque cas : indiquer le rôle, fournir le contexte, spécifier le format. La valeur n'est pas dans l'IA qui fait votre réflexion — mais dans la prise en charge du travail mécanique de production afin que vous puissiez vous concentrer sur le jugement.",

  "slide-26": "Ce playground interactif vous permet d'explorer comment les paramètres de génération affectent l'output en temps réel. Réglez la température à zéro et générez le même prompt deux fois — vous obtiendrez des résultats identiques à chaque fois. Augmentez progressivement la température et observez comment l'output se diversifie. Top-P contrôle le pool de candidats : une valeur faible confine le modèle aux tokens les plus probables ; une valeur élevée ouvre des territoires plus créatifs. Ce ne sont pas des paramètres abstraits — ils contrôlent directement le compromis cohérence-créativité dans votre application. Les applications orientées client qui ont besoin de réponses fiables bénéficient d'une température basse. Les outils créatifs bénéficient d'une température élevée.",

  "slide-27": "C'est maintenant à votre tour de pratiquer. Prenez une tâche réelle — rédiger une description de poste, analyser un dataset, rédiger une proposition technique — et écrivez un prompt initial. Exécutez-le, voyez ce que vous obtenez, puis améliorez-le systématiquement : ajoutez un rôle, ajoutez des instructions de format, ajoutez un exemple. Comparez l'output de chaque itération avec le précédent. Vous découvrirez que chaque raffinement fait une différence significative. L'objectif n'est pas la perfection au premier essai — c'est de construire le muscle itératif de générer, évaluer critiquement, affiner et répéter. Ce cycle est la compétence fondamentale du prompt engineering efficace.",

  "slide-28": "Les points clés du chapitre deux. Chaque prompt efficace a quatre parties : rôle, contexte, tâche et format. En manquer une et la qualité en souffre. Les patterns de prompting — zero-shot, few-shot, chain-of-thought — sont combinables : utilisez-les ensemble pour des exigences complexes. Les techniques avancées comme les system prompts et l'output structuré étendent le prompting en territoire architectural. Et rappelez-vous : un prompt est un programme. Traitez-le comme du code — versionnez-le, testez-le sur des inputs divers et affinez-le de manière itérative.",

  "slide-29": "Les références clés du chapitre deux. Anthropic et OpenAI publient tous deux des guides détaillés de prompt engineering qui reflètent les meilleures pratiques les plus récentes pour leurs modèles. Le papier Chain-of-Thought Prompting de Wei et collègues a établi pourquoi le raisonnement étape par étape améliore drastiquement les performances sur des tâches complexes. Le site promptingguide.ai et le cours Learn Prompting sont d'excellentes ressources structurées pour construire ces compétences depuis zéro.",

  /* ── CHAPITRE 3 ───────────────────────────────────────────── */

  "chapter-3": "Le chapitre trois porte sur ce qui se passe quand l'IA devient votre partenaire de codage. Nous couvrirons tout le spectre : du simple autocomplétion, aux assistants d'écriture de code conversationnels, aux outils entièrement agentiques qui comprennent l'ensemble du codebase et apportent des modifications autonomes à plusieurs fichiers. Il y a un réel gain de productivité mesurable — soutenu par des études contrôlées. Il y a aussi des risques réels lorsque ces outils sont utilisés sans comprendre ce qu'ils produisent. Nous examinerons les deux côtés honnêtement.",

  "slide-31": "En février 2025, le chercheur en IA Andrej Karpathy a inventé l'expression vibe coding pour décrire une nouvelle façon d'écrire du logiciel. Vous décrivez ce que vous voulez en langage naturel, l'IA génère le code, vous l'exécutez, observez ce qui casse et décrivez la correction. Pas nécessairement en lisant chaque ligne avant de le mettre en production. Les développeurs qui adoptent ce cycle d'itération rapide rapportent travailler trois à cinq fois plus vite sur des tâches bien définies. Mais il y a un avertissement critique : le vibe coding amplifie vos compétences existantes — il ne remplace pas la compréhension. Si vous ne pouvez pas évaluer si le code est correct et sécurisé, vous ne détecterez pas les erreurs que l'IA fait en toute confiance.",

  "slide-32": "Le workflow de développement assisté par IA suit un cycle clair : décrivez la tâche avec précision, générez du code, révisez de manière critique, exécutez-le, identifiez ce qui ne va pas et affinez. Le mot à souligner est critiquement. Les outils IA excellent dans la génération de boilerplate, le scaffolding, les tests unitaires et les transformations bien spécifiées. Ils peinent avec la logique métier implicite, le code sensible à la sécurité et tout ce qui nécessite une connaissance contextuelle profonde de votre codebase. Des outils comme Cursor et Windsurf réduisent la friction avec des vues diff inline et l'édition multi-fichiers. Les meilleurs praticiens ont réduit ce cycle d'itération à moins de deux minutes par modification.",

  "slide-33": "Le paysage des outils de codage IA a trois niveaux. Assistants intégrés à l'IDE : GitHub Copilot avec la plus large adoption enterprise ; Cursor, populaire parmi les startups pour son mode composer multi-fichiers ; et Windsurf, qui excelle dans la conscience des grands codebases. Les agents entièrement autonomes comme Devin peuvent recevoir une tâche, parcourir la documentation, écrire du code, exécuter des tests et faire des commits avec une interaction humaine minimale. Le facteur différenciant dans l'évaluation des outils est le contexte du codebase : quelle partie de votre code existant l'outil peut tenir en contexte simultanément. Plus de contexte signifie des suggestions plus précises et contextuellement appropriées.",

  "slide-34": "Les outils de codage IA fonctionnent le mieux sur des problèmes bien définis et autonomes : API CRUD, tests unitaires, scripts de transformation de données, fichiers de configuration, expressions régulières, mises en page CSS et documentation. Là où ils peinent de manière cohérente : la logique métier complexe avec des contraintes non déclarées, le code critique pour la sécurité où une erreur subtile est exploitable, et les codebases legacy où des années de décisions vivent dans des conventions non documentées. La règle d'or : plus votre spécification est claire, meilleur est l'output. L'IA amplifie la qualité de votre réflexion — elle ne la remplace pas.",

  "slide-35": "Les gains de productivité des outils de codage IA sont réels et mesurables. Une étude contrôlée randomisée de GitHub et Microsoft en 2022 a trouvé que les développeurs utilisant Copilot complétaient une tâche de serveur HTTP cinquante-cinq pourcent plus vite. Le rapport GitHub Octoverse 2024 a trouvé que Copilot génère en moyenne quarante-six pourcent du code dans les fichiers où il est activé. L'enquête Developer Survey de Stack Overflow a montré que soixante-seize pourcent des développeurs utilisent déjà ou prévoient d'adopter des outils de codage IA. Pour les développeurs seniors, le rôle évolue : de l'écriture de fonctions individuelles vers des décisions architecturales, la révision rigoureuse de l'output IA, et l'ingénierie des spécifications précises qui dirigent l'IA efficacement.",

  "slide-36": "Cet exercice porte sur le processus, pas seulement le résultat. Prenez n'importe quel fichier CSV et utilisez un outil de codage IA pour écrire un script d'analyse : statistiques récapitulatives, détection des valeurs aberrantes et une visualisation simple. Faites attention à où l'IA fait des hypothèses sans demander — types de colonnes, gestion des valeurs manquantes, format de sortie. Notez ce qu'elle rate la première fois. Pratiquez le cycle : générez, révisez de manière critique, testez et affinez. À la fin, vous aurez un script fonctionnel et une intuition concrète de précisément où l'assistance IA ajoute de la valeur et où votre jugement reste indispensable.",

  "slide-37": "Les points clés du chapitre trois. Les outils de codage IA offrent de réels gains de productivité — de trente-cinq à cinquante-cinq pourcent sur des tâches bien définies, soutenus par des études contrôlées. Mais l'amplification fonctionne dans les deux sens : les bonnes pratiques sont mises à l'échelle, et les mauvaises aussi. Révisez toujours de manière critique le code généré par l'IA — pas seulement pour la correction mais pour la sécurité, les cas limites et la maintenabilité. Le rôle émergent n'est pas prompteur mais ingénieur AI-enabled : quelqu'un qui spécifie l'intention avec précision, évalue rigoureusement l'output IA et l'intègre en toute sécurité dans un système plus grand.",

  "slide-38": "Les références du chapitre trois. Le post original de Karpathy sur le vibe-coding définit la philosophie de ce nouveau mode de développement. L'étude Kalliamvakou est la mesure académique la plus rigoureuse de l'impact de Copilot sur la productivité. Le rapport GitHub Octoverse 2024 fournit des statistiques d'adoption à l'échelle de l'industrie. La documentation de Cursor mérite d'être explorée comme exemple concret de ce à quoi ressemble un IDE natif IA au-delà d'un plugin traditionnel.",

  /* ── CHAPITRE 4 ───────────────────────────────────────────── */

  "chapter-4": "Le chapitre quatre s'attaque à l'une des limitations les plus importantes des modèles de langage en production : ils ne connaissent pas vos données privées, et leur entraînement a une date limite de connaissance fixe. Le Retrieval-Augmented Generation — RAG — est la solution, et c'est l'architecture IA la plus largement déployée dans les logiciels enterprise aujourd'hui. Comprendre le RAG est ce qui sépare ceux qui utilisent l'IA de ceux qui construisent dessus. Nous couvrirons le pipeline complet : indexation des documents, embeddings, recherche vectorielle, récupération et génération basée sur des sources.",

  "slide-40": "Pourquoi ne pas simplement faire du fine-tuning du modèle sur vos documents internes ? Trois raisons : le fine-tuning est coûteux, prend des jours ou des semaines, et — surtout — les faits changent. Quand un document est mis à jour, vous devriez ré-entraîner l'ensemble du modèle. Le RAG adopte une approche fondamentalement différente : au lieu d'incorporer la connaissance dans les poids du modèle, il récupère les informations pertinentes au moment de la requête et les injecte directement dans le prompt. Pensez-y comme donner au modèle un moteur de recherche et des droits copier-coller avant qu'il réponde — il lit les documents récupérés, puis répond. Cela rend le RAG moins cher, plus rapide à mettre à jour, plus vérifiable et plus contrôlable que le fine-tuning pour toute information qui change dans le temps.",

  "slide-41": "Le pipeline RAG a deux phases distinctes. La première est l'indexation, qui se produit une fois ou périodiquement : les documents sont divisés en chunks, chaque chunk est converti en un vecteur embedding, et ces vecteurs sont stockés dans une base de données vectorielle. La seconde est la requête, qui se produit sur chaque requête utilisateur : la question est embedded en utilisant le même modèle, la base de données vectorielle trouve les chunks les plus proches, ces chunks sont injectés dans le prompt comme contexte, et le modèle de langage génère une réponse basée sur des sources. La qualité de chaque étape — stratégie de chunking, modèle d'embedding, profondeur de récupération — détermine la qualité de la réponse finale.",

  "slide-42": "Voici l'intuition derrière les embeddings. Imaginez placer chaque morceau de texte dans un espace de haute dimension où les textes sémantiquement similaires atterrissent près les uns des autres. 'Le chiffre d'affaires a baissé le trimestre dernier' et 'les ventes ont chuté au T3' seraient très proches, même s'ils ne partagent pas de mots. 'Chiffre d'affaires' et 'chaton' seraient loin. Une base de données vectorielle est un index optimisé pour trouver les plus proches voisins dans cet espace à grande vitesse, utilisant des algorithmes comme HNSW qui évitent de comparer chaque paire de vecteurs. Pour la plupart des organisations, pgvector — une extension PostgreSQL — est le point de départ pragmatique. Pinecone et Weaviate sont des bases de données vectorielles dédiées adaptées aux déploiements à grande échelle.",

  "slide-43": "La façon dont vous divisez les documents en chunks a plus d'impact sur la qualité RAG que presque toute autre décision — y compris quel modèle de langage vous utilisez. La division récursive par caractères essaie de diviser aux limites de paragraphe, phrase, puis mot — un bon défaut. Le chunking sémantique utilise la similarité d'embedding entre des phrases adjacentes pour trouver des limites naturelles de sujet — plus coûteux mais préserve mieux le sens. L'indexation hiérarchique stocke à la fois des chunks parent et enfant : la récupération utilise des chunks enfant pour la précision, mais fournit le chunk parent au modèle pour un contexte plus complet. Pour la plupart des contenus, une taille de chunk de cinq cents à mille tokens avec un chevauchement de dix à vingt pourcent est un point de départ fiable.",

  "slide-44": "Cet exemple avant-après rend concret ce qui est en jeu avec le chunking. La requête est : quelle est la politique de congé parental pour les parents adoptifs ? Si le manuel RH est découpé mécaniquement toutes les cinq cents caractères, le texte de politique pertinent pourrait être divisé entre deux chunks — aucun ne se classe haut dans une recherche vectorielle car chaque chunk seul est incomplet. Avec le chunking sémantique — en divisant aux limites naturelles du sujet — toute la section sur le congé parental reste ensemble, est clairement récupérée et produit une réponse correcte et complète. La taille de chunk et le chevauchement ne sont pas des détails de configuration. Ce sont des décisions architecturales qui déterminent directement si votre système RAG fonctionne.",

  "slide-45": "Le RAG est l'architecture IA numéro un en production en 2025, résolvant trois problèmes critiques simultanément. Il ancre les réponses du modèle dans des documents sources vérifiables, transformant un modèle boîte noire en un assistant transparent qui peut citer ses sources. Il élimine les problèmes de knowledge cutoff — mettez à jour votre index documentaire et la connaissance effective du modèle se met à jour immédiatement, sans ré-entraînement. Et il rend l'IA auditée : dans les secteurs réglementés, tracer chaque affirmation à un document source est souvent une exigence de conformité. Les applications courantes incluent les bases de connaissances internes, les Q&A sur la documentation technique, la recherche légale et de conformité, et le support client avec accès aux informations live sur les produits.",

  "slide-46": "Pour cet exercice architectural, concevez un système RAG pour un cas d'usage réel qui vous intéresse. Travaillez sur chaque décision : quels sont vos documents sources, et à quelle fréquence changent-ils ? Quelle taille de chunk et quel chevauchement ont du sens pour ce type de contenu ? Quelles métadonnées devraient accompagner chaque chunk pour permettre le filtrage par date, auteur ou niveau d'accès ? Comment gérez-vous les documents sensibles qui ne devraient pas être largement récupérables ? Et comment instruisez-vous le modèle de dire je ne sais pas quand le contexte récupéré ne répond pas à la question — plutôt qu'halluciner ? Prendre ces décisions à l'avance économise un temps de débogage énorme ensuite.",

  "slide-47": "Les points clés du chapitre quatre. Le RAG résout le problème de la connaissance figée en récupérant des documents pertinents au moment de la requête — pas de ré-entraînement nécessaire, toujours à jour. La stratégie de chunking et le choix du modèle d'embedding ont plus d'impact sur la qualité que le choix du modèle de langage. Incluez toujours un filtre sur les métadonnées et une instruction explicite pour que le modèle reconnaisse quand les informations pertinentes manquent. Et le RAG rend l'IA auditée : chaque réponse peut être tracée à un document source, ce qui est souvent une exigence de conformité dans les secteurs réglementés.",

  "slide-48": "Les références clés du chapitre quatre. Le papier RAG original de Lewis et collègues, publié en 2020, a montré des résultats à l'état de l'art sur le question answering à domaine ouvert. LlamaIndex et LangChain sont les deux principaux frameworks open-source pour construire des pipelines RAG en production — tous deux ont une excellente documentation. Le survey de 2023 de Gao et collègues fournit une cartographie complète des variantes RAG naïves, avancées et modulaires, avec une évaluation claire de quand chaque approche est le plus efficace.",

  /* ── CHAPITRE 5 ───────────────────────────────────────────── */

  "chapter-5": "Le chapitre cinq passe du modèle à l'agent. Jusqu'à présent, nous avons parlé de modèles qui répondent : vous demandez, ils répondent. Un agent IA est différent — il agit. Il peut naviguer sur le web, appeler des API, écrire et exécuter du code, interroger des bases de données et envoyer des e-mails — de manière autonome, enchaînant plusieurs décisions sans humain dans la boucle pour chaque étape. Ce passage de la réponse à l'action est l'un des développements les plus conséquents de l'IA en 2025. Nous couvrirons le cycle de raisonnement ReAct, les quatre patterns agentiques, le Model Context Protocol et l'orchestration multi-agents.",

  "slide-50": "Un agent IA diffère d'un chatbot d'une manière fondamentale : il agit. Là où un chatbot renvoie du texte, un agent émet des instructions qui font arriver des choses dans le monde réel. La structure de base est un cycle appelé ReAct — abréviation de Reason and Act. Le modèle observe l'état actuel, raisonne sur ce qu'il faut faire ensuite, entreprend une action — appelant une fonction, interrogeant une base de données, exécutant du code — observe le résultat, et raisonne à nouveau. Ce cycle continue jusqu'à ce que la tâche soit complète. Les agents peuvent fonctionner pendant des minutes ou des heures, prenant des dizaines de décisions autonomes. Ce pouvoir s'accompagne d'un risque : des limites de portée claires et des points de contrôle de supervision humaine sont essentiels.",

  "slide-51": "Andrew Ng a identifié quatre patterns agentiques qui rendent les workflows IA dramatiquement plus capables. Reflection : le modèle génère un output, puis critique et révise son propre travail — cela seul peut porter la précision de génération de code d'environ cinquante pourcent à plus de quatre-vingt-dix. Tool use : le modèle appelle des fonctions externes pour interagir avec des systèmes réels. Planning : le modèle décompose une tâche complexe en sous-tâches avant d'exécuter. Collaboration multi-agents : plusieurs modèles spécialisés travaillent comme une équipe. L'insight clé : les workflows agentiques itératifs surpassent de manière cohérente un seul prompt one-shot, parfois même en utilisant un modèle de base moins capable.",

  "slide-52": "Le pattern ReAct, introduit par Yao et collègues en 2022, fonctionne en rendant explicite la chaîne de pensée du modèle dans le prompt. Avant chaque action, le modèle écrit une pensée — son raisonnement sur la situation actuelle. Puis il spécifie l'action. Puis il observe le résultat. Puis il écrit une autre pensée. Cet entrelacement de raisonnement et d'action est ce qui rend les agents fiables sur des tâches complexes, car le modèle verbalise son plan avant de l'exécuter. Cela rend aussi le comportement des agents inspectable : vous pouvez lire la trace des pensées et comprendre exactement pourquoi chaque décision a été prise. Les agents bien conçus incluent une logique de retry et des stratégies de repli pour quand un appel d'outil échoue.",

  "slide-53": "L'appel de fonctions et l'utilisation d'outils sont la façon dont les agents interagissent avec le monde. Au lieu de renvoyer du texte simple, le modèle émet un payload JSON structuré spécifiant la fonction qu'il veut appeler et les arguments à passer. Votre code applicatif reçoit ce JSON, exécute la vraie fonction — appelant une API REST, interrogeant une base de données, exécutant un calcul — et renvoie le résultat au modèle. Cette architecture est cruciale pour la sécurité : le modèle demande une action, mais votre code décide de l'exécuter. Vous pouvez ajouter de la validation, du rate limiting et des portes d'approbation humaine pour les actions irréversibles. L'agent demande ; vous contrôlez ce qui se passe réellement.",

  "slide-54": "Le Model Context Protocol, ou MCP, a été publié par Anthropic en novembre 2024 et est rapidement devenu l'interface standard pour connecter les applications IA à des outils externes. Avant MCP, chaque produit IA devait construire des intégrations personnalisées pour chaque outil dont il avait besoin — multipliant la charge de maintenance dans tout l'écosystème. MCP définit un protocole universel : écrivez un serveur MCP pour votre outil une fois, et n'importe quel client compatible MCP — Cursor, VS Code Copilot, Claude, Windsurf — peut l'utiliser immédiatement sans travail supplémentaire. C'est analogue au Language Server Protocol, qui a résolu le même problème dans le monde IDE : écrivez un serveur de langage une fois et chaque éditeur compatible obtient le support gratuitement.",

  "slide-55": "Quand un seul agent n'est pas suffisant, les frameworks multi-agents vous permettent d'orchestrer plusieurs agents spécialisés travaillant ensemble. LangGraph de l'équipe LangChain est l'option la plus prête pour la production : il vous force à modéliser votre agent comme une machine à états explicite avec des états et des transitions définis, rendant le système inspectable, reprendable et sûr à interrompre pour la révision humaine. AutoGen de Microsoft utilise un modèle de chat de groupe où les agents communiquent via un fil de messages partagé — adapté aux workflows de débat et de raffinement. Le conseil pratique : commencez avec le seul agent le plus simple possible et ajoutez des agents seulement quand un seul agent échoue de manière démontrable. La complexité dans les systèmes multi-agents augmente vite, et il en va de même pour les modes d'échec.",

  "slide-56": "Les points clés du chapitre cinq. La différence entre un LLM et un agent est l'action : un agent peut appeler des outils, exécuter du code et prendre des décisions sur plusieurs étapes. Le cycle ReAct — raisonne, agis, observe, répète — est le pattern qui rend les agents fiables et inspectables. L'utilisation d'outils est architecturalement critique : le modèle demande une action, mais votre application décide de ce qui est réellement exécuté. MCP devient rapidement l'interface universelle pour les intégrations d'outils IA. Et les systèmes multi-agents ajoutent de la complexité rapidement — commencez avec le design le plus simple et ajoutez des agents seulement quand un seul agent échoue de manière démontrable.",

  "slide-57": "Les références clés du chapitre cinq. Le papier ReAct de Yao et collègues est le travail fondateur sur la combinaison du raisonnement et de l'action dans les agents IA. La documentation du Model Context Protocol d'Anthropic décrit la norme ouverte maintenant largement adoptée dans les outils de développement IA. Les cours courts de DeepLearning.AI sur les agents et l'utilisation d'outils sont la meilleure introduction pratique — plusieurs sont gratuits. La documentation et les exemples de LangGraph sont excellents pour quiconque construit des systèmes agentiques prêts pour la production.",

  /* ── CHAPITRE 6 ───────────────────────────────────────────── */

  "chapter-6": "Le chapitre six pose la question la plus difficile : juste parce que l'IA peut faire quelque chose, devrait-elle le faire — et dans quelles conditions ? Après cinq chapitres sur les capacités, ce chapitre porte sur la responsabilité. Nous examinerons des cas documentés où les systèmes IA ont causé des dommages réels : outils de recrutement biaisés, scores de risque de récidive défectueux, citations juridiques fabriquées et fraudes deepfake. Nous couvrirons l'EU AI Act, la première loi contraignante au monde sur l'IA. Et nous discuterons des frameworks de gouvernance que vous pouvez appliquer à vos déploiements. L'IA responsable n'est pas un frein à l'innovation — c'est ce qui rend l'innovation digne de confiance.",

  "slide-59": "Les deux limitations les plus importantes des modèles IA actuels sont le biais et l'hallucination. Biais : les modèles apprennent des patterns à partir de données générées par des humains — y compris les préjugés humains. Un modèle de recrutement entraîné sur des données historiques peut apprendre à préférer certains groupes démographiques non pas parce qu'il a été programmé pour le faire, mais parce que ce pattern existait dans le jeu d'entraînement. Hallucination : les modèles génèrent du texte qui semble confiant et fluide mais est factuellement incorrect. Cela se produit parce que le modèle prédit des tokens statistiquement plausibles, il ne récupère pas des faits vérifiés. Les deux sont des échecs prévisibles et systématiques. Concevez vos systèmes IA avec ces modes d'échec en tête dès le premier jour.",

  "slide-60": "L'EU AI Act de l'Union Européenne est la première loi IA complète et contraignante au monde, entrée en vigueur en août 2024. Elle utilise une approche à niveaux basée sur le risque. La plupart des applications tombent dans des catégories à risque minimal ou limité avec des exigences légères de transparence. Les applications à haut risque — celles qui affectent l'embauche, le crédit, les forces de l'ordre, l'accès à l'éducation ou les services essentiels — font face à des exigences strictes : documentation technique, supervision humaine, tests de précision et enregistrement dans la base de données de l'UE. La non-conformité risque des amendes allant jusqu'à trente-cinq millions d'euros ou sept pourcent du chiffre d'affaires annuel mondial. Si votre organisation déploie de l'IA dans n'importe quelle catégorie à haut risque dans l'UE, la conformité est une obligation légale.",

  "slide-61": "Les échecs IA réels nous apprennent plus sur le risque que tout scénario hypothétique. L'outil de recrutement interne d'Amazon, entraîné sur une décennie de CV tech dominés par des hommes, a systématiquement déclassé les candidatures féminines — il a été abandonné en 2018. COMPAS, un outil de prédiction de récidive utilisé dans les tribunaux américains, a été trouvé à signaler les accusés noirs comme à haut risque au double du taux par rapport aux accusés blancs comparables. Un avocat new-yorkais a déposé un mémoire juridique rempli de citations de cas générées par l'IA — chaque cas était fabriqué. Ces échecs partagent un pattern : la technologie a fonctionné exactement comme prévu. La gouvernance autour d'elle ne l'a pas fait.",

  "slide-62": "Deux autres cas documentés de 2023 et 2024 illustrent les enjeux. L'outil IA de pré-autorisation d'UnitedHealth a refusé la couverture des soins infirmiers pour les patients Medicare âgés avec un taux d'erreur de quatre-vingt-dix pourcent — annulant les recommandations des médecins pour des milliers de personnes. Le chatbot de service client d'Air Canada a créé une politique tarifaire de deuil fabriquée et l'a promise à un client en deuil ; la compagnie a été tenue légalement responsable de l'invention de l'IA. Les deux illustrent le même échec systémique : un système IA déployé dans un domaine conséquentiel sans supervision humaine adéquate ni voie d'escalade.",

  "slide-63": "Trois frameworks complémentaires donnent de la structure à la gouvernance IA aujourd'hui. Le NIST AI Risk Management Framework organise la gouvernance autour de quatre fonctions : Gouverner, Cartographier, Mesurer et Gérer — familier aux organisations qui utilisent déjà le NIST Cybersecurity Framework. ISO 42001, publié en décembre 2023, est la première norme certifiable de système de management IA ; il s'aligne avec ISO 27001, rendant simple l'extension des certifications de sécurité existantes pour couvrir l'IA. L'EU AI Act est la couche légale contraignante pour les opérations dans l'UE. Ensemble, ces trois frameworks donnent aux organisations un chemin structuré et auditable vers le déploiement IA responsable.",

  "slide-64": "L'IA responsable n'est pas une liste de contrôle ponctuelle — c'est une discipline continue. Avant de déployer tout système IA, documentez ce qu'il fait, sur quelles données il s'appuie, et quels dommages il pourrait causer à des groupes spécifiques d'utilisateurs. Testez-le avec des profils divers — ne supposez pas que parce que le système fonctionne pour un groupe démographique il fonctionne également pour tous. Faites du red-teaming délibérément : essayez de le tromper, poussez-le vers des modes d'échec, et testez les vulnérabilités d'injection de prompt. Intégrez la transparence dès le début — la rétrofitter est coûteux et souvent inadéquat. Et définissez des voies d'escalade claires pour quand le système produit des outputs nocifs ou incorrects en production. L'IA que vous pouvez expliquer et contrôler est l'IA en laquelle vous pouvez avoir confiance.",

  "slide-65": "Où va l'IA ? Certaines tendances sont déjà claires. Les fenêtres de contexte continuent de croître, permettant aux modèles de raisonner sur des codebases entiers et des collections de documents simultanément. Les modèles multimodaux traitent nativement texte, images, audio et vidéo. L'autonomie des agents s'étend, avec des systèmes IA gérant des workflows plus longs et plus complexes avec moins d'intervention humaine. Les coûts d'inférence continuent de baisser. Les rôles les plus à risque sont ceux qui peuvent être entièrement décrits comme un pattern répétable et bien spécifié. Les rôles qui croissent sont ceux qui nécessitent jugement, empathie, raisonnement éthique et créativité contextuelle. La meilleure préparation : restez curieux, construisez des choses, et développez une relation critique et informée avec ces outils.",

  "slide-66": "Les points clés du chapitre six. Le biais et l'hallucination ne sont pas des échecs aléatoires — ce sont des conséquences prévisibles de la façon dont ces systèmes sont entraînés. Chaque échec IA réel que nous avons examiné était évitable avec une gouvernance appropriée. L'EU AI Act crée des obligations légales pour les applications à haut risque en Europe, et les régulateurs dans le monde entier suivent son exemple. La pratique IA responsable — transparence, équité, supervision humaine et voies d'escalade claires — n'est pas du théâtre de conformité. C'est ce qui rend les systèmes IA suffisamment dignes de confiance pour être déployés à grande échelle.",

  "slide-67": "Les références clés du chapitre six. Le texte officiel de l'EU AI Act et la chronologie de mise en œuvre sont des lectures essentielles pour quiconque déploie de l'IA en Europe. Stochastic Parrots de Bender, Gebru et collègues est une analyse critique fondamentale des grands modèles de langage et des risques qu'ils portent. L'enquête COMPAS de ProPublica est une lecture obligatoire sur le biais algorithmique dans la justice pénale. La documentation NIST AI RMF et ISO 42001 fournit les frameworks de gouvernance discutés dans ce chapitre.",

  "slide-68": "Ce tableau vous donne une carte pratique de là où l'IA offre une valeur mesurable dans divers secteurs aujourd'hui. La finance utilise l'IA pour la détection de fraude, le scoring du crédit et le traitement de documents — tout en production dans les principales institutions. La santé l'applique à la synthèse des notes cliniques, à l'analyse des images radiologiques et à l'analyse des interactions médicamenteuses — avec supervision humaine sur toutes les décisions cliniques. Les cabinets juridiques utilisent l'IA pour la révision de contrats et la recherche de cas. Le secteur manufacturier l'applique à la maintenance prédictive et au contrôle qualité. Le retail l'utilise pour la personnalisation, les prévisions de la demande et l'optimisation de la chaîne d'approvisionnement. Le pattern dans tous les secteurs : l'IA gère le travail de reconnaissance de patterns à volume élevé pour que les humains puissent se concentrer sur le jugement et la gestion des exceptions.",

  /* ── CONCLUSION ──────────────────────────────────────────── */

  "conclusion": "Nous avons atteint la conclusion. Six chapitres — des mathématiques de l'attention des transformers à l'éthique des agents autonomes. Prenons un moment pour consolider les idées les plus importantes avant de clore.",

  "slide-70": "Voici le résumé des six chapitres. Chapitre un : les LLM sont des prédicteurs probabilistes de tokens — ils encodent des patterns statistiques, pas des faits, et l'échelle est ce qui a débloqué les capacités. Chapitre deux : le prompt engineering est l'art de communiquer avec précision — rôle, contexte, format et exemples améliorent drastiquement la qualité de l'output. Chapitre trois : le codage assisté par IA offre de réels gains de productivité mais amplifie toutes les compétences et habitudes que vous apportez. Chapitre quatre : le RAG connecte l'IA à vos données privées en récupérant des documents au moment de la requête — pas de ré-entraînement, toujours à jour. Chapitre cinq : les agents agissent — ils se déplacent en cycles reason-act-observe utilisant des outils pour accomplir des tâches multi-étapes de manière autonome. Chapitre six : l'IA responsable est une discipline d'ingénierie, pas une réflexion après coup.",

  "slide-71": "Quatre intuitions à emporter au-delà de ce cours. Première : les LLM sont des machines à patterns, pas des bases de données de faits. Ils prédisent le prochain token, pas la vérité. Vérifiez chaque output qui compte. Deuxième : les prompts sont des programmes. Les prompts structurés surpassent de manière cohérente les requêtes vagues — traitez le prompt engineering avec le même rigor que vous appliquez au code. Troisième : le contexte est tout. Ce que vous mettez dans la fenêtre de contexte — rôle, fond, exemples, contraintes — détermine la qualité de ce qui en sort. Quatrième : les systèmes IA ont besoin de gouvernance. Chaque déploiement à haut risque devrait avoir une piste d'audit claire, un chemin de substitution humaine et une évaluation régulière pour le biais et la précision.",

  "slide-72": "Voici les ressources que je recommande pour continuer ce parcours. Pour les fondamentaux : les cours courts de DeepLearning.AI d'Andrew Ng couvrent transformers, RAG et agents en quelques heures chacun. La série Zero to Hero d'Andrej Karpathy construit la compréhension des réseaux de neurones depuis zéro en code. Le cours NLP de HuggingFace est la meilleure introduction structurée à la bibliothèque transformer. Pour rester à jour : le podcast Latent Space couvre la recherche IA de pointe en profondeur, et la page HuggingFace Daily Papers suit les nouvelles publications dès leur publication. L'habitude la plus précieuse est la lecture curatée et cohérente — même trente minutes par semaine vous garde orienté dans ce domaine en rapide évolution.",

  "slide-73": "Nous avons atteint la fin de ce cours. L'intelligence artificielle est un outil extraordinaire — et comme tout outil puissant, sa valeur dépend entièrement de l'intention, du jugement et du soin des personnes qui l'utilisent. Les modèles continueront de s'améliorer. Les principes que nous avons couverts — ancrer les outputs, concevoir pour la supervision, tester les biais, intégrer la responsabilité nativement — resteront pertinents quelle que soit las systèmes spécifiques qui existent dans un an ou cinq. Restez curieux. Construisez des choses. Et si vous avez des questions en appliquant ces idées, je suis toujours joignable sur LinkedIn. Merci.",

  /* ── ANNEXE ──────────────────────────────────────────────── */

  "annex": "L'annexe est votre section de référence. Elle contient des diagrammes, des aide-mémoire et du matériel de support pour les six chapitres. Revenez à ces diapositives chaque fois que vous avez besoin d'une référence visuelle rapide ou d'un regard plus approfondi sur un concept spécifique.",

  "slide-75": "Cette visualisation montre le mécanisme d'auto-attention en action. Chaque ligne représente un token qui interroge tous les autres dans la phrase. Plus une cellule est lumineuse, plus le poids d'attention est fort — ce qui signifie que ces deux tokens sont étroitement liés dans la vue du modèle. Remarquez comment le mot il prête une forte attention à chat — le modèle a appris à résoudre les références pronominales sans règles grammaticales explicites. Ce comportement émerge entièrement de l'entraînement sur des milliards de phrases. Les transformers modernes exécutent plusieurs têtes d'attention en parallèle, chacune traçant différentes relations linguistiques : accord sujet-verbe, paires adjectif-nom et coréférence à longue portée.",

  "slide-76": "L'aide-mémoire des patterns de prompt engineering est votre fiche de référence pratique. Le pattern Role assigne une persona experte pour améliorer profondeur et style. Chain-of-Thought force le raisonnement étape par étape avant la réponse finale — essentiel pour les maths, la logique et les tâches multi-étapes. Few-Shot fournit des exemples déjà résolus pour démontrer le format exact dont vous avez besoin. Tree of Thought explore plusieurs chemins de raisonnement simultanément. Meta-Prompting demande au modèle de générer ou affiner un prompt pour une tâche donnée. Utilisez cette fiche comme liste de contrôle chaque fois que vous concevez un nouveau prompt pour une utilisation en production.",

  "slide-77": "Ce diagramme montre le cycle de vie complet d'une seule requête IA. Un utilisateur ou une application envoie un prompt. Le texte est tokenisé — converti en identifiants entiers à environ trois quarts de mot par token. Ces tokens traversent les couches d'attention et feed-forward du LLM, optionnellement augmentées par des appels d'outils ou une étape de récupération RAG. Le modèle génère des probabilités de tokens, échantillonne le prochain token et l'ajoute — en répétant jusqu'à la complétion. L'output revient à l'application, où il peut être analysé, validé et affiché. L'étape critique que la plupart des développeurs sous-estiment est la validation humaine : traitez l'output IA comme un brouillon sûr, pas une réponse définitive, dans tout contexte à enjeux élevés.",

  "slide-78": "La pile IA moderne a quatre niveaux. En haut, la couche applicative : l'interface de chat, l'application web ou la passerelle API avec laquelle les utilisateurs interagissent. En dessous, la couche d'orchestration : agents, planificateurs et logique de raisonnement multi-étapes implémentés avec LangGraph, AutoGen ou MCP. Puis la couche d'inférence : le modèle de langage lui-même, accessible via API gérée ou auto-hébergé pour la souveraineté des données. À la base, la couche de données : bases de données vectorielles, magasins de documents et sources de données structurées depuis lesquelles les pipelines RAG puisent. Comprendre dans quelle couche vit un problème aide à choisir la bonne solution et la bonne équipe pour le construire.",

  "slide-79": "En élargissant la vue à l'écosystème entier : en haut, utilisateurs et interfaces — UI de chat, plugins IDE, applications mobiles et consommateurs d'API. En dessous, la couche applicative gère le routage, le caching et la limitation de débit. Une couche de raisonnement où les agents décomposent les tâches et orchestrent les appels d'outils. Une couche d'inférence où le modèle de langage traite le contexte et génère du texte. Une couche de récupération pour le RAG — recherche vectorielle et magasins de documents. Et à la base, l'infrastructure : clusters GPU, fournisseurs cloud, surveillance et outils de conformité. Chaque couche est un point d'intégration potentiel, une opportunité d'optimisation et un point de contrôle de gouvernance.",

  "slide-80": "Le coût de l'IA est piloté par trois variables. Taille du modèle : les modèles plus grands coûtent de dix à cent fois plus par appel que les plus petits — GPT-4o mini ou Claude Haiku offrent la plupart des capacités à une fraction du coût de GPT-4o. Nombre de tokens : le prix est par token, et les tokens de sortie coûtent typiquement de trois à cinq fois plus que les tokens d'entrée. Fréquence des appels : même des coûts modestes par appel deviennent significatifs à grande échelle. Le conseil pratique : testez toujours d'abord les modèles plus petits sur votre tâche spécifique. Vous constaterez souvent qu'un modèle dix fois moins cher offre quatre-vingt-dix pourcent de la qualité dont vous avez besoin.",

  "slide-81": "Cette diapositive documente les fichiers sources de diagrammes PlantUML inclus dans ce dépôt. Chaque diagramme dans le cours a un fichier dot-puml correspondant dans le dossier diagrams, ainsi qu'un fichier dot-link pointant vers la version rendue. Les diagrammes couvrent l'architecture du transformer, le cycle de vie complet des LLM, l'écosystème des agents IA, le flux du pipeline RAG, le workflow de développement assisté par IA et plus encore. Si vous voulez adapter un diagramme pour vos présentations : forkez le dépôt, modifiez le source dot-puml et régénérez. PlantUML vous donne des diagrammes textuels avec contrôle de version qui se mettent à jour proprement quand le contenu change.",

  "slide-82": "HuggingFace est aux modèles IA ce que GitHub est au code source — le dépôt central où les chercheurs publient les poids et les développeurs les téléchargent. La bibliothèque Transformers fournit une API Python cohérente qui fonctionne pour toutes les principales architectures, donc changer de modèle est une modification d'une ligne. GGUF est un format de fichier qui empaquette les poids du modèle et les métadonnées d'architecture dans un seul fichier autonome, introduit en 2023 comme standard de distribution locale portable. La quantization réduit la précision numérique des poids du modèle — des floats 32 bits aux entiers 4 bits — rendant les modèles environ quatre fois plus petits avec une perte de qualité minimale. La variante Q4-K-M est largement considérée comme le meilleur compromis taille-qualité pour une utilisation locale.",

  "slide-83": "Exécuter des modèles de langage localement — sur votre propre matériel, sans dépendance au cloud — est de plus en plus pratique. Ollama est le point de départ le plus simple : il enveloppe les modèles locaux dans une API REST compatible OpenAI sur le port 11434, donc vous passez du cloud au local en changeant une seule URL. LM Studio fournit une interface desktop soignée avec un navigateur de modèles intégré. LLaMA dot cpp est le moteur d'inférence sous-jacent écrit en C++, supportant l'accélération CPU et GPU sur toutes les plateformes. La contrainte principale est la RAM : un modèle à sept milliards de paramètres en quantization 4 bits nécessite environ quatre gigaoctets — la plupart des laptops modernes peuvent le gérer. Les Mac Apple silicon sont particulièrement adaptés car leur mémoire unifiée sert à la fois les charges de travail CPU et GPU."

};
