/* ═══════════════════════════════════════════════════════════
   SPEAKER NOTES — Italiano
   Stile voice-over — parlato direttamente all'ascoltatore.
   Key = id della slide  o  "slide-{index}" per slide senza id.
   ═══════════════════════════════════════════════════════════ */
window.NOTES_IT = {

  /* ── PREFAZIO ────────────────────────────────────────────── */

  "slide-0": "Benvenuti a Capire l'Intelligenza Artificiale — un percorso pratico dalle fondamenta agli agenti autonomi. Questo corso è pensato per sviluppatori, architetti, product manager e chiunque voglia capire davvero come funziona l'AI moderna. Copriamo sei capitoli, ognuno costruito sul precedente, così arriverete con una visione coerente invece di buzzword scollegate. Potete cambiare lingua in qualsiasi momento dal menu in alto. Cominciamo.",

  "slide-1": "Prima di iniziare, un breve orientamento. Usate le frecce o scorrete per navigare tra le slide. Il pulsante del menu apre il navigatore dei capitoli per saltare a qualsiasi sezione. Ogni capitolo termina con una slide di riferimenti per approfondire. Le slide interattive — quelle con animazioni o slider — sono autonome: basta seguire le istruzioni sullo schermo. Il materiale è disponibile in inglese, italiano, francese e spagnolo — cambiate lingua quando volete dal menu in alto.",

  "agenda": "Ecco cosa copriremo insieme. Sei capitoli, ognuno costruito sul precedente. Il capitolo uno stabilisce le basi: cos'è davvero l'AI, come funzionano i transformer e cosa significano tutti quei parametri. Il capitolo due riguarda il prompt engineering — l'arte di comunicare con precisione con i modelli AI. Il capitolo tre copre il coding assistito da AI, dall'autocompletamento agli strumenti agentici. Il capitolo quattro spiega il Retrieval-Augmented Generation — come connettere l'AI ai vostri dati privati. Il capitolo cinque esplora gli agenti AI autonomi e il Model Context Protocol. Il capitolo sei affronta etica, bias e governance. L'annesso contiene materiale di riferimento a cui tornare in qualsiasi momento.",

  /* ── CAPITOLO 1 ──────────────────────────────────────────── */

  "chapter-1": "Il capitolo uno pone le basi concettuali per tutto ciò che segue. L'idea più importante è questa: l'intelligenza artificiale non è magia — è matematica applicata a enormi quantità di dati. Passeremo dai sistemi deterministici, come un classico programma if-then che fornisce sempre la stessa risposta, a quelli probabilistici, dove il modello fa la sua migliore previsione basandosi su pattern appresi da miliardi di esempi. Alla fine di questo capitolo, capirete come funziona una rete neurale transformer, cosa significano davvero temperatura e token, e perché l'hardware specializzato è importante.",

  "slide-4": "La distinzione più fondamentale nell'AI moderna è il passaggio dal calcolo deterministico a quello probabilistico. Il software tradizionale è deterministico: dando lo stesso input ottieni sempre lo stesso output. I modelli linguistici sono probabilistici: alla stessa domanda possono rispondere in modo diverso ogni volta. Non è un difetto — è by design. Il modello non cerca una risposta fissa. Invece, campiona da una distribuzione di probabilità sulle possibili parole successive. Il parametro temperatura controlla quanto sia stretta o ampia quella distribuzione. Questo passaggio — dalla correttezza garantita alla verosimiglianza ottimizzata — è il modello mentale su cui si basa tutto il resto del corso.",

  "slide-5": "Ci sono effettivamente due ere nella storia dell'AI moderna: tutto prima del 2017, e tutto dopo. Prima del 2017, l'approccio dominante erano le reti neurali ricorrenti, che elaboravano il testo una parola alla volta e tendevano a dimenticare il contesto oltre qualche frase. Nel 2017, un team di Google pubblicò un paper intitolato Attention Is All You Need, introducendo l'architettura transformer. L'innovazione chiave: ogni parola in una frase può riferirsi direttamente a ogni altra parola simultaneamente, indipendentemente dalla distanza. Quella singola intuizione ha sbloccato un salto di capacità. Nel 2020, GPT-3 ha dimostrato che scalare questa architettura con abbastanza dati e calcolo produce un modello capace di apprendere nuovi compiti da pochi esempi — senza addestramento aggiuntivo.",

  "slide-6": "Tre forze si sono convergite tra il 2017 e il 2023 per accelerare l'AI oltre ogni aspettativa precedente. Prima, i dati: internet ha prodotto testo su scala senza precedenti — CommonCrawl, Wikipedia, GitHub e miliardi di libri digitalizzati hanno fornito il materiale grezzo di addestramento. Seconda, il calcolo: le GPU sono evolute da hardware per giochi in motori di calcolo massicciamente parallelo capaci di addestrare modelli con centinaia di miliardi di parametri. Terza, l'architettura transformer stessa: poteva essere addestrata in modo molto più efficiente degli approcci precedenti, e la sua capacità scalava in modo prevedibile con più dati e calcolo. Quando queste tre forze si sono combinate, il progresso che una volta richiedeva un decennio ha cominciato ad avvenire in mesi.",

  "slide-7": "Questa animazione mostra cosa succede davvero quando un modello linguistico genera testo. Ogni passo avanza produce esattamente un token. Notate le barre di probabilità: il modello non è mai certo di quale parola viene dopo. Mantiene una distribuzione completa di possibilità e ne campiona. Quando la temperatura è sopra zero, i token a bassa probabilità hanno ancora una chance di essere selezionati — ecco perché generare lo stesso prompt due volte può produrre risultati diversi. Questo spiega anche perché i modelli linguistici trasmettono l'output token per token invece di restituire una risposta completa istantaneamente: calcolano letteralmente il testo un token alla volta.",

  "slide-8": "Tracciamo il percorso che un pezzo di testo compie attraverso un transformer. Prima, il testo grezzo viene diviso in token — piccoli frammenti di caratteri. Ogni token viene convertito in un embedding: un vettore di numeri che codifica il suo significato in uno spazio ad alta dimensione. Questi embedding passano poi attraverso il meccanismo di auto-attenzione — il cuore del transformer. Qui, ogni token esamina ogni altro token e decide quanto peso attribuirgli. È così che il modello risolve che 'esso' si riferisce a 'gatto' diverse parole indietro, senza regole esplicite. Dopo l'attenzione, il risultato passa attraverso layer feed-forward, e infine il modello produce una distribuzione di probabilità sul prossimo token possibile. Questo intero processo si ripete per ogni singolo token generato.",

  "slide-03a": "Questa slide illustra la pipeline di campionamento completa — il percorso dall'input testuale a un singolo token generato. Gli embedding convertono ogni token in un vettore ad alta dimensione. L'auto-attenzione permette a ogni token di riferirsi a tutti gli altri. I layer feed-forward applicano una trasformazione non lineare appresa. Il softmax converte i punteggi grezzi in una distribuzione di probabilità sul vocabolario intero. Infine, il passo di campionamento estrae il prossimo token da quella distribuzione, modulata da temperatura e Top-P. Capire questa pipeline aiuta a ragionare sul perché le scelte di parametri hanno gli effetti che hanno sull'output del modello.",

  "slide-10": "Capire i parametri chiave di generazione è essenziale per lavorare con qualsiasi modello AI. La temperatura è la più importante: a zero, il modello sceglie sempre il token a probabilità più alta, producendo output deterministico e riproducibile. Sopra zero, i token a bassa probabilità hanno una chance — aumentando la creatività ma anche l'imprevedibilità. Per la generazione di codice e l'estrazione di dati, mantenete bassa la temperatura. Per il brainstorming, alzatela. Un token è circa tre quarti di una parola italiana — e l'unità su cui viene calcolata la vostra fattura API. Max token limita la lunghezza della risposta e il costo per chiamata. Top-P controlla la dimensione del pool di candidati. Cambiate questi parametri uno alla volta, perché interagiscono.",

  "slide-11": "Tre limitazioni pratiche sono più importanti quando si costruiscono applicazioni AI nel mondo reale. Prima, i modelli linguistici non hanno memoria persistente: ogni conversazione inizia da zero, senza ricordo di nulla detto prima. Se la continuità è importante, dovete iniettare la cronologia rilevante nel prompt voi stessi. Seconda, le finestre di contesto sono finite: ogni modello ha una lunghezza massima di input, e i contenuti oltre quel limite vengono semplicemente tagliati. Terza, le allucinazioni sono intrinseche: i modelli possono produrre output factualmente errati ma fluenti e sicuri su argomenti fuori dalla loro distribuzione di addestramento. Capire questi vincoli in anticipo previene una categoria di sorprese in produzione.",

  "slide-12": "Perché i modelli AI richiedono hardware così specializzato? Al loro nucleo, i layer delle reti neurali sono enormi moltiplicazioni matriciali — moltiplicare array con miliardi di numeri simultaneamente. Le GPU sono state originariamente costruite per il rendering grafico, che comporta esattamente questo tipo di calcolo altamente parallelo. Una moderna GPU H100 ha ottanta gigabyte di memoria ad alta larghezza di banda ed elabora migliaia di operazioni in parallelo. I cloud provider come Azure, AWS e Google Cloud espongono queste capacità come API, quindi pagate per token invece di acquistare hardware. La curva dei costi è drammatica: il costo di inferenza scende circa dieci volte all'anno — ecco perché eseguire modelli capaci localmente è già pratico oggi.",

  "slide-13": "Una delle proprietà più sorprendenti dei moderni modelli linguistici di grandi dimensioni è la loro generalità. Ogni compito in questo word cloud — analisi del sentiment, traduzione, riassunto, generazione di codice, riconoscimento di entità nominate, classificazione, risposta a domande e decine di altri — può essere gestito da un singolo modello di fondazione. Prima del 2020, ognuno di questi compiti richiedeva un modello dedicato, appositamente addestrato. Oggi, un solo modello li gestisce tutti. L'implicazione è profonda: il costo marginale di provare un nuovo caso d'uso AI è ora essenzialmente zero, perché si riutilizza lo stesso modello.",

  "slide-14": "Il panorama dei modelli AI cambia ogni tre-sei mesi circa, quindi trattate questa tabella come uno snapshot. Dimensioni chiave nella scelta di un modello: capacità per il vostro compito specifico, dimensione della finestra di contesto, costo per token, se è open-weight o proprietario, e dove gira l'inferenza per la compliance. Gemini 2.0 guida sulla finestra di contesto con oltre un milione di token. Llama 3 e Mistral sono open-weight e possono essere self-hosted — importante per la sovranità dei dati. GPT-4o mini offre la maggior parte della qualità di GPT-4o completo a una frazione del costo. La vostra scelta dipende da compito, budget, latenza e requisiti di compliance.",

  "slide-15": "Ogni modello linguistico ha modalità di fallimento prevedibili che dovreste conoscere prima di distribuirlo. L'allucinazione è la più pericolosa: il modello genera testo che suona fluente e sicuro ma è fattualmente errato — senza alcun segnale visibile di incertezza. Il knowledge cutoff significa che il modello non sa nulla degli eventi dopo la fine dei suoi dati di addestramento. Il ragionamento matematico non è affidabile — i modelli spesso sbagliano l'aritmetica in modi che sembrano sorprendenti dato le altre loro capacità. E il bias: poiché i modelli imparano pattern da testo generato da esseri umani, riflettono i pregiudizi in quel testo. Nessuno di questi è un bug che verrà fixato — sono proprietà fondamentali dell'architettura attuale. Progettate il vostro sistema di conseguenza.",

  "ai-system-architecture": "Questo diagramma mostra l'architettura a strati completa di un moderno sistema AI. In cima ci sono gli attori: l'utente finale che invia query, lo sviluppatore che costruisce e monitora il sistema, e qualsiasi servizio esterno o API. Le richieste scendono attraverso un layer applicativo che gestisce autenticazione, rate limiting e contesto della conversazione. Sotto si trova il layer di integrazione AI: costruzione del prompt, recupero opzionale da un database vettoriale per RAG, e la chiamata al modello linguistico. La risposta risale attraverso gli stessi layer. Ogni layer è un'opportunità per aggiungere controlli di sicurezza, logging e controllo — ecco perché i sistemi AI ben progettati sono costruiti a strati invece che come connessione diretta utente-modello.",

  "slide-17": "Consolidiamo le idee chiave del capitolo uno. Gli LLM sono probabilistici, non deterministici: la stessa domanda può produrre risposte diverse, ed è by design. I transformer hanno reso possibile questo elaborando intere sequenze simultaneamente attraverso l'auto-attenzione. Temperatura e limiti di token sono i controlli principali che userete in ogni integrazione. Le finestre di contesto definiscono la massima informazione su cui un modello può ragionare in una chiamata. E tutte le capacità — traduzione, codice, riassunto, ragionamento — emergono da un singolo obiettivo di pre-addestramento: prevedere il prossimo token. Questa è la fondazione su cui si basa tutto il resto del corso.",

  "slide-18": "Chiudiamo il capitolo uno con i riferimenti fondamentali. Il paper che ha dato inizio a tutto è Attention Is All You Need di Vaswani e colleghi, pubblicato da Google nel 2017 — ha introdotto l'architettura transformer che è alla base di ogni moderno modello linguistico. Il paper GPT-3 di OpenAI nel 2020 ha mostrato che scalare i transformer sblocca il few-shot learning — la capacità di eseguire nuovi compiti da pochi esempi nel prompt. Per un'ottima spiegazione visiva di come funziona l'attenzione, The Illustrated Transformer di Jay Alammar è altamente raccomandato e disponibile gratuitamente online.",

  /* ── CAPITOLO 2 ──────────────────────────────────────────── */

  "chapter-2": "Il capitolo due è dove la teoria diventa pratica. Il prompt engineering è la disciplina di comunicare con precisione con i modelli AI. Come si formula una richiesta ha un enorme effetto sulla qualità della risposta — e ci sono pattern ripetibili che migliorano in modo affidabile i risultati. Analizzeremo l'anatomia di un buon prompt, impareremo sei pattern collaudati dallo zero-shot al chain-of-thought, e vedremo riscritture reali prima-dopo. Queste competenze si applicano a ogni modello AI, non solo a quelli disponibili oggi.",

  "slide-20": "Un prompt ben strutturato ha quattro strati, e capire ognuno sblocca risultati significativamente migliori. In cima c'è il system prompt: dove definite il ruolo, i vincoli e la persona del modello. Una semplice istruzione come sei un senior data engineer specializzato in Python sposta in modo misurabile lo stile e la profondità della risposta. Poi il contesto: le informazioni di background rilevanti di cui il modello ha bisogno. Poi arriva il messaggio utente — il compito o la domanda effettiva. Infine, le istruzioni sul formato di output: dite esplicitamente al modello se volete JSON, un elenco numerato, un paragrafo o una tabella. Il modello non conosce i vostri requisiti downstream a meno che non li specifichiate.",

  "slide-21": "Tre pattern fondamentali di prompting coprono la vasta maggioranza dei casi d'uso. Zero-shot: descrivete il compito direttamente, senza esempi — i moderni modelli gestiscono la maggior parte dei compiti in questo modo. Few-shot: fornite da due a cinque esempi input-output che dimostrano il formato e lo stile che volete — particolarmente efficace per output strutturato e coerente. Chain-of-thought: chiedete al modello di ragionare passo dopo passo prima di dare la risposta finale — questo migliora drasticamente l'accuratezza su compiti matematici, logici e multi-step. Questi pattern si combinano naturalmente: un system prompt più esempi few-shot più chain-of-thought è una delle architetture di prompt più affidabili in produzione.",

  "slide-22": "Oltre alle basi, diversi pattern avanzati estendono ciò che il prompting può raggiungere. I system prompt definiscono la persona, le regole e le guardrail del modello — gli utenti non li vedono mai, ma plasmano ogni risposta. Il role playing assegna una specifica persona esperta per migliorare la profondità dell'output. Il Retrieval-Augmented Generation inietta documenti pertinenti recuperati da una knowledge base nel prompt prima della generazione — trattato in dettaglio nel capitolo quattro. Il tool use permette al modello di richiedere l'esecuzione di funzioni esterne — la base degli agenti nel capitolo cinque. Queste tecniche sono particolarmente preziose quando si costruiscono sistemi AI in produzione.",

  "slide-23": "L'errore più comune quando si lavora con l'AI è scrivere prompt vaghi. Confrontate riassumi questo documento con riassumi questo documento in esattamente tre punti elenco per un dirigente non tecnico, usando italiano semplice, senza gergo, massimo quindici parole per punto. Il secondo produce in modo coerente output migliore e più utilizzabile. Linee guida chiave: assegnate sempre un ruolo nel system prompt; esprimete i vincoli positivamente — dite cosa volete, non cosa non volete; siate espliciti su lunghezza e formato; e includete un esempio quando lo stile di output desiderato non è ovvio. Testate qualsiasi prompt su almeno dieci input diversi prima di mandarlo in produzione.",

  "slide-24": "Il prompt makeover è uno dei modi più efficaci per costruire intuizione. Prendete un prompt mediocre e applicatevi una riscrittura strutturata: aggiungete un ruolo chiaro, specificate il formato di output, aggiungete vincoli, includete un esempio. Il pattern è notevolmente coerente: il prima-prompt ingenuo produce output generico, spesso inutilizzabile; il dopo-prompt ingegnerizzato produce qualcosa di specifico, strutturato e pronto all'uso. Il divario tra loro non è il modello — è la qualità dell'istruzione. Un modello mentale utile: pensate a un prompt come a un programma che state scrivendo per un interprete molto capace ma estremamente letterale.",

  "slide-25": "Vediamo come gli stessi principi di prompting si applicano in diversi ruoli professionali. Un manager potrebbe chiedere all'AI di riassumere un rapporto di venti pagine in cinque punti elenco adatti a un pubblico non tecnico. Uno sviluppatore potrebbe chiederle di scrivere un test unitario per una funzione specifica con requisiti di copertura precisi. Un analista dati potrebbe richiedere uno script Python che ingerisce un CSV, calcola statistiche riassuntive e segnala i valori anomali. Il pattern è lo stesso in ogni caso: indicare il ruolo, fornire contesto, specificare il formato. Il valore non sta nell'AI che fa il vostro pensiero — ma nell'occuparsi del lavoro meccanico di produzione così che possiate concentrarvi sul giudizio.",

  "slide-26": "Questo playground interattivo vi permette di esplorare come i parametri di generazione influenzano l'output in tempo reale. Impostate la temperatura a zero e generate lo stesso prompt due volte — otterrete risultati identici ogni volta. Aumentate gradualmente la temperatura e osservate come l'output si diversifica. Top-P controlla il pool di candidati: un valore basso limita il modello ai token più probabili; un valore alto apre territori più creativi. Queste non sono impostazioni astratte — controllano direttamente il compromesso coerenza-creatività nella vostra applicazione. Le applicazioni rivolte ai clienti che necessitano di risposte affidabili beneficiano di bassa temperatura. Gli strumenti creativi beneficiano di alta temperatura.",

  "slide-27": "Ora è il vostro turno di praticare. Prendete un compito reale — scrivere una descrizione del lavoro, analizzare un dataset, redigere una proposta tecnica — e scrivete un prompt iniziale. Eseguitelo, vedete cosa ottenete, poi miglioratelo sistematicamente: aggiungete un ruolo, aggiungete istruzioni sul formato, aggiungete un esempio. Confrontate l'output di ogni iterazione con quello precedente. Scoprirete che ogni perfezionamento fa una differenza significativa. L'obiettivo non è la perfezione al primo tentativo — è costruire il muscolo iterativo di generare, valutare criticamente, perfezionare e ripetere. Questo ciclo è la competenza fondamentale del prompt engineering efficace.",

  "slide-28": "I punti chiave del capitolo due. Ogni prompt efficace ha quattro parti: ruolo, contesto, compito e formato. Mancarne uno e la qualità ne risente. I pattern di prompting — zero-shot, few-shot, chain-of-thought — sono combinabili: usateli insieme per requisiti complessi. Le tecniche avanzate come i system prompt e l'output strutturato estendono il prompting in territorio architetturale. E ricordate: un prompt è un programma. Tratatelo come codice — versionatelo, testatelo su input diversi e perfezionatelo iterativamente.",

  "slide-29": "I riferimenti chiave del capitolo due. Anthropic e OpenAI pubblicano entrambe guide dettagliate di prompt engineering che riflettono le migliori pratiche più recenti per i loro modelli. Il paper Chain-of-Thought Prompting di Wei e colleghi ha stabilito perché ragionare passo dopo passo migliora drasticamente le prestazioni su compiti complessi. Il sito promptingguide.ai e il corso Learn Prompting sono eccellenti risorse strutturate per costruire queste competenze da zero.",

  /* ── CAPITOLO 3 ──────────────────────────────────────────── */

  "chapter-3": "Il capitolo tre riguarda cosa succede quando l'AI diventa il vostro partner di coding. Copriremo l'intero spettro: dal semplice autocompletamento, agli assistenti di scrittura del codice conversazionali, agli strumenti completamente agentici che comprendono l'intero codebase e apportano modifiche autonome a più file. C'è un reale, misurabile vantaggio di produttività — supportato da studi controllati. Ci sono anche rischi reali quando questi strumenti vengono usati senza capire cosa producono. Guarderemo entrambi i lati onestamente.",

  "slide-31": "Nel febbraio 2025, il ricercatore AI Andrej Karpathy ha coniato la frase vibe coding per descrivere un nuovo modo di scrivere software. Descrivete cosa volete in linguaggio naturale, l'AI genera il codice, lo eseguite, osservate cosa si rompe e descrivete la correzione. Non necessariamente leggete ogni riga prima di metterlo in produzione. Gli sviluppatori che abbracciano questo ciclo di iterazione rapida riferiscono di lavorare da tre a cinque volte più velocemente su compiti ben definiti. Ma c'è un avvertimento critico: il vibe coding amplifica le vostre competenze esistenti — non sostituisce la comprensione. Se non potete valutare se il codice è corretto e sicuro, non catturerete gli errori che l'AI fa con sicurezza.",

  "slide-32": "Il workflow di sviluppo assistito da AI segue un ciclo chiaro: descrivete il compito con precisione, generate codice, revisionate criticamente, eseguitelo, identificate cosa c'è di sbagliato e perfezionate. La parola da enfatizzare è criticamente. Gli strumenti AI eccellono nella generazione di boilerplate, scaffolding, test unitari e trasformazioni ben specificate. Faticano con la logica di business implicita, il codice sensibile alla sicurezza e qualsiasi cosa che richieda una conoscenza contestuale profonda del vostro codebase. Strumenti come Cursor e Windsurf riducono l'attrito con viste diff inline e modifica multi-file. I migliori professionisti hanno ridotto questo ciclo di iterazione a meno di due minuti per modifica.",

  "slide-33": "Il panorama degli strumenti di coding AI ha tre livelli. Assistenti integrati nell'IDE: GitHub Copilot con la più ampia adozione enterprise; Cursor, popolare tra le startup per la sua modalità composer multi-file; e Windsurf, che eccelle nella consapevolezza di codebase di grandi dimensioni. Agenti completamente autonomi come Devin possono ricevere un compito, sfogliare la documentazione, scrivere codice, eseguire test e fare commit con minima interazione umana. Il fattore differenziante nella valutazione degli strumenti è il contesto del codebase: quanta parte del vostro codice esistente lo strumento può tenere in contesto contemporaneamente. Più contesto significa suggerimenti più accurati e contestualmente appropriati.",

  "slide-34": "Gli strumenti di coding AI funzionano meglio su problemi ben definiti e autonomi: API CRUD, test unitari, script di trasformazione dati, file di configurazione, espressioni regolari, layout CSS e documentazione. Dove faticano in modo coerente: logica di business complessa con vincoli non dichiarati, codice critico per la sicurezza dove un errore sottile è sfruttabile, e codebase legacy dove anni di decisioni vivono in convenzioni non documentate. La regola d'oro: più chiara è la vostra specifica, migliore è l'output. L'AI amplifica la qualità del vostro pensiero — non lo sostituisce.",

  "slide-35": "I guadagni di produttività dagli strumenti di coding AI sono reali e misurabili. Uno studio controllato randomizzato di GitHub e Microsoft nel 2022 ha trovato che gli sviluppatori usando Copilot completavano un compito di server HTTP il cinquantacinque percento più velocemente. Il rapporto GitHub Octoverse 2024 ha trovato che Copilot genera in media il quarantasei percento del codice nei file in cui è abilitato. Il Developer Survey di Stack Overflow ha mostrato che il settantasei percento degli sviluppatori sta già usando o pianifica di adottare strumenti di coding AI. Per i senior developer, il ruolo si sta spostando: dalla scrittura di singole funzioni verso decisioni architetturali, revisione rigorosa dell'output AI, e ingegnerizzazione delle specifiche precise che dirigono l'AI efficacemente.",

  "slide-36": "Questo esercizio riguarda il processo, non solo il risultato. Prendete qualsiasi file CSV e usate uno strumento di coding AI per scrivere uno script di analisi: statistiche riassuntive, rilevamento dei valori anomali e una semplice visualizzazione. Prestate attenzione a dove l'AI fa assunzioni senza chiedere — tipi di colonne, gestione dei valori mancanti, formato di output. Notate cosa sbaglia la prima volta. Praticate il ciclo: generate, revisionate criticamente, testate e perfezionate. Alla fine avrete uno script funzionante e un'intuizione concreta di esattamente dove l'assistenza AI aggiunge valore e dove il vostro giudizio rimane indispensabile.",

  "slide-37": "I punti chiave del capitolo tre. Gli strumenti di coding AI offrono guadagni di produttività reali — dal trentacinque al cinquantacinque percento su compiti ben definiti, supportati da studi controllati. Ma l'amplificazione funziona in entrambe le direzioni: le buone pratiche vengono scale up, e quelle scadenti pure. Revisionate sempre criticamente il codice generato dall'AI — non solo per la correttezza ma per sicurezza, casi limite e manutenibilità. Il ruolo emergente non è prompter ma AI-enabled engineer: qualcuno che specifica l'intento con precisione, valuta l'output AI rigorosamente e lo integra in modo sicuro in un sistema più grande.",

  "slide-38": "I riferimenti del capitolo tre. Il post originale sul vibe-coding di Karpathy definisce la filosofia di questo nuovo modo di sviluppo. Lo studio Kalliamvakou è la misura accademica più rigorosa dell'impatto sulla produttività di Copilot. Il rapporto GitHub Octoverse 2024 fornisce statistiche sull'adozione a livello industriale. La documentazione di Cursor vale la pena esplorare come esempio concreto di come appare un IDE nativo AI oltre un tradizionale plugin.",

  /* ── CAPITOLO 4 ──────────────────────────────────────────── */

  "chapter-4": "Il capitolo quattro affronta una delle limitazioni più importanti dei modelli linguistici in produzione: non conoscono i vostri dati privati, e il loro addestramento ha un cutoff di conoscenza fisso. Il Retrieval-Augmented Generation — RAG — è la soluzione, ed è l'architettura AI più ampiamente distribuita nel software enterprise oggi. Capire il RAG è ciò che separa chi usa l'AI da chi ci costruisce sopra. Copriremo la pipeline completa: indicizzazione dei documenti, embedding, ricerca vettoriale, recupero e generazione basata su fonti.",

  "slide-40": "Perché non semplicemente fare fine-tune del modello sui vostri documenti interni? Tre ragioni: il fine-tuning è costoso, richiede giorni o settimane, e — soprattutto — i fatti cambiano. Quando un documento viene aggiornato, dovreste ri-addestrare l'intero modello. Il RAG adotta un approccio fondamentalmente diverso: invece di incorporare la conoscenza nei pesi del modello, recupera le informazioni rilevanti al momento della query e le inietta direttamente nel prompt. Pensate a darlo al modello un motore di ricerca e diritti copia-incolla prima che risponda — legge i documenti recuperati, poi risponde. Questo rende il RAG più economico, più veloce da aggiornare, più verificabile e più controllabile del fine-tuning per qualsiasi informazione che cambia nel tempo.",

  "slide-41": "La pipeline RAG ha due fasi distinte. La prima è l'indicizzazione, che avviene una volta o periodicamente: i documenti vengono divisi in chunk, ogni chunk viene convertito in un vettore embedding, e quei vettori vengono memorizzati in un database vettoriale. La seconda è la query, che avviene su ogni richiesta utente: la domanda viene embedded usando lo stesso modello, il database vettoriale trova i chunk più vicini, quei chunk vengono iniettati nel prompt come contesto, e il modello linguistico genera una risposta basata su fonti. La qualità di ogni passo — strategia di chunking, modello embedding, profondità di recupero — determina la qualità della risposta finale.",

  "slide-42": "Ecco l'intuizione dietro gli embedding. Immaginate di posizionare ogni pezzo di testo in uno spazio ad alta dimensione dove i testi semanticamente simili atterrano vicini. 'Il fatturato è diminuito nell'ultimo trimestre' e 'le vendite sono calate nel Q3' sarebbero molto vicini, anche se non condividono parole. 'Fatturato' e 'cucciolo' sarebbero lontani. Un database vettoriale è un indice ottimizzato per trovare i vicini più prossimi in questo spazio ad alta velocità, usando algoritmi come HNSW che evitano il confronto di ogni coppia di vettori. Per la maggior parte delle organizzazioni, pgvector — un'estensione PostgreSQL — è il punto di partenza pragmatico. Pinecone e Weaviate sono database vettoriali dedicati adatti a distribuzioni su larga scala.",

  "slide-43": "Come dividete i documenti in chunk ha un impatto maggiore sulla qualità RAG rispetto a quasi qualsiasi altra decisione — incluso quale modello linguistico usate. La divisione ricorsiva per caratteri cerca di dividere su paragrafo, frase, poi confini di parola — un buon default. Il chunking semantico usa la similarità di embedding tra frasi adiacenti per trovare confini naturali di argomento — più costoso ma preserva meglio il significato. L'indicizzazione gerarchica memorizza sia chunk padre che figlio: il recupero usa chunk figlio per la precisione, ma fornisce il chunk padre al modello per un contesto più completo. Per la maggior parte dei contenuti, una dimensione di chunk da cinquecento a mille token con overlap del dieci-venti percento è un punto di partenza affidabile.",

  "slide-44": "Questo esempio prima-dopo rende concreto ciò che è in gioco con il chunking. La query è: qual è la politica di congedo parentale per i genitori adottivi? Se il manuale HR viene diviso meccanicamente ogni cinquecento caratteri, il testo della policy rilevante potrebbe essere diviso tra due chunk — nessuno dei quali si classifica alto in una ricerca vettoriale perché ogni chunk da solo è incompleto. Con il chunking semantico — dividendo ai confini naturali dell'argomento — l'intera sezione sul congedo parentale rimane insieme, viene recuperata chiaramente e produce una risposta corretta e completa. La dimensione del chunk e l'overlap non sono dettagli di configurazione. Sono decisioni architetturali che determinano direttamente se il vostro sistema RAG funziona.",

  "slide-45": "Il RAG è l'architettura AI numero uno in produzione nel 2025, risolvendo tre problemi critici contemporaneamente. Radica le risposte del modello in documenti sorgente verificabili, trasformando un modello black-box in un assistente trasparente che può citare le sue fonti. Elimina i problemi di knowledge cutoff — aggiornate il vostro indice documentale e la conoscenza effettiva del modello si aggiorna immediatamente, senza ri-addestramento. E rende l'AI auditabile: nei settori regolamentati, tracciare ogni affermazione a un documento sorgente è spesso un requisito di compliance. Le applicazioni comuni includono knowledge base interne, Q&A su documentazione tecnica, ricerca legale e di compliance, e supporto clienti con accesso a informazioni live sui prodotti.",

  "slide-46": "Per questo esercizio architetturale, progettate un sistema RAG per un caso d'uso reale che vi interessa. Lavorate su ogni decisione: quali sono i vostri documenti sorgente, e con quale frequenza cambiano? Quale dimensione di chunk e overlap ha senso per questo tipo di contenuto? Quali metadati dovrebbero accompagnare ogni chunk per abilitare il filtraggio per data, autore o livello di accesso? Come gestite i documenti sensibili che non dovrebbero essere ampiamente recuperabili? E come istruite il modello a dire non lo so quando il contesto recuperato non risponde alla domanda — piuttosto che allucinare? Prendere queste decisioni in anticipo risparmia un enorme tempo di debug in seguito.",

  "slide-47": "I punti chiave del capitolo quattro. Il RAG risolve il problema della conoscenza congelata recuperando documenti rilevanti al momento della query — nessun ri-addestramento necessario, sempre aggiornato. La strategia di chunking e la scelta del modello embedding hanno più impatto sulla qualità rispetto alla scelta del modello linguistico. Includete sempre un filtro sui metadati e un'istruzione esplicita per il modello di riconoscere quando mancano informazioni rilevanti. E il RAG rende l'AI auditabile: ogni risposta può essere tracciata a un documento sorgente, che è spesso un requisito di compliance nei settori regolamentati.",

  "slide-48": "I riferimenti chiave del capitolo quattro. Il paper RAG originale di Lewis e colleghi, pubblicato nel 2020, ha mostrato risultati all'avanguardia sul question answering a dominio aperto. LlamaIndex e LangChain sono i due principali framework open-source per costruire pipeline RAG in produzione — entrambi hanno un'ottima documentazione. Il survey del 2023 di Gao e colleghi fornisce una mappa completa delle varianti RAG naive, avanzate e modulari, con una chiara valutazione di quando ogni approccio è più efficace.",

  /* ── CAPITOLO 5 ──────────────────────────────────────────── */

  "chapter-5": "Il capitolo cinque passa dal modello all'agente. Finora abbiamo parlato di modelli che rispondono: voi chiedete, loro rispondono. Un agente AI è diverso — agisce. Può navigare sul web, chiamare API, scrivere ed eseguire codice, interrogare database e inviare email — autonomamente, concatenando più decisioni senza un essere umano nel loop per ogni passo. Questo passaggio dalla risposta all'azione è uno degli sviluppi più consequenziali nell'AI nel 2025. Copriremo il ciclo di ragionamento ReAct, i quattro pattern agentici, il Model Context Protocol e l'orchestrazione multi-agente.",

  "slide-50": "Un agente AI differisce da un chatbot in un modo fondamentale: agisce. Dove un chatbot restituisce testo, un agente emette istruzioni che fanno accadere cose nel mondo reale. La struttura di base è un ciclo chiamato ReAct — abbreviazione di Reason and Act. Il modello osserva lo stato attuale, ragiona su cosa fare dopo, intraprende un'azione — chiamando una funzione, interrogando un database, eseguendo codice — osserva il risultato, e ragiona di nuovo. Questo ciclo continua finché il compito non è completato. Gli agenti possono girare per minuti o ore, prendendo decine di decisioni autonome. Quel potere è accompagnato dal rischio: confini di ambito chiari e checkpoint di supervisione umana sono essenziali.",

  "slide-51": "Andrew Ng ha identificato quattro pattern agentici che rendono i workflow AI drammaticamente più capaci. Reflection: il modello genera output, poi critica e rivede il proprio lavoro — questo da solo può portare l'accuratezza della generazione di codice da circa il cinquanta percento a oltre il novanta. Tool use: il modello chiama funzioni esterne per interagire con sistemi reali. Planning: il modello decompone un compito complesso in sottocompiti prima di eseguire. Collaborazione multi-agente: più modelli specializzati lavorano come un team. L'insight chiave: i workflow agentici iterativi superano in modo coerente un singolo prompt one-shot, a volte anche usando un modello base meno capace.",

  "slide-52": "Il pattern ReAct, introdotto da Yao e colleghi nel 2022, funziona rendendo esplicita la catena di pensiero del modello nel prompt. Prima di ogni azione, il modello scrive un pensiero — il suo ragionamento sulla situazione attuale. Poi specifica l'azione. Poi osserva il risultato. Poi scrive un altro pensiero. Questo interleaving di ragionamento e azione è ciò che rende gli agenti affidabili su compiti complessi, perché il modello verbalizza il suo piano prima di eseguirlo. Rende anche il comportamento degli agenti ispezionabile: potete leggere la traccia dei pensieri e capire esattamente perché ogni decisione è stata presa. Gli agenti ben ingegnerizzati includono logica di retry e strategie di fallback per quando una chiamata a strumenti fallisce.",

  "slide-53": "La chiamata alle funzioni e l'uso degli strumenti sono il modo in cui gli agenti interagiscono con il mondo. Invece di restituire testo semplice, il modello emette un payload JSON strutturato specificando la funzione che vuole chiamare e gli argomenti da passare. Il vostro codice applicativo riceve questo JSON, esegue la funzione effettiva — chiamando un'API REST, interrogando un database, eseguendo un calcolo — e restituisce il risultato al modello. Questa architettura è cruciale per la sicurezza: il modello richiede un'azione, ma il vostro codice decide se eseguirla. Potete aggiungere validazione, rate limiting e gate di approvazione umana per azioni irreversibili. L'agente chiede; voi controllate cosa accade effettivamente.",

  "slide-54": "Il Model Context Protocol, o MCP, è stato rilasciato da Anthropic nel novembre 2024 ed è rapidamente diventato l'interfaccia standard per connettere le applicazioni AI a strumenti esterni. Prima di MCP, ogni prodotto AI doveva costruire integrazioni personalizzate per ogni strumento che necessitava — moltiplicando il carico di manutenzione in tutto l'ecosistema. MCP definisce un protocollo universale: scrivete un server MCP per il vostro strumento una volta, e qualsiasi client compatibile con MCP — Cursor, VS Code Copilot, Claude, Windsurf — può usarlo immediatamente senza lavoro aggiuntivo. È analogo al Language Server Protocol, che ha risolto lo stesso problema nel mondo IDE: scrivete un language server una volta e ogni editor compatibile ottiene il supporto gratuitamente.",

  "slide-55": "Quando un singolo agente non è sufficiente, i framework multi-agente vi permettono di orchestrare diversi agenti specializzati che lavorano insieme. LangGraph del team LangChain è l'opzione più pronta per la produzione: vi costringe a modellare il vostro agente come una macchina a stati esplicita con stati e transizioni definiti, rendendo il sistema ispezionabile, riprendibile e sicuro da interrompere per la revisione umana. AutoGen di Microsoft usa un modello di chat di gruppo dove gli agenti comunicano tramite un thread di messaggi condiviso — adatto ai workflow di dibattito e perfezionamento. Il consiglio pratico: iniziate con il singolo agente più semplice possibile e aggiungete agenti solo quando un singolo agente dimostrabilmente fallisce. La complessità nei sistemi multi-agente cresce velocemente, e così fanno le modalità di fallimento.",

  "slide-56": "I punti chiave del capitolo cinque. La differenza tra un LLM e un agente è l'azione: un agente può chiamare strumenti, eseguire codice e prendere decisioni su più passi. Il ciclo ReAct — ragiona, agisci, osserva, ripeti — è il pattern che rende gli agenti affidabili e ispezionabili. L'uso di strumenti è architetturalmente critico: il modello richiede un'azione, ma la vostra applicazione decide cosa eseguire effettivamente. MCP sta rapidamente diventando l'interfaccia universale per le integrazioni di strumenti AI. E i sistemi multi-agente aggiungono complessità velocemente — iniziate con il design più semplice e aggiungete agenti solo quando un singolo agente dimostrabilmente fallisce.",

  "slide-57": "I riferimenti chiave del capitolo cinque. Il paper ReAct di Yao e colleghi è il lavoro fondamentale sulla combinazione di ragionamento e azione negli agenti AI. La documentazione del Model Context Protocol di Anthropic descrive lo standard aperto ora ampiamente adottato negli strumenti di sviluppo AI. I corsi brevi di DeepLearning.AI su agenti e uso di strumenti sono la migliore introduzione pratica — diversi sono gratuiti. La documentazione ed esempi di LangGraph sono eccellenti per chiunque costruisca sistemi agentici pronti per la produzione.",

  /* ── CAPITOLO 6 ──────────────────────────────────────────── */

  "chapter-6": "Il capitolo sei pone la domanda più difficile: solo perché l'AI può fare qualcosa, dovrebbe farlo — e in quali condizioni? Dopo cinque capitoli sulle capacità, questo capitolo riguarda la responsabilità. Guarderemo casi documentati in cui i sistemi AI hanno causato danni reali: strumenti di assunzione distorti, punteggi di rischio di recidiva difettosi, citazioni legali fabricate e frodi deepfake. Copriremo l'EU AI Act, la prima legge vincolante al mondo sull'AI. E discuteremo framework di governance che potete applicare alle vostre distribuzioni. L'AI responsabile non è un freno all'innovazione — è ciò che rende l'innovazione degna di fiducia.",

  "slide-59": "Le due limitazioni più importanti degli attuali modelli AI sono il bias e l'allucinazione. Bias: i modelli imparano pattern da dati generati da esseri umani — inclusi i pregiudizi umani. Un modello di assunzione addestrato su dati storici può imparare a preferire certi gruppi demografici non perché sia stato programmato per farlo, ma perché quel pattern esisteva nel training set. Allucinazione: i modelli generano testo che suona sicuro e fluente ma è fattualmente errato. Questo succede perché il modello predice token statisticamente plausibili, non recupera fatti verificati. Entrambi sono fallimenti prevedibili e sistematici. Progettate i vostri sistemi AI con queste modalità di fallimento in mente fin dal primo giorno.",

  "slide-60": "L'EU AI Act dell'Unione Europea è la prima legge AI completa e vincolante al mondo, entrata in vigore nell'agosto 2024. Utilizza un approccio a livelli basato sul rischio. La maggior parte delle applicazioni rientra in categorie di rischio minimo o limitato con requisiti leggeri di trasparenza. Le applicazioni ad alto rischio — quelle che influenzano l'assunzione, il credito, le forze dell'ordine, l'accesso all'istruzione o i servizi essenziali — affrontano requisiti rigorosi: documentazione tecnica, supervisione umana, test di accuratezza e registrazione nel database dell'UE. La non conformità rischia multe fino a trentacinque milioni di euro o il sette percento del fatturato annuo globale. Se la vostra organizzazione distribuisce AI in qualsiasi categoria ad alto rischio nell'UE, la compliance è un obbligo legale.",

  "slide-61": "I fallimenti AI nel mondo reale ci insegnano più su rischio di qualsiasi scenario ipotetico. Lo strumento interno di assunzione di Amazon, addestrato su un decennio di curriculum tech dominati da uomini, ha sistematicamente declassato le candidature di donne — è stato discontinuato nel 2018. COMPAS, uno strumento di previsione della recidiva usato nei tribunali statunitensi, è stato trovato a segnalare i imputati neri come ad alto rischio al doppio del tasso rispetto agli imputati bianchi comparabili. Un avvocato di New York ha presentato un atto legale pieno di citazioni di casi generate dall'AI — ogni caso era fabbricato. Questi fallimenti condividono un pattern: la tecnologia ha funzionato esattamente come progettata. La governance intorno a essa no.",

  "slide-62": "Altri due casi documentati dal 2023 e 2024 illustrano le poste in gioco. Lo strumento AI di pre-autorizzazione di UnitedHealth ha negato la copertura dell'assistenza infermieristica per pazienti Medicare anziani con un tasso di errore del novanta percento — scavalcando le raccomandazioni dei medici per migliaia di persone. Il chatbot del servizio clienti di Air Canada ha creato una policy di tariffa per lutto fabricata e l'ha promessa a un cliente in lutto; la compagnia è stata ritenuta legalmente responsabile per l'invenzione dell'AI. Entrambi illustrano lo stesso fallimento sistemico: un sistema AI distribuito in un dominio consequenziale senza adeguata supervisione umana o percorso di escalation.",

  "slide-63": "Tre framework complementari danno struttura alla governance AI oggi. Il NIST AI Risk Management Framework organizza la governance intorno a quattro funzioni: Govern, Map, Measure e Manage — familiare alle organizzazioni che usano già il NIST Cybersecurity Framework. ISO 42001, pubblicato nel dicembre 2023, è il primo standard certificabile di sistema di gestione AI; si allinea con ISO 27001, rendendo semplice estendere le certificazioni di sicurezza esistenti per coprire l'AI. L'EU AI Act è il layer legale vincolante per le operazioni nell'UE. Insieme, questi tre framework danno alle organizzazioni un percorso strutturato e auditabile verso la distribuzione AI responsabile.",

  "slide-64": "L'AI responsabile non è una checklist una-tantum — è una disciplina continua. Prima di distribuire qualsiasi sistema AI, documentate cosa fa, su quali dati si basa, e quali danni potrebbe causare a gruppi specifici di utenti. Testatelo con profili diversi — non assumete che perché il sistema funziona per un gruppo demografico funzioni ugualmente per tutti. Fate red-teaming deliberatamente: cercate di ingannarlo, spingetelo verso modalità di fallimento, e testate per vulnerabilità di prompt injection. Costruite la spiegabilità fin dall'inizio — retrometterla è costoso e spesso inadeguato. E definite percorsi di escalation chiari per quando il sistema produce output dannosi o errati in produzione. L'AI che potete spiegare e controllare è l'AI di cui potete fidarvi.",

  "slide-65": "Dove sta andando l'AI? Alcune tendenze sono già chiare. Le finestre di contesto continuano a crescere, abilitando i modelli a ragionare su interi codebase e collezioni di documenti simultaneamente. I modelli multimodali elaborano testo, immagini, audio e video nativamente. L'autonomia degli agenti si espande, con i sistemi AI che gestiscono workflow più lunghi e complessi con meno intervento umano. I costi di inferenza continuano a scendere. I ruoli più a rischio sono quelli che possono essere completamente descritti come un pattern ripetibile e ben specificato. I ruoli che crescono sono quelli che richiedono giudizio, empatia, ragionamento etico e creatività contestuale. La migliore preparazione: rimanete curiosi, costruite cose, e sviluppate una relazione critica e informata con questi strumenti.",

  "slide-66": "I punti chiave del capitolo sei. Bias e allucinazione non sono fallimenti casuali — sono conseguenze prevedibili di come questi sistemi vengono addestrati. Ogni fallimento AI nel mondo reale che abbiamo esaminato era prevenibile con una governance appropriata. L'EU AI Act crea obblighi legali per le applicazioni ad alto rischio nell'Europa, e i regolatori a livello globale stanno seguendo la sua guida. La pratica AI responsabile — trasparenza, equità, supervisione umana e percorsi di escalation chiari — non è teatro di compliance. È ciò che rende i sistemi AI abbastanza degni di fiducia da distribuire su larga scala.",

  "slide-67": "I riferimenti chiave del capitolo sei. Il testo ufficiale dell'EU AI Act e la timeline di implementazione sono letture essenziali per chiunque distribuisca AI in Europa. Stochastic Parrots di Bender, Gebru e colleghi è un'analisi critica fondamentale dei modelli linguistici di grandi dimensioni e i rischi che portano. L'indagine COMPAS di ProPublica è lettura obbligatoria sul bias algoritmico nella giustizia penale. La documentazione NIST AI RMF e ISO 42001 fornisce i framework di governance discussi in questo capitolo.",

  "slide-68": "Questa tabella vi dà una mappa pratica di dove l'AI offre valore misurabile nei vari settori oggi. La finanza usa l'AI per rilevamento frodi, scoring del credito e elaborazione documenti — tutto in produzione nelle principali istituzioni. La sanità la applica alla sintesi delle note cliniche, all'analisi delle immagini radiologiche e all'analisi delle interazioni farmacologiche — con supervisione umana su tutte le decisioni cliniche. Gli studi legali usano l'AI per la revisione dei contratti e la ricerca dei casi. Il manifatturiero la applica alla manutenzione predittiva e al controllo qualità. Il retail la usa per la personalizzazione, le previsioni della domanda e l'ottimizzazione della supply chain. Il pattern in tutti i settori: l'AI gestisce il lavoro ad alto volume di pattern-matching così che gli esseri umani possano concentrarsi sul giudizio e sulla gestione delle eccezioni.",

  /* ── CONCLUSIONE ─────────────────────────────────────────── */

  "conclusion": "Abbiamo raggiunto la conclusione. Sei capitoli — dalla matematica dell'attenzione dei transformer all'etica degli agenti autonomi. Prendiamo un momento per consolidare le idee più importanti prima di chiudere.",

  "slide-70": "Ecco il riassunto di tutti sei i capitoli. Capitolo uno: gli LLM sono predittori probabilistici di token — codificano pattern statistici, non fatti, e la scala è ciò che ha sbloccato le capacità. Capitolo due: il prompt engineering è l'arte di comunicare con precisione — ruolo, contesto, formato ed esempi migliorano drasticamente la qualità dell'output. Capitolo tre: il coding assistito da AI offre guadagni di produttività reali ma amplifica qualsiasi competenza e abitudine portiate. Capitolo quattro: il RAG connette l'AI ai vostri dati privati recuperando documenti al momento della query — nessun ri-addestramento, sempre aggiornato. Capitolo cinque: gli agenti agiscono — si muovono in cicli reason-act-observe usando strumenti per completare compiti multi-step autonomamente. Capitolo sei: l'AI responsabile è una disciplina ingegneristica, non un ripensamento.",

  "slide-71": "Quattro intuizioni da portare con sé oltre questo corso. Prima: gli LLM sono macchine di pattern, non database di fatti. Predicono il prossimo token, non la verità. Verificate ogni output che conta. Seconda: i prompt sono programmi. I prompt strutturati superano in modo coerente le richieste vaghe — trattate il prompt engineering con lo stesso rigore che applicate al codice. Terza: il contesto è tutto. Ciò che mettete nella finestra di contesto — ruolo, background, esempi, vincoli — determina la qualità di ciò che ne esce. Quarta: i sistemi AI hanno bisogno di governance. Ogni distribuzione ad alto rischio dovrebbe avere una chiara traccia di audit, un percorso di override umano e una valutazione regolare per bias e accuratezza.",

  "slide-72": "Ecco le risorse che raccomando per continuare questo percorso. Per le fondamenta: i corsi brevi di DeepLearning.AI di Andrew Ng coprono transformer, RAG e agenti in poche ore ciascuno. La serie Zero to Hero di Andrej Karpathy costruisce la comprensione delle reti neurali da zero in codice. Il corso NLP di HuggingFace è la migliore introduzione strutturata alla libreria transformer. Per rimanere aggiornati: il podcast Latent Space copre la ricerca AI di frontiera in profondità, e la pagina HuggingFace Daily Papers traccia nuove pubblicazioni non appena vengono pubblicate. L'abitudine più preziosa è la lettura curata e coerente — anche trenta minuti a settimana vi mantiene orientati in questo campo in rapida evoluzione.",

  "slide-73": "Abbiamo raggiunto la fine di questo corso. L'intelligenza artificiale è uno strumento straordinario — e come qualsiasi strumento potente, il suo valore dipende interamente dall'intento, dal giudizio e dalla cura delle persone che lo utilizzano. I modelli continueranno a migliorare. I principi che abbiamo coperto — radicare gli output, progettare per la supervisione, testare per il bias, costruire la responsabilità in modo nativo — rimarranno rilevanti indipendentemente da quali sistemi specifici esistano tra un anno o cinque. Rimanete curiosi. Costruite cose. E se avete domande mentre applicate queste idee, sono sempre raggiungibile su LinkedIn. Grazie.",

  /* ── ANNESSO ─────────────────────────────────────────────── */

  "annex": "L'annesso è la vostra sezione di riferimento. Contiene diagrammi, cheat sheet e materiale di supporto per i sei capitoli. Tornate a queste slide ogni volta che avete bisogno di un riferimento visivo rapido o di uno sguardo più approfondito su un concetto specifico.",

  "slide-75": "Questa visualizzazione mostra il meccanismo di auto-attenzione in azione. Ogni riga rappresenta un token che interroga tutti gli altri nella frase. Più una cella è luminosa, più forte è il peso di attenzione — il che significa che quei due token sono strettamente correlati nella visione del modello. Notate come la parola esso attende fortemente gatto — il modello ha imparato a risolvere i riferimenti pronominali senza regole grammaticali esplicite. Questo comportamento emerge interamente dall'addestramento su miliardi di frasi. I transformer moderni eseguono multiple teste di attenzione in parallelo, ognuna tracciando diverse relazioni linguistiche: accordo soggetto-verbo, coppie aggettivo-nome e coreferenza a lungo raggio.",

  "slide-76": "Il cheat sheet dei pattern di prompt engineering è la vostra scheda di riferimento pratica. Il pattern Role assegna una persona esperta per migliorare profondità e stile. Chain-of-Thought forza il ragionamento passo dopo passo prima della risposta finale — essenziale per matematica, logica e compiti multi-step. Few-Shot fornisce esempi già risolti per dimostrare il formato esatto di cui avete bisogno. Tree of Thought esplora molteplici percorsi di ragionamento simultaneamente. Meta-Prompting istruisce il modello a generare o rifinire un prompt per un dato compito. Usate questa scheda come checklist ogni volta che state progettando un nuovo prompt per l'uso in produzione.",

  "slide-77": "Questo diagramma mostra il ciclo di vita completo di una singola richiesta AI. Un utente o un'applicazione invia un prompt. Il testo viene tokenizzato — convertito in ID interi a circa tre quarti di parola per token. Quei token scorrono attraverso i layer di attenzione e feed-forward dell'LLM, opzionalmente aumentati da chiamate a strumenti o un passo di recupero RAG. Il modello genera probabilità di token, campiona il prossimo token e lo aggiunge — ripetendo fino al completamento. L'output ritorna all'applicazione, dove può essere analizzato, validato e visualizzato. Il passo critico che la maggior parte degli sviluppatori sottovaluta è la validazione umana: trattate l'output AI come una bozza sicura, non una risposta definitiva, in qualsiasi contesto ad alto rischio.",

  "slide-78": "Lo stack AI moderno ha quattro livelli. In cima, il layer applicativo: l'interfaccia chat, l'app web o l'API gateway con cui gli utenti interagiscono. Sotto, il layer di orchestrazione: agenti, planner e logica di ragionamento multi-step implementati con LangGraph, AutoGen o MCP. Poi il layer di inferenza: il modello linguistico stesso, accessibile tramite API gestita o self-hosted per la sovranità dei dati. Alla base, il layer dati: database vettoriali, archivi di documenti e fonti di dati strutturati da cui le pipeline RAG attingono. Capire in quale layer vive un problema aiuta a scegliere la soluzione giusta e il team giusto per costruirla.",

  "slide-79": "Allargando la vista all'intero ecosistema: in cima, utenti e interfacce — chat UI, plugin IDE, app mobile e consumatori di API. Sotto, il layer applicativo gestisce routing, caching e rate limiting. Un layer di ragionamento dove gli agenti decompongono i compiti e orchestrano le chiamate agli strumenti. Un layer di inferenza dove il modello linguistico elabora il contesto e genera testo. Un layer di recupero per il RAG — ricerca vettoriale e archivi di documenti. E alla base, l'infrastruttura: cluster GPU, cloud provider, monitoraggio e strumenti di compliance. Ogni layer è un potenziale punto di integrazione, un'opportunità di ottimizzazione e un checkpoint di governance.",

  "slide-80": "Il costo dell'AI è guidato da tre variabili. Dimensione del modello: i modelli più grandi costano da dieci a cento volte di più per chiamata rispetto a quelli più piccoli — GPT-4o mini o Claude Haiku offrono la maggior parte delle capacità a una frazione del costo di GPT-4o. Conteggio dei token: il prezzo è per token, e i token di output tipicamente costano da tre a cinque volte di più dei token di input. Frequenza delle chiamate: anche costi modesti per chiamata diventano significativi su larga scala. Il consiglio pratico: testate sempre prima i modelli più piccoli sul vostro compito specifico. Spesso troverete che un modello che costa dieci volte di meno offre il novanta percento della qualità di cui avete bisogno.",

  "slide-81": "Questa slide documenta i file sorgente di diagrammi PlantUML inclusi in questo repository. Ogni diagramma nel corso ha un corrispondente file dot-puml nella cartella diagrams, insieme a un file dot-link che punta alla versione renderizzata. I diagrammi coprono l'architettura del transformer, il ciclo di vita completo degli LLM, l'ecosistema degli agenti AI, il flusso della pipeline RAG, il workflow di sviluppo assistito da AI e altro ancora. Se volete adattare qualsiasi diagramma per le vostre presentazioni: fate un fork del repository, modificate il sorgente dot-puml e rigenerate. PlantUML vi dà diagrammi testuale con controllo versione che si aggiornano in modo pulito quando il contenuto cambia.",

  "slide-82": "HuggingFace è ai modelli AI ciò che GitHub è al codice sorgente — il repository centrale dove i ricercatori pubblicano i pesi e gli sviluppatori li scaricano. La libreria Transformers fornisce un'API Python coerente che funziona su tutte le principali architetture, quindi cambiare modello è una modifica di una riga. GGUF è un formato di file che impacchetta i pesi del modello e i metadati dell'architettura in un singolo file autonomo, introdotto nel 2023 come standard di distribuzione locale portatile. La quantizzazione riduce la precisione numerica dei pesi del modello — dai float a 32 bit agli interi a 4 bit — rendendo i modelli circa quattro volte più piccoli con minima perdita di qualità. La variante Q4-K-M è ampiamente considerata il miglior compromesso tra dimensione e qualità per l'uso locale.",

  "slide-83": "Eseguire modelli linguistici localmente — sul proprio hardware, senza dipendenza dal cloud — è sempre più pratico. Ollama è il punto di partenza più semplice: avvolge i modelli locali in un'API REST compatibile OpenAI su porta 11434, quindi si passa dal cloud al locale cambiando un singolo URL. LM Studio fornisce un'interfaccia desktop curata con un browser di modelli integrato. LLaMA dot cpp è il motore di inferenza sottostante scritto in C++, che supporta l'accelerazione CPU e GPU su tutte le piattaforme. Il vincolo principale è la RAM: un modello con sette miliardi di parametri a quantizzazione a 4 bit necessita di circa quattro gigabyte — la maggior parte dei laptop moderni può gestirlo. I Mac Apple silicon sono particolarmente adatti perché la loro memoria unificata serve sia i carichi di lavoro CPU che GPU."

};
